@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    enum "<size:14>LoginResponse.ErrorMessage\n<size:10>com.hack23.cia.service.api.action.application" as com.hack23.cia.service.api.action.application.LoginResponse.ErrorMessage [[LoginResponse.ErrorMessage.html]] {
        {static} +USERNAME_OR_PASSWORD_DO_NOT_MATCH
    }

    class "<size:14>LoginResponse\n<size:10>com.hack23.cia.service.api.action.application" as com.hack23.cia.service.api.action.application.LoginResponse [[LoginResponse.html]]

    com.hack23.cia.service.api.action.application.LoginResponse +-- com.hack23.cia.service.api.action.application.LoginResponse.ErrorMessage

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
