@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>LoginRequest\n<size:10>com.hack23.cia.service.api.action.application" as com.hack23.cia.service.api.action.application.LoginRequest [[LoginRequest.html]] {
        +getEmail(): String
        +setEmail(String): void
        +getUserpassword(): String
        +setUserpassword(String): void
        +getSessionId(): String
        +setSessionId(String): void
        +getOtpCode(): String
        +setOtpCode(String): void
    }

    abstract class "<size:14>AbstractRequest\n<size:10>com.hack23.cia.service.api.action.common" as com.hack23.cia.service.api.action.common.AbstractRequest [[../common/AbstractRequest.html]]

    com.hack23.cia.service.api.action.common.AbstractRequest <|-- com.hack23.cia.service.api.action.application.LoginRequest

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
