@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>LoginResponse\n<size:10>com.hack23.cia.service.api.action.application" as com.hack23.cia.service.api.action.application.LoginResponse [[LoginResponse.html]] {
        +LoginResponse(ServiceResult)
    }

    abstract class "<size:14>AbstractResponse\n<size:10>com.hack23.cia.service.api.action.common" as com.hack23.cia.service.api.action.common.AbstractResponse [[../common/AbstractResponse.html]]
    enum "<size:14>LoginResponse.ErrorMessage\n<size:10>com.hack23.cia.service.api.action.application" as com.hack23.cia.service.api.action.application.LoginResponse.ErrorMessage [[LoginResponse.ErrorMessage.html]]

    com.hack23.cia.service.api.action.common.AbstractResponse <|-- com.hack23.cia.service.api.action.application.LoginResponse
    com.hack23.cia.service.api.action.application.LoginResponse +-- com.hack23.cia.service.api.action.application.LoginResponse.ErrorMessage

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
