@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    enum "<size:14>RegisterUserResponse.ErrorMessage\n<size:10>com.hack23.cia.service.api.action.application" as com.hack23.cia.service.api.action.application.RegisterUserResponse.ErrorMessage [[RegisterUserResponse.ErrorMessage.html]] {
        {static} +USER_ALREADY_EXIST
    }

    class "<size:14>RegisterUserResponse\n<size:10>com.hack23.cia.service.api.action.application" as com.hack23.cia.service.api.action.application.RegisterUserResponse [[RegisterUserResponse.html]]

    com.hack23.cia.service.api.action.application.RegisterUserResponse +-- com.hack23.cia.service.api.action.application.RegisterUserResponse.ErrorMessage

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
