@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    abstract class "<size:14>AbstractMenuItemFactoryImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl" as com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl.AbstractMenuItemFactoryImpl [[AbstractMenuItemFactoryImpl.html]] {
        #createButtonLink(ResponsiveRow, String, Resource, ClickListener, String): void
        #initApplicationMenuBar(MenuBar): void
    }

    center footer UMLDoclet 2.0.4, PlantUML 1.2019.06
@enduml
