@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>CommitteeMenuItemFactoryImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl" as com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl.CommitteeMenuItemFactoryImpl [[CommitteeMenuItemFactoryImpl.html]] {
        +createCommitteeeMenuBar(MenuBar, String): void
        +createOverviewPage(VerticalLayout, String): void
    }

    abstract class "<size:14>AbstractMenuItemFactoryImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl" as com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl.AbstractMenuItemFactoryImpl [[AbstractMenuItemFactoryImpl.html]]
    interface "<size:14>CommitteeMenuItemFactory\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.menufactory.api" as com.hack23.cia.web.impl.ui.application.views.common.menufactory.api.CommitteeMenuItemFactory [[../api/CommitteeMenuItemFactory.html]] {
        {abstract} +createCommitteeeMenuBar(MenuBar, String): void
        {abstract} +createOverviewPage(VerticalLayout, String): void
    }

    com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl.AbstractMenuItemFactoryImpl <|-- com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl.CommitteeMenuItemFactoryImpl
    com.hack23.cia.web.impl.ui.application.views.common.menufactory.api.CommitteeMenuItemFactory <|.. com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl.CommitteeMenuItemFactoryImpl

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
