@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>MinistryRankingMenuItemFactoryImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl" as com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl.MinistryRankingMenuItemFactoryImpl [[MinistryRankingMenuItemFactoryImpl.html]] {
        +createMinistryRankingMenuBar(MenuBar): void
        +createMinistryRankingTopics(MenuItem): void
        +createOverviewPage(VerticalLayout): void
    }

    abstract class "<size:14>AbstractMenuItemFactoryImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl" as com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl.AbstractMenuItemFactoryImpl [[AbstractMenuItemFactoryImpl.html]]
    interface "<size:14>MinistryRankingMenuItemFactory\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.menufactory.api" as com.hack23.cia.web.impl.ui.application.views.common.menufactory.api.MinistryRankingMenuItemFactory [[../api/MinistryRankingMenuItemFactory.html]] {
        {abstract} +createMinistryRankingMenuBar(MenuBar): void
        {abstract} +createMinistryRankingTopics(MenuItem): void
        {abstract} +createOverviewPage(VerticalLayout): void
    }

    com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl.AbstractMenuItemFactoryImpl <|-- com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl.MinistryRankingMenuItemFactoryImpl
    com.hack23.cia.web.impl.ui.application.views.common.menufactory.api.MinistryRankingMenuItemFactory <|.. com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl.MinistryRankingMenuItemFactoryImpl

    center footer UMLDoclet 2.0.4, PlantUML 1.2019.06
@enduml
