@startuml
    namespace com.hack23.cia.web.impl.ui.application.views.common.converters {

        class ListPropertyConverter [[ListPropertyConverter.html]] {
            +ListPropertyConverter(String, String)
            +ListPropertyConverter(String, String, String)
            +apply(Object): String
            +convertToModel(String, ValueContext): Result<List<?>>
            +convertToPresentation(List, ValueContext): String
            +getColumn(): String
        }

        com.vaadin.data.Converter <|.. ListPropertyConverter
        com.vaadin.data.ValueProvider <|.. ListPropertyConverter
    }

    namespace com.vaadin.data {
        interface Converter<PRESENTATION, MODEL> {
            {abstract} +convertToModel(PRESENTATION, ValueContext): Result<MODEL>
            {abstract} +convertToPresentation(MODEL, ValueContext): PRESENTATION
            {static} +identity(): Converter<T, T>
            {static} +from(SerializableFunction<P, M>, SerializableFunction<M, P>, SerializableFunction<Exception, String>): Converter<P, M>
            {static} +from(SerializableFunction<P, Result<M>>, SerializableFunction<M, P>): Converter<P, M>
            +chain(Converter<MODEL, T>): Converter<PRESENTATION, T>
        }
        interface ValueProvider<SOURCE, TARGET> {
            {static} +identity(): ValueProvider<T, T>
            {abstract} +apply(SOURCE): TARGET
        }
    }

    center footer UMLDoclet 2.0.7, PlantUML 1.2019.12
@enduml
