@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    abstract class "<size:14>AbstractPersonView\n<size:10>com.hack23.cia.web.impl.ui.application.views.user.common" as com.hack23.cia.web.impl.ui.application.views.user.common.AbstractPersonView [[AbstractPersonView.html]] {
        +AbstractPersonView(Map<String, PageModeContentFactory>, String)
    }

    abstract class "<size:14>AbstractActorView\n<size:10>com.hack23.cia.web.impl.ui.application.views.user.common" as com.hack23.cia.web.impl.ui.application.views.user.common.AbstractActorView [[AbstractActorView.html]]

    com.hack23.cia.web.impl.ui.application.views.user.common.AbstractActorView <|-- com.hack23.cia.web.impl.ui.application.views.user.common.AbstractPersonView

    center footer UMLDoclet 2.0.6, PlantUML 1.2019.12
@enduml
