@startuml
    namespace com.hack23.cia.web.impl.ui.application.views.common.sizing {

        class ContentSize [[ContentSize.html]] {
            {static} +FULL_SIZE: String
            {static} +HALF_SIZE: String
        }

        class ContentRatio [[ContentRatio.html]] {
            {static} +CHART: float
            {static} +FULL_SIZE: float
            {static} +GRID: float
            {static} +LARGE: float
            {static} +LARGE_FORM: float
            {static} +SMALL: float
            {static} +SMALL_GRID: float
            {static} +SMALL2: float
            {static} +SMALL3: float
        }

    }

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
