@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>AdminAgencyView\n<size:10>com.hack23.cia.web.impl.ui.application.views.admin.system" as com.hack23.cia.web.impl.ui.application.views.admin.system.AdminAgencyView [[AdminAgencyView.html]] {
        {static} +NAME: String
        +AdminAgencyView(ApplicationContext)
    }

    abstract class "<size:14>AbstractAdminView\n<size:10>com.hack23.cia.web.impl.ui.application.views.admin.common" as com.hack23.cia.web.impl.ui.application.views.admin.common.AbstractAdminView [[../common/AbstractAdminView.html]]

    com.hack23.cia.web.impl.ui.application.views.admin.common.AbstractAdminView <|-- com.hack23.cia.web.impl.ui.application.views.admin.system.AdminAgencyView

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
