@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    abstract class "<size:14>AbstractBusinessServiceImpl\n<size:10>com.hack23.cia.service.impl.action.common" as com.hack23.cia.service.impl.action.common.AbstractBusinessServiceImpl<T extends ServiceRequest, V extends ServiceResponse> [[AbstractBusinessServiceImpl.html]] {
        #createApplicationEventService: BusinessService<CreateApplicationEventRequest, CreateApplicationEventResponse>
        +AbstractBusinessServiceImpl(Class<T extends ServiceRequest>)
        #getCreateApplicationEventService(): BusinessService<CreateApplicationEventRequest, CreateApplicationEventResponse>
        {abstract} #createErrorResponse(): V extends ServiceResponse
        #inputValidation(T extends ServiceRequest): V extends ServiceResponse
        #createBaseApplicationEventRequest(): CreateApplicationEventRequest
        {abstract} #createApplicationEventForService(T extends ServiceRequest): CreateApplicationEventRequest
    }

    abstract class "<size:14>AbstractCommonBusinessServiceImpl\n<size:10>com.hack23.cia.service.impl.action.common" as com.hack23.cia.service.impl.action.common.AbstractCommonBusinessServiceImpl<T extends ServiceRequest, V extends ServiceResponse> [[AbstractCommonBusinessServiceImpl.html]]
    interface "<size:14>BusinessService\n<size:10>com.hack23.cia.service.impl.action.common" as com.hack23.cia.service.impl.action.common.BusinessService<T extends ServiceRequest, V extends ServiceResponse> [[BusinessService.html]] {
        {abstract} +getSupportedService(): Class<? extends ServiceRequest>
        {abstract} +processService(T extends ServiceRequest): V extends ServiceResponse
    }

    com.hack23.cia.service.impl.action.common.AbstractCommonBusinessServiceImpl <|-- com.hack23.cia.service.impl.action.common.AbstractBusinessServiceImpl
    com.hack23.cia.service.impl.action.common.BusinessService <|.. com.hack23.cia.service.impl.action.common.AbstractBusinessServiceImpl

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
