@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>BusinessService\n<size:10>com.hack23.cia.service.impl.action.common" as com.hack23.cia.service.impl.action.common.BusinessService<T extends ServiceRequest, V extends ServiceResponse> [[BusinessService.html]] {
        {abstract} +getSupportedService(): Class<? extends ServiceRequest>
        {abstract} +processService(T extends ServiceRequest): V extends ServiceResponse
    }

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
