@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>EmailService\n<size:10>com.hack23.cia.service.impl.email" as com.hack23.cia.service.impl.email.EmailService [[EmailService.html]] {
        {abstract} +sendEmail(String, String, String): void
    }

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
