package com.hack23.cia.service.impl.rules
 
import com.hack23.cia.model.internal.application.data.party.impl.ViewRiksdagenPartySummary
 
rule "We have an inactive ViewRiksdagenPartySummary"
    when
        exists( ViewRiksdagenPartySummary(currentAssignments == 0) )
    then
        System.out.println("inactive");
end

rule "We have an active ViewRiksdagenPartySummary"
    when
        exists( ViewRiksdagenPartySummary(currentAssignments > 0) )
    then
        System.out.println("active");
end