package com.hack23.cia.service.impl.rules
 
import com.hack23.cia.model.internal.application.data.party.impl.ViewRiksdagenPartySummary
import com.hack23.cia.service.api.action.kpi.Status
import com.hack23.cia.service.impl.rules.ComplianceCheckImpl

rule "We have an active Party with no government experience"
    when
        exists( ViewRiksdagenPartySummary( active == true && totalDaysServedGovernment == 0 ) )
    then
        insert( new ComplianceCheckImpl() );
end
