package com.hack23.cia.service.impl.rules
 
import com.hack23.cia.model.internal.application.data.politician.impl.ViewRiksdagenPolitician;
 
rule "We have an old Politician"
    when
        exists( ViewRiksdagenPolitician(bornYear < 1970) )
    then
        System.out.println("old");
end

rule "We have an young Politician"
    when
        exists( ViewRiksdagenPolitician(bornYear > 1970) )
    then
        System.out.println("young");
end
