package com.hack23.cia.service.impl.rules
 
import com.hack23.cia.model.internal.application.data.politician.impl.ViewRiksdagenPolitician
import com.hack23.cia.service.api.action.kpi.Status
import com.hack23.cia.service.impl.rules.PoliticianComplianceCheckImpl

rule "We have an politician minister that has no experience from parliament"
	dialect "java"
    when
        $p : PoliticianComplianceCheckImpl(politician.activeGovernment == true && politician.totalDaysServedCommittee == 0)
    then
    	modify( $p ) {
      		setStatus( Status.MINOR )
		}
end
