package com.hack23.cia.service.impl.rules
 
import com.hack23.cia.model.internal.application.data.politician.impl.ViewRiksdagenPolitician
import com.hack23.cia.service.api.action.kpi.Status
import com.hack23.cia.service.impl.rules.ComplianceCheckImpl

rule "We have an politician that left the party still holding assignments"
    when
        exists( ViewRiksdagenPolitician(party == "-" && active == true ) )
    then
        insert( new ComplianceCheckImpl() );
end