@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>DataContainer\n<size:10>com.hack23.cia.service.api" as com.hack23.cia.service.api.DataContainer<T extends Serializable, I extends Serializable> [[DataContainer.html]] {
        {abstract} +getAll(): List<T extends Serializable>
        {abstract} +getAllOrderBy(SingularAttribute<T extends Serializable, ? extends Object>): List<T extends Serializable>
        {abstract} +getPage(int, int): List<T extends Serializable>
        {abstract} +getPageOrderBy(int, int, SingularAttribute<T extends Serializable, ? extends Object>): List<T extends Serializable>
        {abstract} +getAllBy(SingularAttribute<T extends Serializable, ? extends Object>, Object): List<T extends Serializable>
        {abstract} +findListByProperty(Object..., SingularAttribute<T extends Serializable, ? extends Object>...): List<T extends Serializable>
        {abstract} +findOrderedListByProperty(SingularAttribute<T extends Serializable, ? extends Object>, Object, SingularAttribute<T extends Serializable, ? extends Object>): List<T extends Serializable>
        {abstract} +findOrderedListByProperty(SingularAttribute<T extends Serializable, ? extends Object>, Object..., SingularAttribute<T extends Serializable, ? extends Object>...): List<T extends Serializable>
        {abstract} +findByQueryProperty(Class<T>, SingularAttribute<T, ? extends Object>, Class<V>, SingularAttribute<V, ? extends Object>, Object): T
        {abstract} +findListByEmbeddedProperty(Class<T>, SingularAttribute<T, V>, Class<V>, SingularAttribute<V, ? extends Object>, Object): List<T>
        {abstract} +findOrderedListByEmbeddedProperty(Class<T>, SingularAttribute<T, V>, Class<V>, SingularAttribute<V, ? extends Object>, Object, SingularAttribute<V, ? extends Object>): List<T>
        {abstract} +findOrderedByPropertyListByEmbeddedProperty(Class<T>, SingularAttribute<T, V>, Class<V>, SingularAttribute<V, ? extends Object>, Object, SingularAttribute<T, ? extends Object>): List<T>
        {abstract} +load(I extends Serializable): T extends Serializable
        {abstract} +getSize(): Long
    }

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
