@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    abstract class "<size:14>AbstractPageModContentFactoryImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.pagemode" as com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractPageModContentFactoryImpl [[AbstractPageModContentFactoryImpl.html]] {
        {static} +CURRENT_PAGE_VISIT_HISTORY: String
        {static} +DEFAULT_RESULTS_PER_PAGE: int
        {static} +GENERAL_PAGE_MODE_PAGE_VISIT: String
        #createPageVisitHistory(String, String, VerticalLayout): void
        #createPanelContent(): VerticalLayout
        #getAdminChartDataManager(): AdminChartDataManager
        #getApplicationManager(): ApplicationManager
        #getFormFactory(): FormFactory
        #getGridFactory(): GridFactory
        #getMenuItemFactory(): ApplicationMenuItemFactory
        #getPageActionEventHelper(): PageActionEventHelper
        #getPageId(String): String
        #getPageLinkFactory(): PageLinkFactory
        #getPageNr(String): int
    }

    interface "<size:14>PageModeContentFactory\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.pagemode" as com.hack23.cia.web.impl.ui.application.views.common.pagemode.PageModeContentFactory [[PageModeContentFactory.html]] {
        {abstract} +createContent(String, MenuBar, Panel): Layout
        {abstract} +matches(String, String): boolean
        {abstract} +validReference(String): boolean
    }

    com.hack23.cia.web.impl.ui.application.views.common.pagemode.PageModeContentFactory <|.. com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractPageModContentFactoryImpl

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
