@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>VaultManager\n<size:10>com.hack23.cia.service.impl.action.application.encryption" as com.hack23.cia.service.impl.action.application.encryption.VaultManager [[VaultManager.html]] {
        {abstract} +getEncryptedValue(String, UserAccount): String
        {abstract} +encryptValue(String, String, String): String
        {abstract} +decryptValue(String, String, String): String
    }

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
