//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.25 at 12:05:09 AM CET 
//


package com.hack23.cia.model.internal.application.user.impl;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.OrderColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.hack23.cia.model.common.api.ModelObject;
import com.hack23.cia.model.common.impl.xml.XmlDateTimeTypeAdapter;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for UserAccount complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserAccount"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="modelObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="modelObjectVersion" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="userpassword" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="numberOfVisits" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="userType" type="{http://user.application.internal.model.cia.hack23.com/impl}UserType" minOccurs="0"/&gt;
 *         &lt;element name="userRole" type="{http://user.application.internal.model.cia.hack23.com/impl}UserRole" minOccurs="0"/&gt;
 *         &lt;element name="userLockStatus" type="{http://user.application.internal.model.cia.hack23.com/impl}UserLockStatus" minOccurs="0"/&gt;
 *         &lt;element name="userEmailStatus" type="{http://user.application.internal.model.cia.hack23.com/impl}UserEmailStatus" minOccurs="0"/&gt;
 *         &lt;element name="createdDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserAccount", propOrder = {
    "modelObjectId",
    "modelObjectVersion",
    "country",
    "username",
    "email",
    "userId",
    "userpassword",
    "numberOfVisits",
    "address",
    "userType",
    "userRole",
    "userLockStatus",
    "userEmailStatus",
    "createdDate"
})
@Entity(name = "UserAccount")
@Table(name = "USER_ACCOUNT")
@Inheritance(strategy = InheritanceType.JOINED)
public class UserAccount
    implements Serializable, ModelObject, Equals, HashCode, ToString
{

    protected Integer modelObjectId;
    protected int modelObjectVersion;
    protected String country;
    protected String username;
    protected String email;
    protected String userId;
    protected String userpassword;
    protected Integer numberOfVisits;
    @XmlElement(nillable = true)
    protected List<String> address;
    @XmlSchemaType(name = "string")
    protected UserType userType;
    @XmlSchemaType(name = "string")
    protected UserRole userRole;
    @XmlSchemaType(name = "string")
    protected UserLockStatus userLockStatus;
    @XmlSchemaType(name = "string")
    protected UserEmailStatus userEmailStatus;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(XmlDateTimeTypeAdapter.class)
    @XmlSchemaType(name = "dateTime")
    protected Date createdDate;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the modelObjectId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Basic
    @Column(name = "MODEL_OBJECT_ID", precision = 10, scale = 0)
    public Integer getModelObjectId() {
        return modelObjectId;
    }

    /**
     * Sets the value of the modelObjectId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setModelObjectId(Integer value) {
        this.modelObjectId = value;
    }

    /**
     * Gets the value of the modelObjectVersion property.
     * 
     */
    @Version
    @Column(name = "MODEL_OBJECT_VERSION")
    public int getModelObjectVersion() {
        return modelObjectVersion;
    }

    /**
     * Sets the value of the modelObjectVersion property.
     * 
     */
    public void setModelObjectVersion(int value) {
        this.modelObjectVersion = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "COUNTRY", length = 255)
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "USERNAME", length = 255)
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "EMAIL", length = 255)
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "USER_ID", length = 255)
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the userpassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "USERPASSWORD", length = 255)
    public String getUserpassword() {
        return userpassword;
    }

    /**
     * Sets the value of the userpassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserpassword(String value) {
        this.userpassword = value;
    }

    /**
     * Gets the value of the numberOfVisits property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Basic
    @Column(name = "NUMBER_OF_VISITS", precision = 10, scale = 0)
    public Integer getNumberOfVisits() {
        return numberOfVisits;
    }

    /**
     * Sets the value of the numberOfVisits property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberOfVisits(Integer value) {
        this.numberOfVisits = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the address property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    @ElementCollection
    @OrderColumn(name = "HJINDEX")
    @Column(name = "HJVALUE", length = 255)
    @CollectionTable(name = "USER_ACCOUNT_ADDRESS", joinColumns = {
        @JoinColumn(name = "HJID")
    })
    public List<String> getAddress() {
        if (address == null) {
            address = new ArrayList<String>();
        }
        return this.address;
    }

    /**
     * 
     * 
     */
    public void setAddress(List<String> address) {
        this.address = address;
    }

    /**
     * Gets the value of the userType property.
     * 
     * @return
     *     possible object is
     *     {@link UserType }
     *     
     */
    @Basic
    @Column(name = "USER_TYPE", length = 255)
    @Enumerated(EnumType.STRING)
    public UserType getUserType() {
        return userType;
    }

    /**
     * Sets the value of the userType property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserType }
     *     
     */
    public void setUserType(UserType value) {
        this.userType = value;
    }

    /**
     * Gets the value of the userRole property.
     * 
     * @return
     *     possible object is
     *     {@link UserRole }
     *     
     */
    @Basic
    @Column(name = "USER_ROLE", length = 255)
    @Enumerated(EnumType.STRING)
    public UserRole getUserRole() {
        return userRole;
    }

    /**
     * Sets the value of the userRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserRole }
     *     
     */
    public void setUserRole(UserRole value) {
        this.userRole = value;
    }

    /**
     * Gets the value of the userLockStatus property.
     * 
     * @return
     *     possible object is
     *     {@link UserLockStatus }
     *     
     */
    @Basic
    @Column(name = "USER_LOCK_STATUS", length = 255)
    @Enumerated(EnumType.STRING)
    public UserLockStatus getUserLockStatus() {
        return userLockStatus;
    }

    /**
     * Sets the value of the userLockStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserLockStatus }
     *     
     */
    public void setUserLockStatus(UserLockStatus value) {
        this.userLockStatus = value;
    }

    /**
     * Gets the value of the userEmailStatus property.
     * 
     * @return
     *     possible object is
     *     {@link UserEmailStatus }
     *     
     */
    @Basic
    @Column(name = "USER_EMAIL_STATUS", length = 255)
    @Enumerated(EnumType.STRING)
    public UserEmailStatus getUserEmailStatus() {
        return userEmailStatus;
    }

    /**
     * Sets the value of the userEmailStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserEmailStatus }
     *     
     */
    public void setUserEmailStatus(UserEmailStatus value) {
        this.userEmailStatus = value;
    }

    /**
     * Gets the value of the createdDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "CREATED_DATE")
    @Temporal(TemporalType.TIMESTAMP)
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the value of the createdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedDate(Date value) {
        this.createdDate = value;
    }

    public UserAccount withModelObjectId(Integer value) {
        setModelObjectId(value);
        return this;
    }

    public UserAccount withModelObjectVersion(int value) {
        setModelObjectVersion(value);
        return this;
    }

    public UserAccount withCountry(String value) {
        setCountry(value);
        return this;
    }

    public UserAccount withUsername(String value) {
        setUsername(value);
        return this;
    }

    public UserAccount withEmail(String value) {
        setEmail(value);
        return this;
    }

    public UserAccount withUserId(String value) {
        setUserId(value);
        return this;
    }

    public UserAccount withUserpassword(String value) {
        setUserpassword(value);
        return this;
    }

    public UserAccount withNumberOfVisits(Integer value) {
        setNumberOfVisits(value);
        return this;
    }

    public UserAccount withAddress(String... values) {
        if (values!= null) {
            for (String value: values) {
                getAddress().add(value);
            }
        }
        return this;
    }

    public UserAccount withAddress(Collection<String> values) {
        if (values!= null) {
            getAddress().addAll(values);
        }
        return this;
    }

    public UserAccount withAddress(List<String> address) {
        setAddress(address);
        return this;
    }

    public UserAccount withUserType(UserType value) {
        setUserType(value);
        return this;
    }

    public UserAccount withUserRole(UserRole value) {
        setUserRole(value);
        return this;
    }

    public UserAccount withUserLockStatus(UserLockStatus value) {
        setUserLockStatus(value);
        return this;
    }

    public UserAccount withUserEmailStatus(UserEmailStatus value) {
        setUserEmailStatus(value);
        return this;
    }

    public UserAccount withCreatedDate(Date value) {
        setCreatedDate(value);
        return this;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            Integer theModelObjectId;
            theModelObjectId = this.getModelObjectId();
            strategy.appendField(locator, this, "modelObjectId", buffer, theModelObjectId);
        }
        {
            int theModelObjectVersion;
            theModelObjectVersion = this.getModelObjectVersion();
            strategy.appendField(locator, this, "modelObjectVersion", buffer, theModelObjectVersion);
        }
        {
            String theCountry;
            theCountry = this.getCountry();
            strategy.appendField(locator, this, "country", buffer, theCountry);
        }
        {
            String theUsername;
            theUsername = this.getUsername();
            strategy.appendField(locator, this, "username", buffer, theUsername);
        }
        {
            String theEmail;
            theEmail = this.getEmail();
            strategy.appendField(locator, this, "email", buffer, theEmail);
        }
        {
            String theUserId;
            theUserId = this.getUserId();
            strategy.appendField(locator, this, "userId", buffer, theUserId);
        }
        {
            String theUserpassword;
            theUserpassword = this.getUserpassword();
            strategy.appendField(locator, this, "userpassword", buffer, theUserpassword);
        }
        {
            Integer theNumberOfVisits;
            theNumberOfVisits = this.getNumberOfVisits();
            strategy.appendField(locator, this, "numberOfVisits", buffer, theNumberOfVisits);
        }
        {
            List<String> theAddress;
            theAddress = (((this.address!= null)&&(!this.address.isEmpty()))?this.getAddress():null);
            strategy.appendField(locator, this, "address", buffer, theAddress);
        }
        {
            UserType theUserType;
            theUserType = this.getUserType();
            strategy.appendField(locator, this, "userType", buffer, theUserType);
        }
        {
            UserRole theUserRole;
            theUserRole = this.getUserRole();
            strategy.appendField(locator, this, "userRole", buffer, theUserRole);
        }
        {
            UserLockStatus theUserLockStatus;
            theUserLockStatus = this.getUserLockStatus();
            strategy.appendField(locator, this, "userLockStatus", buffer, theUserLockStatus);
        }
        {
            UserEmailStatus theUserEmailStatus;
            theUserEmailStatus = this.getUserEmailStatus();
            strategy.appendField(locator, this, "userEmailStatus", buffer, theUserEmailStatus);
        }
        {
            Date theCreatedDate;
            theCreatedDate = this.getCreatedDate();
            strategy.appendField(locator, this, "createdDate", buffer, theCreatedDate);
        }
        return buffer;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final UserAccount that = ((UserAccount) object);
        {
            Integer lhsModelObjectId;
            lhsModelObjectId = this.getModelObjectId();
            Integer rhsModelObjectId;
            rhsModelObjectId = that.getModelObjectId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "modelObjectId", lhsModelObjectId), LocatorUtils.property(thatLocator, "modelObjectId", rhsModelObjectId), lhsModelObjectId, rhsModelObjectId)) {
                return false;
            }
        }
        {
            int lhsModelObjectVersion;
            lhsModelObjectVersion = this.getModelObjectVersion();
            int rhsModelObjectVersion;
            rhsModelObjectVersion = that.getModelObjectVersion();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "modelObjectVersion", lhsModelObjectVersion), LocatorUtils.property(thatLocator, "modelObjectVersion", rhsModelObjectVersion), lhsModelObjectVersion, rhsModelObjectVersion)) {
                return false;
            }
        }
        {
            String lhsCountry;
            lhsCountry = this.getCountry();
            String rhsCountry;
            rhsCountry = that.getCountry();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "country", lhsCountry), LocatorUtils.property(thatLocator, "country", rhsCountry), lhsCountry, rhsCountry)) {
                return false;
            }
        }
        {
            String lhsUsername;
            lhsUsername = this.getUsername();
            String rhsUsername;
            rhsUsername = that.getUsername();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "username", lhsUsername), LocatorUtils.property(thatLocator, "username", rhsUsername), lhsUsername, rhsUsername)) {
                return false;
            }
        }
        {
            String lhsEmail;
            lhsEmail = this.getEmail();
            String rhsEmail;
            rhsEmail = that.getEmail();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "email", lhsEmail), LocatorUtils.property(thatLocator, "email", rhsEmail), lhsEmail, rhsEmail)) {
                return false;
            }
        }
        {
            String lhsUserId;
            lhsUserId = this.getUserId();
            String rhsUserId;
            rhsUserId = that.getUserId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "userId", lhsUserId), LocatorUtils.property(thatLocator, "userId", rhsUserId), lhsUserId, rhsUserId)) {
                return false;
            }
        }
        {
            String lhsUserpassword;
            lhsUserpassword = this.getUserpassword();
            String rhsUserpassword;
            rhsUserpassword = that.getUserpassword();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "userpassword", lhsUserpassword), LocatorUtils.property(thatLocator, "userpassword", rhsUserpassword), lhsUserpassword, rhsUserpassword)) {
                return false;
            }
        }
        {
            Integer lhsNumberOfVisits;
            lhsNumberOfVisits = this.getNumberOfVisits();
            Integer rhsNumberOfVisits;
            rhsNumberOfVisits = that.getNumberOfVisits();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "numberOfVisits", lhsNumberOfVisits), LocatorUtils.property(thatLocator, "numberOfVisits", rhsNumberOfVisits), lhsNumberOfVisits, rhsNumberOfVisits)) {
                return false;
            }
        }
        {
            List<String> lhsAddress;
            lhsAddress = (((this.address!= null)&&(!this.address.isEmpty()))?this.getAddress():null);
            List<String> rhsAddress;
            rhsAddress = (((that.address!= null)&&(!that.address.isEmpty()))?that.getAddress():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "address", lhsAddress), LocatorUtils.property(thatLocator, "address", rhsAddress), lhsAddress, rhsAddress)) {
                return false;
            }
        }
        {
            UserType lhsUserType;
            lhsUserType = this.getUserType();
            UserType rhsUserType;
            rhsUserType = that.getUserType();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "userType", lhsUserType), LocatorUtils.property(thatLocator, "userType", rhsUserType), lhsUserType, rhsUserType)) {
                return false;
            }
        }
        {
            UserRole lhsUserRole;
            lhsUserRole = this.getUserRole();
            UserRole rhsUserRole;
            rhsUserRole = that.getUserRole();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "userRole", lhsUserRole), LocatorUtils.property(thatLocator, "userRole", rhsUserRole), lhsUserRole, rhsUserRole)) {
                return false;
            }
        }
        {
            UserLockStatus lhsUserLockStatus;
            lhsUserLockStatus = this.getUserLockStatus();
            UserLockStatus rhsUserLockStatus;
            rhsUserLockStatus = that.getUserLockStatus();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "userLockStatus", lhsUserLockStatus), LocatorUtils.property(thatLocator, "userLockStatus", rhsUserLockStatus), lhsUserLockStatus, rhsUserLockStatus)) {
                return false;
            }
        }
        {
            UserEmailStatus lhsUserEmailStatus;
            lhsUserEmailStatus = this.getUserEmailStatus();
            UserEmailStatus rhsUserEmailStatus;
            rhsUserEmailStatus = that.getUserEmailStatus();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "userEmailStatus", lhsUserEmailStatus), LocatorUtils.property(thatLocator, "userEmailStatus", rhsUserEmailStatus), lhsUserEmailStatus, rhsUserEmailStatus)) {
                return false;
            }
        }
        {
            Date lhsCreatedDate;
            lhsCreatedDate = this.getCreatedDate();
            Date rhsCreatedDate;
            rhsCreatedDate = that.getCreatedDate();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "createdDate", lhsCreatedDate), LocatorUtils.property(thatLocator, "createdDate", rhsCreatedDate), lhsCreatedDate, rhsCreatedDate)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            Integer theModelObjectId;
            theModelObjectId = this.getModelObjectId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "modelObjectId", theModelObjectId), currentHashCode, theModelObjectId);
        }
        {
            int theModelObjectVersion;
            theModelObjectVersion = this.getModelObjectVersion();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "modelObjectVersion", theModelObjectVersion), currentHashCode, theModelObjectVersion);
        }
        {
            String theCountry;
            theCountry = this.getCountry();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "country", theCountry), currentHashCode, theCountry);
        }
        {
            String theUsername;
            theUsername = this.getUsername();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "username", theUsername), currentHashCode, theUsername);
        }
        {
            String theEmail;
            theEmail = this.getEmail();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "email", theEmail), currentHashCode, theEmail);
        }
        {
            String theUserId;
            theUserId = this.getUserId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "userId", theUserId), currentHashCode, theUserId);
        }
        {
            String theUserpassword;
            theUserpassword = this.getUserpassword();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "userpassword", theUserpassword), currentHashCode, theUserpassword);
        }
        {
            Integer theNumberOfVisits;
            theNumberOfVisits = this.getNumberOfVisits();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "numberOfVisits", theNumberOfVisits), currentHashCode, theNumberOfVisits);
        }
        {
            List<String> theAddress;
            theAddress = (((this.address!= null)&&(!this.address.isEmpty()))?this.getAddress():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "address", theAddress), currentHashCode, theAddress);
        }
        {
            UserType theUserType;
            theUserType = this.getUserType();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "userType", theUserType), currentHashCode, theUserType);
        }
        {
            UserRole theUserRole;
            theUserRole = this.getUserRole();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "userRole", theUserRole), currentHashCode, theUserRole);
        }
        {
            UserLockStatus theUserLockStatus;
            theUserLockStatus = this.getUserLockStatus();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "userLockStatus", theUserLockStatus), currentHashCode, theUserLockStatus);
        }
        {
            UserEmailStatus theUserEmailStatus;
            theUserEmailStatus = this.getUserEmailStatus();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "userEmailStatus", theUserEmailStatus), currentHashCode, theUserEmailStatus);
        }
        {
            Date theCreatedDate;
            theCreatedDate = this.getCreatedDate();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "createdDate", theCreatedDate), currentHashCode, theCreatedDate);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
