@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>UpdateSearchIndexJob\n<size:10>com.hack23.cia.service.impl.task" as com.hack23.cia.service.impl.task.UpdateSearchIndexJob [[UpdateSearchIndexJob.html]] {
        #executeInternal(JobExecutionContext): void
    }

    abstract class "<size:14>AbstractJob\n<size:10>com.hack23.cia.service.impl.task" as com.hack23.cia.service.impl.task.AbstractJob [[AbstractJob.html]]

    com.hack23.cia.service.impl.task.AbstractJob <|-- com.hack23.cia.service.impl.task.UpdateSearchIndexJob

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
