@startuml
    set namespaceSeparator none
    hide circle
    hide empty fields
    hide empty methods

    com.hack23.cia.web.impl.ui.application --> com.vaadin.server
    com.hack23.cia.web.impl.ui.application --> org.slf4j
    com.hack23.cia.web.impl.ui.application --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application --> com.vaadin.spring.server
    com.hack23.cia.web.impl.ui.application --> com.hack23.cia.service.api
    com.hack23.cia.web.impl.ui.application --> com.hack23.cia.web.impl.ui.application.views.common
    com.hack23.cia.web.impl.ui.application --> com.vaadin.spring.navigator
    com.hack23.cia.web.impl.ui.application --> com.vaadin.spring.internal
    com.hack23.cia.web.impl.ui.application --> org.eclipse.jetty.servlet
    com.hack23.cia.web.impl.ui.application --> com.hack23.cia.testfoundation
    com.hack23.cia.web.impl.ui.application.action --> com.hack23.cia.model.internal.application.system.impl
    com.hack23.cia.web.impl.ui.application.action --> com.hack23.cia.service.api
    com.hack23.cia.web.impl.ui.application.util --> com.vaadin.server
    com.hack23.cia.web.impl.ui.application.util --> nl.basjes.parse.useragent
    com.hack23.cia.web.impl.ui.application.util --> com.hack23.cia.testfoundation
    com.hack23.cia.web.impl.ui.application.views.admin.common --> com.hack23.cia.web.impl.ui.application.views.common
    com.hack23.cia.web.impl.ui.application.views.admin.datasummary --> com.hack23.cia.web.impl.ui.application.views.admin.common
    com.hack23.cia.web.impl.ui.application.views.admin.datasummary --> org.springframework.context
    com.hack23.cia.web.impl.ui.application.views.admin.datasummary.pagemode --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.admin.datasummary.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.pagemode
    com.hack23.cia.web.impl.ui.application.views.admin.agentoperations --> com.hack23.cia.web.impl.ui.application.views.admin.common
    com.hack23.cia.web.impl.ui.application.views.admin.agentoperations --> org.springframework.context
    com.hack23.cia.web.impl.ui.application.views.admin.agentoperations.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.pagemode
    com.hack23.cia.web.impl.ui.application.views.admin.agentoperations.pagemode --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.admin.system --> com.hack23.cia.web.impl.ui.application.views.admin.common
    com.hack23.cia.web.impl.ui.application.views.admin.system --> org.springframework.context
    com.hack23.cia.web.impl.ui.application.views.admin.system.pagemode --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.admin.system.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.pagemode
    com.hack23.cia.web.impl.ui.application.views.admin.system.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.paging
    com.hack23.cia.web.impl.ui.application.views.admin.system.pagemode --> com.hack23.cia.web.impl.ui.application.views.pageclicklistener
    com.hack23.cia.web.impl.ui.application.views.admin.system.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.converters
    com.hack23.cia.web.impl.ui.application.views.common.paging --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.common.paging --> com.hack23.cia.web.impl.ui.application.views.common.pagelinks.api
    com.hack23.cia.web.impl.ui.application.views.common --> org.springframework.context
    com.hack23.cia.web.impl.ui.application.views.common --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.common --> com.vaadin.navigator
    com.hack23.cia.web.impl.ui.application.views.common --> org.slf4j
    com.hack23.cia.web.impl.ui.application.views.common --> com.hack23.cia.web.impl.ui.application.views.common.menufactory.api
    com.hack23.cia.web.impl.ui.application.views.common --> com.hack23.cia.web.impl.ui.application.action
    com.hack23.cia.web.impl.ui.application.views.common --> com.hack23.cia.web.impl.ui.application.views.common.pagelinks.api
    com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl --> com.hack23.cia.web.impl.ui.application.views.common.menufactory.api
    com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl --> com.hack23.cia.web.impl.ui.application.views.common.pagelinks.api
    com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl --> com.hack23.cia.service.api
    com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl --> com.jarektoro.responsivelayout
    com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl --> com.vaadin.server
    com.hack23.cia.web.impl.ui.application.views.common.menufactory.api --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.common.converters --> com.vaadin.data
    com.hack23.cia.web.impl.ui.application.views.common.converters --> org.slf4j
    com.hack23.cia.web.impl.ui.application.views.common.converters --> org.apache.commons.beanutils
    com.hack23.cia.web.impl.ui.application.views.common.converters --> com.hack23.cia.testfoundation
    com.hack23.cia.web.impl.ui.application.views.common.gridfactory.impl --> com.hack23.cia.web.impl.ui.application.views.common.gridfactory.api
    com.hack23.cia.web.impl.ui.application.views.common.gridfactory.impl --> com.vaadin.data
    com.hack23.cia.web.impl.ui.application.views.common.gridfactory.impl --> org.slf4j
    com.hack23.cia.web.impl.ui.application.views.common.gridfactory.impl --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.common.gridfactory.impl --> com.vaadin.event.selection
    com.hack23.cia.web.impl.ui.application.views.common.gridfactory.impl --> com.hack23.cia.web.impl.ui.application.views.common.converters
    com.hack23.cia.web.impl.ui.application.views.common.gridfactory.impl --> com.hack23.cia.web.impl.ui.application.views.pageclicklistener
    com.hack23.cia.web.impl.ui.application.views.common.gridfactory.api --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.common.gridfactory.api --> com.hack23.cia.web.impl.ui.application.views.pageclicklistener
    com.hack23.cia.web.impl.ui.application.views.common.gridfactory.api --> com.hack23.cia.web.impl.ui.application.views.common.converters
    com.hack23.cia.web.impl.ui.application.views.common.labelfactory --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.common.pagelinks.impl --> com.vaadin.server
    com.hack23.cia.web.impl.ui.application.views.common.pagelinks.impl --> org.slf4j
    com.hack23.cia.web.impl.ui.application.views.common.pagelinks.impl --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.common.pagelinks.impl --> com.hack23.cia.web.impl.ui.application.views.common.pagelinks.api
    com.hack23.cia.web.impl.ui.application.views.common.pagelinks.impl --> com.hack23.cia.model.internal.application.data.committee.impl
    com.hack23.cia.web.impl.ui.application.views.common.pagelinks.impl --> com.hack23.cia.model.internal.application.data.ministry.impl
    com.hack23.cia.web.impl.ui.application.views.common.pagelinks.impl --> com.hack23.cia.model.internal.application.data.party.impl
    com.hack23.cia.web.impl.ui.application.views.common.pagelinks.impl --> com.hack23.cia.model.external.riksdagen.person.impl
    com.hack23.cia.web.impl.ui.application.views.common.pagelinks.impl --> com.hack23.cia.testfoundation
    com.hack23.cia.web.impl.ui.application.views.common.pagelinks.api --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.common.pagelinks.api --> com.hack23.cia.model.internal.application.data.committee.impl
    com.hack23.cia.web.impl.ui.application.views.common.pagelinks.api --> com.hack23.cia.model.internal.application.data.ministry.impl
    com.hack23.cia.web.impl.ui.application.views.common.pagelinks.api --> com.hack23.cia.model.internal.application.data.party.impl
    com.hack23.cia.web.impl.ui.application.views.common.pagelinks.api --> com.hack23.cia.model.external.riksdagen.person.impl
    com.hack23.cia.web.impl.ui.application.views.common.pagelinks.api --> com.hack23.cia.web.impl.ui.application.views.common.viewnames
    com.hack23.cia.web.impl.ui.application.views.common.formfactory.impl --> com.vaadin.data
    com.hack23.cia.web.impl.ui.application.views.common.formfactory.impl --> com.hack23.cia.web.impl.ui.application.views.common.formfactory.api
    com.hack23.cia.web.impl.ui.application.views.common.formfactory.impl --> org.slf4j
    com.hack23.cia.web.impl.ui.application.views.common.formfactory.impl --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.common.formfactory.impl --> com.hack23.cia.testfoundation
    com.hack23.cia.web.impl.ui.application.views.common.formfactory.api --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.common.rows --> com.jarektoro.responsivelayout
    com.hack23.cia.web.impl.ui.application.views.common.rows --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.impl --> com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.api
    com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.impl --> com.hack23.cia.service.api
    com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.impl --> org.dussan.vaadin.dcharts.data
    com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.impl --> com.hack23.cia.model.external.riksdagen.dokumentstatus.impl
    com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.api --> org.dussan.vaadin.dcharts.data
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl --> com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl --> com.hack23.cia.service.api
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl --> com.hack23.cia.model.internal.application.data.committee.impl
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl --> org.dussan.vaadin.dcharts.options
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl --> org.dussan.vaadin.dcharts.data
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl --> org.slf4j
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl --> com.hack23.cia.model.internal.application.data.impl
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl --> org.dussan.vaadin.dcharts
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl --> com.hack23.cia.model.internal.application.data.ministry.impl
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl --> com.hack23.cia.service.external.esv.api
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl --> com.hack23.cia.model.internal.application.data.document.impl
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl --> com.hack23.cia.model.internal.application.data.party.impl
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl --> com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.api
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl --> com.hack23.cia.web.widgets.charts
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl --> com.hack23.cia.model.external.riksdagen.person.impl
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl --> org.tltv.gantt
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl --> org.tltv.gantt.client.shared
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api --> org.dussan.vaadin.dcharts.options
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api --> com.hack23.cia.model.internal.application.data.impl
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api --> com.hack23.cia.web.widgets.charts
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api --> com.hack23.cia.model.internal.application.data.committee.impl
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api --> org.dussan.vaadin.dcharts.data
    com.hack23.cia.web.impl.ui.application.views.common.pagemode --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.common.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api
    com.hack23.cia.web.impl.ui.application.views.common.pagemode --> com.hack23.cia.service.api
    com.hack23.cia.web.impl.ui.application.views.common.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.formfactory.api
    com.hack23.cia.web.impl.ui.application.views.common.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.gridfactory.api
    com.hack23.cia.web.impl.ui.application.views.common.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.menufactory.api
    com.hack23.cia.web.impl.ui.application.views.common.pagemode --> com.hack23.cia.web.impl.ui.application.action
    com.hack23.cia.web.impl.ui.application.views.common.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.pagelinks.api
    com.hack23.cia.web.impl.ui.application.views.user.govermentbody --> com.hack23.cia.web.impl.ui.application.views.user.common
    com.hack23.cia.web.impl.ui.application.views.user.govermentbody --> org.springframework.context
    com.hack23.cia.web.impl.ui.application.views.user.govermentbody.pagemode --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.user.govermentbody.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api
    com.hack23.cia.web.impl.ui.application.views.user.govermentbody.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.pagemode
    com.hack23.cia.web.impl.ui.application.views.user.govermentbody.pagemode --> com.hack23.cia.service.external.esv.api
    com.hack23.cia.web.impl.ui.application.views.user.govermentbody.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.menufactory.api
    com.hack23.cia.web.impl.ui.application.views.user.govermentbody.pagemode --> com.hack23.cia.web.impl.ui.application.views.pageclicklistener
    com.hack23.cia.web.impl.ui.application.views.user.common --> com.hack23.cia.web.impl.ui.application.views.common
    com.hack23.cia.web.impl.ui.application.views.user.goverment --> com.hack23.cia.web.impl.ui.application.views.user.common
    com.hack23.cia.web.impl.ui.application.views.user.goverment --> org.springframework.context
    com.hack23.cia.web.impl.ui.application.views.user.goverment.pagemode --> com.hack23.cia.web.impl.ui.application.views.pageclicklistener
    com.hack23.cia.web.impl.ui.application.views.user.goverment.pagemode --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.user.goverment.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api
    com.hack23.cia.web.impl.ui.application.views.user.goverment.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.api
    com.hack23.cia.web.impl.ui.application.views.user.goverment.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.pagemode
    com.hack23.cia.web.impl.ui.application.views.user.goverment.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.menufactory.api
    com.hack23.cia.web.impl.ui.application.views.user.goverment.pagemode --> com.hack23.cia.model.internal.application.data.ministry.impl
    com.hack23.cia.web.impl.ui.application.views.user.committee --> com.hack23.cia.web.impl.ui.application.views.user.common
    com.hack23.cia.web.impl.ui.application.views.user.committee --> org.springframework.context
    com.hack23.cia.web.impl.ui.application.views.user.committee.pagemode --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.user.committee.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api
    com.hack23.cia.web.impl.ui.application.views.user.committee.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.api
    com.hack23.cia.web.impl.ui.application.views.user.committee.pagemode --> com.hack23.cia.web.impl.ui.application.views.pageclicklistener
    com.hack23.cia.web.impl.ui.application.views.user.committee.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.pagemode
    com.hack23.cia.web.impl.ui.application.views.user.committee.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.menufactory.api
    com.hack23.cia.web.impl.ui.application.views.user.committee.pagemode --> com.hack23.cia.model.internal.application.data.committee.impl
    com.hack23.cia.web.impl.ui.application.views.user.parliament --> com.hack23.cia.web.impl.ui.application.views.user.common
    com.hack23.cia.web.impl.ui.application.views.user.parliament --> org.springframework.context
    com.hack23.cia.web.impl.ui.application.views.user.parliament.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.pagemode
    com.hack23.cia.web.impl.ui.application.views.user.parliament.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.menufactory.api
    com.hack23.cia.web.impl.ui.application.views.user.parliament.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api
    com.hack23.cia.web.impl.ui.application.views.user.parliament.pagemode --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.user.parliament.pagemode --> com.hack23.cia.web.impl.ui.application.views.pageclicklistener
    com.hack23.cia.web.impl.ui.application.views.user.party --> com.hack23.cia.web.impl.ui.application.views.user.common
    com.hack23.cia.web.impl.ui.application.views.user.party --> org.springframework.context
    com.hack23.cia.web.impl.ui.application.views.user.party.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.pagemode
    com.hack23.cia.web.impl.ui.application.views.user.party.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.menufactory.api
    com.hack23.cia.web.impl.ui.application.views.user.party.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api
    com.hack23.cia.web.impl.ui.application.views.user.party.pagemode --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.user.party.pagemode --> com.hack23.cia.web.impl.ui.application.views.pageclicklistener
    com.hack23.cia.web.impl.ui.application.views.user.party.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.api
    com.hack23.cia.web.impl.ui.application.views.user.party.pagemode --> com.hack23.cia.model.internal.application.data.party.impl
    com.hack23.cia.web.impl.ui.application.views.user.country --> com.hack23.cia.web.impl.ui.application.views.user.common
    com.hack23.cia.web.impl.ui.application.views.user.country --> org.springframework.context
    com.hack23.cia.web.impl.ui.application.views.user.country.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api
    com.hack23.cia.web.impl.ui.application.views.user.country.pagemode --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.user.country.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.pagemode
    com.hack23.cia.web.impl.ui.application.views.user.country.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.menufactory.api
    com.hack23.cia.web.impl.ui.application.views.user.document --> com.hack23.cia.web.impl.ui.application.views.user.common
    com.hack23.cia.web.impl.ui.application.views.user.document --> org.springframework.context
    com.hack23.cia.web.impl.ui.application.views.user.document.pagemode --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.user.document.pagemode --> com.hack23.cia.web.impl.ui.application.views.pageclicklistener
    com.hack23.cia.web.impl.ui.application.views.user.document.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.paging
    com.hack23.cia.web.impl.ui.application.views.user.document.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.pagemode
    com.hack23.cia.web.impl.ui.application.views.user.document.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.menufactory.api
    com.hack23.cia.web.impl.ui.application.views.user.document.pagemode --> com.hack23.cia.model.external.riksdagen.dokumentlista.impl
    com.hack23.cia.web.impl.ui.application.views.user.ballot --> com.hack23.cia.web.impl.ui.application.views.user.common
    com.hack23.cia.web.impl.ui.application.views.user.ballot --> org.springframework.context
    com.hack23.cia.web.impl.ui.application.views.user.ballot.pagemode --> com.hack23.cia.web.impl.ui.application.views.pageclicklistener
    com.hack23.cia.web.impl.ui.application.views.user.ballot.pagemode --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.user.ballot.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.pagemode
    com.hack23.cia.web.impl.ui.application.views.user.ballot.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.menufactory.api
    com.hack23.cia.web.impl.ui.application.views.user.ballot.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api
    com.hack23.cia.web.impl.ui.application.views.user.home --> com.hack23.cia.web.impl.ui.application.views.user.common
    com.hack23.cia.web.impl.ui.application.views.user.home --> org.springframework.context
    com.hack23.cia.web.impl.ui.application.views.user.home.pagemode --> com.hack23.cia.web.impl.ui.application.views.pageclicklistener
    com.hack23.cia.web.impl.ui.application.views.user.home.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.menufactory.api
    com.hack23.cia.web.impl.ui.application.views.user.home.pagemode --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.user.home.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.converters
    com.hack23.cia.web.impl.ui.application.views.user.home.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.pagemode
    com.hack23.cia.web.impl.ui.application.views.user.politician --> com.hack23.cia.web.impl.ui.application.views.user.common
    com.hack23.cia.web.impl.ui.application.views.user.politician --> org.springframework.context
    com.hack23.cia.web.impl.ui.application.views.user.politician.pagemode --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.user.politician.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.pagemode
    com.hack23.cia.web.impl.ui.application.views.user.politician.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.menufactory.api
    com.hack23.cia.web.impl.ui.application.views.user.politician.pagemode --> com.hack23.cia.model.internal.application.data.politician.impl
    com.hack23.cia.web.impl.ui.application.views.user.politician.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api
    com.hack23.cia.web.impl.ui.application.views.user.politician.pagemode --> com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.api
    com.hack23.cia.web.impl.ui.application.views.user.politician.pagemode --> com.hack23.cia.model.external.riksdagen.person.impl
    com.hack23.cia.web.impl.ui.application.views.user.politician.pagemode --> com.hack23.cia.web.impl.ui.application.views.pageclicklistener
    com.hack23.cia.web.impl.ui.application.views.pageclicklistener --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.pageclicklistener --> com.hack23.cia.service.api.action.admin
    com.hack23.cia.web.impl.ui.application.views.pageclicklistener --> com.hack23.cia.service.api.action.kpi
    com.hack23.cia.web.impl.ui.application.views.pageclicklistener --> com.vaadin.ui.renderers
    com.hack23.cia.web.impl.ui.application.views.pageclicklistener --> com.vaadin.event.selection
    com.hack23.cia.web.impl.ui.application.views.pageclicklistener --> org.slf4j
    com.hack23.cia.web.impl.ui.application.views.pageclicklistener --> com.hack23.cia.service.api.action.user
    com.hack23.cia.web.impl.ui.application.views.pageclicklistener --> com.vaadin.data
    com.hack23.cia.web.impl.ui.application.views.pageclicklistener --> com.hack23.cia.service.api.action.application
    com.hack23.cia.web.impl.ui.application.views.pageclicklistener --> com.hack23.cia.web.impl.ui.application.views.pageclicklisteners.handlers.api
    com.hack23.cia.web.impl.ui.application.views.pageclicklistener --> com.hack23.cia.model.internal.application.data.impl
    com.hack23.cia.web.impl.ui.application.views.pageclicklistener --> com.hack23.cia.service.api
    com.hack23.cia.web.impl.ui.application.views.pageclicklistener --> com.hack23.cia.testfoundation
    com.hack23.cia.web.impl.ui.application.views.pageclicklisteners.handlers.impl --> com.hack23.cia.web.impl.ui.application.views.pageclicklisteners.handlers.api
    com.hack23.cia.web.impl.ui.application.views.pageclicklisteners.handlers.impl --> com.hack23.cia.web.impl.ui.application.views.pageclicklistener
    com.hack23.cia.web.impl.ui.application.views.pageclicklisteners.handlers.impl --> com.vaadin.ui
    com.hack23.cia.web.impl.ui.application.views.pageclicklisteners.handlers.impl --> com.hack23.cia.web.impl.ui.application.views.common.gridfactory.api
    com.hack23.cia.web.impl.ui.application.views.pageclicklisteners.handlers.impl --> com.hack23.cia.service.api.action.user
    com.hack23.cia.web.impl.ui.application.views.pageclicklisteners.handlers.api --> com.hack23.cia.service.api.action.user
    com.hack23.cia.web.impl.ui.application.web.listener --> org.springframework.context
    com.hack23.cia.web.impl.ui.application.web.listener --> org.slf4j
    com.hack23.cia.web.impl.ui.application.web.listener --> com.hack23.cia.service.api
    com.hack23.cia.web.impl.ui.application.web.listener --> org.springframework.security.access.event
    com.hack23.cia.web.impl.ui.application.web.listener --> org.springframework.security.web.session

    ' Package links
    class "com.hack23.cia.web.impl.ui.application" [[com/hack23/cia/web/impl/ui/application/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.common" [[com/hack23/cia/web/impl/ui/application/views/common/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.action" [[com/hack23/cia/web/impl/ui/application/action/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.util" [[com/hack23/cia/web/impl/ui/application/util/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.admin.common" [[com/hack23/cia/web/impl/ui/application/views/admin/common/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.admin.datasummary" [[com/hack23/cia/web/impl/ui/application/views/admin/datasummary/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.admin.datasummary.pagemode" [[com/hack23/cia/web/impl/ui/application/views/admin/datasummary/pagemode/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.common.pagemode" [[com/hack23/cia/web/impl/ui/application/views/common/pagemode/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.admin.agentoperations" [[com/hack23/cia/web/impl/ui/application/views/admin/agentoperations/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.admin.agentoperations.pagemode" [[com/hack23/cia/web/impl/ui/application/views/admin/agentoperations/pagemode/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.admin.system" [[com/hack23/cia/web/impl/ui/application/views/admin/system/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.admin.system.pagemode" [[com/hack23/cia/web/impl/ui/application/views/admin/system/pagemode/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.common.paging" [[com/hack23/cia/web/impl/ui/application/views/common/paging/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.pageclicklistener" [[com/hack23/cia/web/impl/ui/application/views/pageclicklistener/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.common.converters" [[com/hack23/cia/web/impl/ui/application/views/common/converters/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.common.pagelinks.api" [[com/hack23/cia/web/impl/ui/application/views/common/pagelinks/api/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.common.menufactory.api" [[com/hack23/cia/web/impl/ui/application/views/common/menufactory/api/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl" [[com/hack23/cia/web/impl/ui/application/views/common/menufactory/impl/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.common.gridfactory.impl" [[com/hack23/cia/web/impl/ui/application/views/common/gridfactory/impl/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.common.gridfactory.api" [[com/hack23/cia/web/impl/ui/application/views/common/gridfactory/api/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.common.labelfactory" [[com/hack23/cia/web/impl/ui/application/views/common/labelfactory/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.common.pagelinks.impl" [[com/hack23/cia/web/impl/ui/application/views/common/pagelinks/impl/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.common.viewnames" [[com/hack23/cia/web/impl/ui/application/views/common/viewnames/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.common.formfactory.impl" [[com/hack23/cia/web/impl/ui/application/views/common/formfactory/impl/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.common.formfactory.api" [[com/hack23/cia/web/impl/ui/application/views/common/formfactory/api/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.common.rows" [[com/hack23/cia/web/impl/ui/application/views/common/rows/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.impl" [[com/hack23/cia/web/impl/ui/application/views/common/dataseriesfactory/impl/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.api" [[com/hack23/cia/web/impl/ui/application/views/common/dataseriesfactory/api/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl" [[com/hack23/cia/web/impl/ui/application/views/common/chartfactory/impl/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api" [[com/hack23/cia/web/impl/ui/application/views/common/chartfactory/api/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.user.govermentbody" [[com/hack23/cia/web/impl/ui/application/views/user/govermentbody/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.user.common" [[com/hack23/cia/web/impl/ui/application/views/user/common/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.user.govermentbody.pagemode" [[com/hack23/cia/web/impl/ui/application/views/user/govermentbody/pagemode/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.user.goverment" [[com/hack23/cia/web/impl/ui/application/views/user/goverment/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.user.goverment.pagemode" [[com/hack23/cia/web/impl/ui/application/views/user/goverment/pagemode/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.user.committee" [[com/hack23/cia/web/impl/ui/application/views/user/committee/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.user.committee.pagemode" [[com/hack23/cia/web/impl/ui/application/views/user/committee/pagemode/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.user.parliament" [[com/hack23/cia/web/impl/ui/application/views/user/parliament/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.user.parliament.pagemode" [[com/hack23/cia/web/impl/ui/application/views/user/parliament/pagemode/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.user.party" [[com/hack23/cia/web/impl/ui/application/views/user/party/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.user.party.pagemode" [[com/hack23/cia/web/impl/ui/application/views/user/party/pagemode/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.user.country" [[com/hack23/cia/web/impl/ui/application/views/user/country/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.user.country.pagemode" [[com/hack23/cia/web/impl/ui/application/views/user/country/pagemode/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.user.document" [[com/hack23/cia/web/impl/ui/application/views/user/document/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.user.document.pagemode" [[com/hack23/cia/web/impl/ui/application/views/user/document/pagemode/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.user.ballot" [[com/hack23/cia/web/impl/ui/application/views/user/ballot/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.user.ballot.pagemode" [[com/hack23/cia/web/impl/ui/application/views/user/ballot/pagemode/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.user.home" [[com/hack23/cia/web/impl/ui/application/views/user/home/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.user.home.pagemode" [[com/hack23/cia/web/impl/ui/application/views/user/home/pagemode/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.user.politician" [[com/hack23/cia/web/impl/ui/application/views/user/politician/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.user.politician.pagemode" [[com/hack23/cia/web/impl/ui/application/views/user/politician/pagemode/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.pageclicklisteners.handlers.api" [[com/hack23/cia/web/impl/ui/application/views/pageclicklisteners/handlers/api/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.views.pageclicklisteners.handlers.impl" [[com/hack23/cia/web/impl/ui/application/views/pageclicklisteners/handlers/impl/package-summary.html]] {
    }
    class "com.hack23.cia.web.impl.ui.application.web.listener" [[com/hack23/cia/web/impl/ui/application/web/listener/package-summary.html]] {
    }

    center footer UMLDoclet 2.0.4, PlantUML 1.2019.06
@enduml
