@startuml
    namespace com.hack23.cia.web.impl.ui.application.util {

        class UserContextUtil [[UserContextUtil.html]] {
            {static} +allowRoleInSecurityContext(String): boolean
            {static} +getRequestUrl(Page): String
            {static} +getUserIdFromSecurityContext(): String
        }

        class WebBrowserUtil [[WebBrowserUtil.html]] {
            {static} +X_FORWARDED_FOR: String
            {static} +getIpInformation(WebBrowser): String
            {static} +getOperatingSystem(WebBrowser): String
        }

    }

    center footer UMLDoclet 2.0.4, PlantUML 1.2019.06
@enduml
