create table AbstractActionEvent (actioneventclasstype varchar(31) not null, id bigint not null auto_increment, createdDate datetime, executionTime bigint, version bigint, agencyId bigint, operation varchar(255), languageContentId bigint, languageId bigint, portalId bigint, errorMessage varchar(255), stackTrace longtext, citizenOperation varchar(255), party varchar(255), searchString varchar(255), ballotId bigint, committeeReportId bigint, parliamentMemberId bigint, primary key (id)) type=InnoDB;
create table AbstractBallotMetaData (ballotMetaDataType varchar(31) not null, id bigint not null auto_increment, absentVotes bigint not null, neutralVotes bigint not null, noVotes bigint not null, totalVotes bigint not null, version bigint, yesVotes bigint not null, opponentVotes bigint, winningPosition varchar(255), winningVotes bigint, createdDate date, resourceType varchar(255), firstVoteDate date, lastVoteDate date, opponent bigint, rebel bigint, politicalParty_id bigint, primary key (id)) type=InnoDB;
create table AbstractResource (abstractResourceType varchar(31) not null, id bigint not null auto_increment, resourceType varchar(255), version bigint, activeByDefault bit, name varchar(255), usageOrder integer, matchesUrl varchar(255), titleDescription varchar(255), fileName varchar(255), imageContent longblob, mimetype varchar(255), content longtext, contentPropertyName varchar(255), description varchar(255), languageContentType varchar(255), shortCode varchar(255), agentName varchar(255), agentOperationType varchar(255), agentOperativeCode varchar(255), operationStatus varchar(255), agency_id bigint, language_id bigint, primary key (id)) type=InnoDB;
create table Agency (id bigint not null auto_increment, name varchar(255), version bigint, primary key (id)) type=InnoDB;
create table AgencyLanguageContent (Agency_id bigint not null, languageContent_id bigint not null, primary key (Agency_id, languageContent_id), unique (languageContent_id)) type=InnoDB;
create table AgencyLanguages (Agency_id bigint not null, languages_id bigint not null, primary key (Agency_id, languages_id), unique (languages_id)) type=InnoDB;
create table Ballot (id bigint not null auto_increment, datum date, description varchar(255), importStatus varchar(255), importedDate date, overviewHref varchar(255), resourceType varchar(255), version bigint, voteResultsHref varchar(255), ballotResult_id bigint, commiteeReport_id bigint, primary key (id), unique (voteResultsHref)) type=InnoDB;
create table BallotPartyVoteResult (Ballot_id bigint not null, partyBallotResult_id bigint not null, unique (partyBallotResult_id)) type=InnoDB;
create table Committee (id bigint not null auto_increment, href varchar(255), importStatus varchar(255), importedDate date, name varchar(255), resourceType varchar(255), shortCode varchar(255), version bigint, primary key (id), unique (name, href)) type=InnoDB;
create table CommitteeCommitteeReports (Committee_id bigint not null, committeeReports_id bigint not null, primary key (Committee_id, committeeReports_id), unique (committeeReports_id)) type=InnoDB;
create table CommitteeParliamentMembers (Committee_id bigint not null, parliamentMembers_id bigint not null, primary key (Committee_id, parliamentMembers_id), unique (parliamentMembers_id)) type=InnoDB;
create table CommitteeReport (id bigint not null auto_increment, decisionDate date, href varchar(255), importStatus varchar(255), importedDate date, name varchar(255), resourceType varchar(255), shortCode varchar(255), version bigint, parliamentYear_id bigint, primary key (id), unique (name, href)) type=InnoDB;
create table Election (id bigint not null auto_increment, electionDate datetime, importStatus varchar(255), importedDate date, name varchar(255), resourceType varchar(255), version bigint, primary key (id)) type=InnoDB;
create table GameBoard (id bigint not null auto_increment, name varchar(255), version bigint, primary key (id)) type=InnoDB;
create table Parliament (id bigint not null auto_increment, description varchar(255), name varchar(255), resourceType varchar(255), shortCode varchar(255), url varchar(255), version bigint, primary key (id)) type=InnoDB;
create table ParliamentCommittees (Parliament_id bigint not null, committees_id bigint not null, primary key (Parliament_id, committees_id), unique (committees_id)) type=InnoDB;
create table ParliamentDocumentType (id bigint not null auto_increment, dataCompleted bit not null, dataUpdating bit not null, importData bit not null, importStatus varchar(255), importedDate date, name varchar(255), resourceType varchar(255), shortCode varchar(255), version bigint, primary key (id)) type=InnoDB;
create table ParliamentElections (Parliament_id bigint not null, elections_id bigint not null, primary key (Parliament_id, elections_id), unique (elections_id)) type=InnoDB;
create table ParliamentMember (id bigint not null auto_increment, electoralRegion varchar(255), endDate date, englishWikiHref varchar(255), fuzzyKey varchar(255), href varchar(255), importStatus varchar(255), importedDate date, name varchar(255), parliamentSeatPosition varchar(255), party varchar(255), resourceType varchar(255), startDate date, version bigint, wikiHref varchar(255), parliamentMemberBallotRecordId bigint, politicalParty_id bigint, politician_id bigint, primary key (id), unique (fuzzyKey)) type=InnoDB;
create table ParliamentMemberVoteCompareResult (id bigint not null auto_increment, createdDate date, datum date, resourceType varchar(255), result float not null, version bigint, votesCompared integer not null, opponentParliamentMember_id bigint, parliamentMember_id bigint, primary key (id), unique (parliamentMember_id, opponentParliamentMember_id)) type=InnoDB;
create table ParliamentYear (id bigint not null auto_increment, currentYear bit not null, dataCompleted bit not null, dataUpdating bit not null, endDate date, importData bit not null, importStatus varchar(255), importedDate date, name varchar(255), resourceType varchar(255), shortCode varchar(255), startDate date, version bigint, primary key (id)) type=InnoDB;
create table ParliamentYears (Parliament_id bigint not null, parliamentYears_id bigint not null, primary key (Parliament_id, parliamentYears_id), unique (parliamentYears_id)) type=InnoDB;
create table Person (personDataType varchar(31) not null, id bigint not null auto_increment, name varchar(255), version bigint, bankId integer, bornYear integer, electoralRegion varchar(255), email varchar(255), gender varchar(255), homePage varchar(255), importStatus varchar(255), importedDate date, lastName varchar(255), parliamentPersonId integer, party varchar(255), personUrlXml varchar(255), phone varchar(255), place varchar(255), placeOfResidence varchar(255), proffession varchar(255), status varchar(255), usedFirstName varchar(255), primary key (id)) type=InnoDB;
create table Player (id bigint not null auto_increment, version bigint, shadowParliamentMember_id bigint, user_id bigint, primary key (id)) type=InnoDB;
create table PoliticalGame (id bigint not null auto_increment, name varchar(255), version bigint, primary key (id)) type=InnoDB;
create table PoliticalGameBoards (PoliticalGame_id bigint not null, gameBoards_id bigint not null, primary key (PoliticalGame_id, gameBoards_id), unique (gameBoards_id)) type=InnoDB;
create table PoliticalParty (id bigint not null auto_increment, importStatus varchar(255), importedDate date, name varchar(255), resourceType varchar(255), shortCode varchar(255), version bigint, election_id bigint, primary key (id)) type=InnoDB;
create table PortalLanguageContent (AbstractResource_id bigint not null, languageContent_id bigint not null, primary key (AbstractResource_id, languageContent_id), unique (languageContent_id)) type=InnoDB;
create table RegisterInformation (id bigint not null auto_increment, version bigint, primary key (id)) type=InnoDB;
create table User (usertype varchar(31) not null, id bigint not null auto_increment, createdDate datetime, password varchar(255), userRole varchar(255), username varchar(255), version bigint, email varchar(255), forceSecureEmailsOnly bit, publicPgpKey varchar(255), human_id bigint, primary key (id)) type=InnoDB;
create table UserSession (id bigint not null auto_increment, active bit not null, clientHost varchar(255), createdAt date, endedAt date, resourceType varchar(255), serverHost varchar(255), sessionId varchar(255), userAgent varchar(255), version bigint, language_id bigint, portal_id bigint, user_id bigint, primary key (id)) type=InnoDB;
create table UserSessionEvents (UserSession_id bigint not null, events_id bigint not null, unique (events_id)) type=InnoDB;
create table Vote (id bigint not null auto_increment, datum date, importStatus varchar(255), importedDate date, position varchar(255), resourceType varchar(255), version bigint, ballot_id bigint, parliamentMember_id bigint, primary key (id), unique (parliamentMember_id, ballot_id)) type=InnoDB;
create table VoteMetaData (id bigint not null auto_increment, createdDate date, outcome varchar(255), politicalPartyBehavior varchar(255), proffessionalBehavior varchar(255), resourceType varchar(255), version bigint, primary key (id)) type=InnoDB;
alter table AbstractBallotMetaData add index FKF3A7047588C7583A (politicalParty_id), add constraint FKF3A7047588C7583A foreign key (politicalParty_id) references PoliticalParty (id);
create index fileNameIndex on AbstractResource (fileName);
create index matchesUrlIndex on AbstractResource (matchesUrl);
create index shortCodeIndex on AbstractResource (shortCode);
create index nameIndex on AbstractResource (name);
create index agentOperativeCodeIndex on AbstractResource (agentOperativeCode);
create index contentPropertyNameIndex on AbstractResource (contentPropertyName);
create index agentNameIndex on AbstractResource (agentName);
alter table AbstractResource add index FKA4BB1A70EC052227 (agency_id), add constraint FKA4BB1A70EC052227 foreign key (agency_id) references Agency (id);
alter table AbstractResource add index FKA4BB1A7014985DA4 (language_id), add constraint FKA4BB1A7014985DA4 foreign key (language_id) references AbstractResource (id);
alter table AgencyLanguageContent add index FK821A071CEC052227 (Agency_id), add constraint FK821A071CEC052227 foreign key (Agency_id) references Agency (id);
alter table AgencyLanguageContent add index FK821A071CA6243D0 (languageContent_id), add constraint FK821A071CA6243D0 foreign key (languageContent_id) references AbstractResource (id);
alter table AgencyLanguages add index FKF6124976EC052227 (Agency_id), add constraint FKF6124976EC052227 foreign key (Agency_id) references Agency (id);
alter table AgencyLanguages add index FKF6124976DE0D3E01 (languages_id), add constraint FKF6124976DE0D3E01 foreign key (languages_id) references AbstractResource (id);
alter table Ballot add index FK76297C44B5A9997A (ballotResult_id), add constraint FK76297C44B5A9997A foreign key (ballotResult_id) references AbstractBallotMetaData (id);
alter table Ballot add index FK76297C44C50855A0 (commiteeReport_id), add constraint FK76297C44C50855A0 foreign key (commiteeReport_id) references CommitteeReport (id);
alter table BallotPartyVoteResult add index FK7E616A49CDE50E7A (Ballot_id), add constraint FK7E616A49CDE50E7A foreign key (Ballot_id) references Ballot (id);
alter table BallotPartyVoteResult add index FK7E616A494C49C55A (partyBallotResult_id), add constraint FK7E616A494C49C55A foreign key (partyBallotResult_id) references AbstractBallotMetaData (id);
create index shortCodeIndex on Committee (shortCode);
create index nameIndex on Committee (name);
alter table CommitteeCommitteeReports add index FK95D3FCFF56B1C1D7 (Committee_id), add constraint FK95D3FCFF56B1C1D7 foreign key (Committee_id) references Committee (id);
alter table CommitteeCommitteeReports add index FK95D3FCFFA5C9A2A9 (committeeReports_id), add constraint FK95D3FCFFA5C9A2A9 foreign key (committeeReports_id) references CommitteeReport (id);
alter table CommitteeParliamentMembers add index FK1C1E39DB8DF3763D (parliamentMembers_id), add constraint FK1C1E39DB8DF3763D foreign key (parliamentMembers_id) references ParliamentMember (id);
alter table CommitteeParliamentMembers add index FK1C1E39DB56B1C1D7 (Committee_id), add constraint FK1C1E39DB56B1C1D7 foreign key (Committee_id) references Committee (id);
create index shortCodeIndex on CommitteeReport (shortCode);
create index nameIndex on CommitteeReport (name);
alter table CommitteeReport add index FKA6789EF1CC5F8044 (parliamentYear_id), add constraint FKA6789EF1CC5F8044 foreign key (parliamentYear_id) references ParliamentYear (id);
alter table ParliamentCommittees add index FK3061F1B7D1F07E1E (committees_id), add constraint FK3061F1B7D1F07E1E foreign key (committees_id) references Committee (id);
alter table ParliamentCommittees add index FK3061F1B71A987C7D (Parliament_id), add constraint FK3061F1B71A987C7D foreign key (Parliament_id) references Parliament (id);
alter table ParliamentElections add index FKDFF1CE39BB3922C3 (elections_id), add constraint FKDFF1CE39BB3922C3 foreign key (elections_id) references Election (id);
alter table ParliamentElections add index FKDFF1CE391A987C7D (Parliament_id), add constraint FKDFF1CE391A987C7D foreign key (Parliament_id) references Parliament (id);
create index electoralRegionIndex on ParliamentMember (electoralRegion);
create index nameIndex on ParliamentMember (name);
create index partyIndex on ParliamentMember (party);
alter table ParliamentMember add index FKF6C83C3BDCE10A7A (politician_id), add constraint FKF6C83C3BDCE10A7A foreign key (politician_id) references Person (id);
alter table ParliamentMember add index FKF6C83C3B88C7583A (politicalParty_id), add constraint FKF6C83C3B88C7583A foreign key (politicalParty_id) references PoliticalParty (id);
alter table ParliamentMember add index FKF6C83C3B600D569B (parliamentMemberBallotRecordId), add constraint FKF6C83C3B600D569B foreign key (parliamentMemberBallotRecordId) references AbstractBallotMetaData (id);
alter table ParliamentMemberVoteCompareResult add index FK94A1FB9DFA3FC73A (parliamentMember_id), add constraint FK94A1FB9DFA3FC73A foreign key (parliamentMember_id) references ParliamentMember (id);
alter table ParliamentMemberVoteCompareResult add index FK94A1FB9D106A26BD (opponentParliamentMember_id), add constraint FK94A1FB9D106A26BD foreign key (opponentParliamentMember_id) references ParliamentMember (id);
alter table ParliamentYears add index FK637596151A987C7D (Parliament_id), add constraint FK637596151A987C7D foreign key (Parliament_id) references Parliament (id);
alter table ParliamentYears add index FK637596157CFBB86D (parliamentYears_id), add constraint FK637596157CFBB86D foreign key (parliamentYears_id) references ParliamentYear (id);
create index parliamentPersonPlaceOfResidenceIndex on Person (placeOfResidence);
create index parliamentPersonRegionIndex on Person (electoralRegion);
create index parliamentPersonParty on Person (party);
create index parliamentPersonIndex on Person (parliamentPersonId);
alter table Player add index FK8EA38701B5804075 (user_id), add constraint FK8EA38701B5804075 foreign key (user_id) references User (id);
alter table Player add index FK8EA3870188297A1A (shadowParliamentMember_id), add constraint FK8EA3870188297A1A foreign key (shadowParliamentMember_id) references ParliamentMember (id);
alter table PoliticalGameBoards add index FKDEC3739CB96AB33F (PoliticalGame_id), add constraint FKDEC3739CB96AB33F foreign key (PoliticalGame_id) references PoliticalGame (id);
alter table PoliticalGameBoards add index FKDEC3739C7343A4F4 (gameBoards_id), add constraint FKDEC3739C7343A4F4 foreign key (gameBoards_id) references GameBoard (id);
create index shortCodeIndex on PoliticalParty (shortCode);
create index nameIndex on PoliticalParty (name);
alter table PoliticalParty add index FKC6680E09CC2C45C4 (election_id), add constraint FKC6680E09CC2C45C4 foreign key (election_id) references Election (id);
alter table PortalLanguageContent add index FK73755FD5A7A50483 (AbstractResource_id), add constraint FK73755FD5A7A50483 foreign key (AbstractResource_id) references AbstractResource (id);
alter table PortalLanguageContent add index FK73755FD5A6243D0 (languageContent_id), add constraint FK73755FD5A6243D0 foreign key (languageContent_id) references AbstractResource (id);
create index usernameIndex on User (username);
alter table User add index FK285FEB5ABB270E (human_id), add constraint FK285FEB5ABB270E foreign key (human_id) references Person (id);
alter table UserSession add index FKC7BC0C2BAEEC74C7 (portal_id), add constraint FKC7BC0C2BAEEC74C7 foreign key (portal_id) references AbstractResource (id);
alter table UserSession add index FKC7BC0C2BB5804075 (user_id), add constraint FKC7BC0C2BB5804075 foreign key (user_id) references User (id);
alter table UserSession add index FKC7BC0C2B14985DA4 (language_id), add constraint FKC7BC0C2B14985DA4 foreign key (language_id) references AbstractResource (id);
alter table UserSessionEvents add index FK349BCD2410F032BF (UserSession_id), add constraint FK349BCD2410F032BF foreign key (UserSession_id) references UserSession (id);
alter table UserSessionEvents add index FK349BCD243D63B160 (events_id), add constraint FK349BCD243D63B160 foreign key (events_id) references AbstractActionEvent (id);
alter table Vote add index FK28C70AFA3FC73A (parliamentMember_id), add constraint FK28C70AFA3FC73A foreign key (parliamentMember_id) references ParliamentMember (id);
alter table Vote add index FK28C70ACDE50E7A (ballot_id), add constraint FK28C70ACDE50E7A foreign key (ballot_id) references Ballot (id);
