@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ParliamentRankingView\n<size:10>com.hack23.cia.web.impl.ui.application.views.user.parliament" as com.hack23.cia.web.impl.ui.application.views.user.parliament.ParliamentRankingView [[ParliamentRankingView.html]] {
        {static} +NAME: String
        +ParliamentRankingView(ApplicationContext)
    }

    abstract class "<size:14>AbstractRankingView\n<size:10>com.hack23.cia.web.impl.ui.application.views.user.common" as com.hack23.cia.web.impl.ui.application.views.user.common.AbstractRankingView [[../common/AbstractRankingView.html]]

    com.hack23.cia.web.impl.ui.application.views.user.common.AbstractRankingView <|-- com.hack23.cia.web.impl.ui.application.views.user.parliament.ParliamentRankingView

    center footer UMLDoclet 2.0.3, PlantUML 1.2019.06
@enduml
