@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>ViewDataDataContainerFactory\n<size:10>com.hack23.cia.service.impl" as com.hack23.cia.service.impl.ViewDataDataContainerFactory [[ViewDataDataContainerFactory.html]] {
        {abstract} +createDataContainer(Class<T extends Serializable>): DataContainer<T extends Serializable, I extends Serializable>
    }

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
