@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ExternalAttachmentDownloadLink\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.pagelinks.impl" as com.hack23.cia.web.impl.ui.application.views.common.pagelinks.impl.ExternalAttachmentDownloadLink [[ExternalAttachmentDownloadLink.html]] {
        +ExternalAttachmentDownloadLink(String, String, String)
        +attach(): void
    }

    class "<size:14>Link\n<size:10>com.vaadin.ui" as com.vaadin.ui.Link

    com.vaadin.ui.Link <|-- com.hack23.cia.web.impl.ui.application.views.common.pagelinks.impl.ExternalAttachmentDownloadLink

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
