//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.25 at 12:05:09 AM CET 
//


package com.hack23.cia.model.internal.application.data.politician.impl;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.hack23.cia.model.common.api.ModelObject;
import com.hack23.cia.model.common.impl.xml.XmlDateTypeAdapter;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for ViewRiksdagenPolitician complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ViewRiksdagenPolitician"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="personId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="party" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="bornYear" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="totalAssignments" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="currentAssignments" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="firstAssignmentDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="lastAssignmentDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="totalDaysServed" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="totalDaysServedParliament" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="totalDaysServedCommittee" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="totalDaysServedGovernment" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="totalDaysServedEu" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="active" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="activeEu" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="activeGovernment" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="activeCommittee" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="activeParliament" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="activeParty" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="activeSpeaker" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="totalDaysServedSpeaker" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="totalDaysServedParty" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="totalPartyAssignments" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="totalMinistryAssignments" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="totalCommitteeAssignments" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="totalSpeakerAssignments" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="currentPartyAssignments" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="currentMinistryAssignments" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="currentCommitteeAssignments" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="currentSpeakerAssignments" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ViewRiksdagenPolitician", propOrder = {
    "personId",
    "firstName",
    "lastName",
    "party",
    "gender",
    "bornYear",
    "totalAssignments",
    "currentAssignments",
    "firstAssignmentDate",
    "lastAssignmentDate",
    "totalDaysServed",
    "totalDaysServedParliament",
    "totalDaysServedCommittee",
    "totalDaysServedGovernment",
    "totalDaysServedEu",
    "active",
    "activeEu",
    "activeGovernment",
    "activeCommittee",
    "activeParliament",
    "activeParty",
    "activeSpeaker",
    "totalDaysServedSpeaker",
    "totalDaysServedParty",
    "totalPartyAssignments",
    "totalMinistryAssignments",
    "totalCommitteeAssignments",
    "totalSpeakerAssignments",
    "currentPartyAssignments",
    "currentMinistryAssignments",
    "currentCommitteeAssignments",
    "currentSpeakerAssignments"
})
@Entity(name = "ViewRiksdagenPolitician")
@Table(name = "VIEW_RIKSDAGEN_POLITICIAN")
@Inheritance(strategy = InheritanceType.JOINED)
public class ViewRiksdagenPolitician
    implements Serializable, ModelObject, Equals, HashCode, ToString
{

    @XmlElement(required = true)
    protected String personId;
    @XmlElement(required = true)
    protected String firstName;
    @XmlElement(required = true)
    protected String lastName;
    @XmlElement(required = true)
    protected String party;
    @XmlElement(required = true)
    protected String gender;
    protected int bornYear;
    protected long totalAssignments;
    protected long currentAssignments;
    @XmlElement(required = true, type = String.class, nillable = true)
    @XmlJavaTypeAdapter(XmlDateTypeAdapter.class)
    @XmlSchemaType(name = "date")
    protected Date firstAssignmentDate;
    @XmlElement(required = true, type = String.class, nillable = true)
    @XmlJavaTypeAdapter(XmlDateTypeAdapter.class)
    @XmlSchemaType(name = "date")
    protected Date lastAssignmentDate;
    protected long totalDaysServed;
    protected long totalDaysServedParliament;
    protected long totalDaysServedCommittee;
    protected long totalDaysServedGovernment;
    protected long totalDaysServedEu;
    protected boolean active;
    protected boolean activeEu;
    protected boolean activeGovernment;
    protected boolean activeCommittee;
    protected boolean activeParliament;
    protected boolean activeParty;
    protected boolean activeSpeaker;
    protected long totalDaysServedSpeaker;
    protected long totalDaysServedParty;
    protected long totalPartyAssignments;
    protected long totalMinistryAssignments;
    protected long totalCommitteeAssignments;
    protected long totalSpeakerAssignments;
    protected long currentPartyAssignments;
    protected long currentMinistryAssignments;
    protected long currentCommitteeAssignments;
    protected long currentSpeakerAssignments;

    /**
     * Gets the value of the personId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Id
    @Column(name = "PERSON_ID")
    public String getPersonId() {
        return personId;
    }

    /**
     * Sets the value of the personId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonId(String value) {
        this.personId = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "FIRST_NAME", length = 255)
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "LAST_NAME", length = 255)
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the party property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "PARTY", length = 255)
    public String getParty() {
        return party;
    }

    /**
     * Sets the value of the party property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParty(String value) {
        this.party = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "GENDER", length = 255)
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the bornYear property.
     * 
     */
    @Basic
    @Column(name = "BORN_YEAR", precision = 10, scale = 0)
    public int getBornYear() {
        return bornYear;
    }

    /**
     * Sets the value of the bornYear property.
     * 
     */
    public void setBornYear(int value) {
        this.bornYear = value;
    }

    /**
     * Gets the value of the totalAssignments property.
     * 
     */
    @Basic
    @Column(name = "TOTAL_ASSIGNMENTS", precision = 20, scale = 0)
    public long getTotalAssignments() {
        return totalAssignments;
    }

    /**
     * Sets the value of the totalAssignments property.
     * 
     */
    public void setTotalAssignments(long value) {
        this.totalAssignments = value;
    }

    /**
     * Gets the value of the currentAssignments property.
     * 
     */
    @Basic
    @Column(name = "CURRENT_ASSIGNMENTS", precision = 20, scale = 0)
    public long getCurrentAssignments() {
        return currentAssignments;
    }

    /**
     * Sets the value of the currentAssignments property.
     * 
     */
    public void setCurrentAssignments(long value) {
        this.currentAssignments = value;
    }

    /**
     * Gets the value of the firstAssignmentDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "FIRST_ASSIGNMENT_DATE")
    @Temporal(TemporalType.DATE)
    public Date getFirstAssignmentDate() {
        return firstAssignmentDate;
    }

    /**
     * Sets the value of the firstAssignmentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstAssignmentDate(Date value) {
        this.firstAssignmentDate = value;
    }

    /**
     * Gets the value of the lastAssignmentDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "LAST_ASSIGNMENT_DATE")
    @Temporal(TemporalType.DATE)
    public Date getLastAssignmentDate() {
        return lastAssignmentDate;
    }

    /**
     * Sets the value of the lastAssignmentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastAssignmentDate(Date value) {
        this.lastAssignmentDate = value;
    }

    /**
     * Gets the value of the totalDaysServed property.
     * 
     */
    @Basic
    @Column(name = "TOTAL_DAYS_SERVED", precision = 20, scale = 0)
    public long getTotalDaysServed() {
        return totalDaysServed;
    }

    /**
     * Sets the value of the totalDaysServed property.
     * 
     */
    public void setTotalDaysServed(long value) {
        this.totalDaysServed = value;
    }

    /**
     * Gets the value of the totalDaysServedParliament property.
     * 
     */
    @Basic
    @Column(name = "TOTAL_DAYS_SERVED_PARLIAMENT", precision = 20, scale = 0)
    public long getTotalDaysServedParliament() {
        return totalDaysServedParliament;
    }

    /**
     * Sets the value of the totalDaysServedParliament property.
     * 
     */
    public void setTotalDaysServedParliament(long value) {
        this.totalDaysServedParliament = value;
    }

    /**
     * Gets the value of the totalDaysServedCommittee property.
     * 
     */
    @Basic
    @Column(name = "TOTAL_DAYS_SERVED_COMMITTEE", precision = 20, scale = 0)
    public long getTotalDaysServedCommittee() {
        return totalDaysServedCommittee;
    }

    /**
     * Sets the value of the totalDaysServedCommittee property.
     * 
     */
    public void setTotalDaysServedCommittee(long value) {
        this.totalDaysServedCommittee = value;
    }

    /**
     * Gets the value of the totalDaysServedGovernment property.
     * 
     */
    @Basic
    @Column(name = "TOTAL_DAYS_SERVED_GOVERNMENT", precision = 20, scale = 0)
    public long getTotalDaysServedGovernment() {
        return totalDaysServedGovernment;
    }

    /**
     * Sets the value of the totalDaysServedGovernment property.
     * 
     */
    public void setTotalDaysServedGovernment(long value) {
        this.totalDaysServedGovernment = value;
    }

    /**
     * Gets the value of the totalDaysServedEu property.
     * 
     */
    @Basic
    @Column(name = "TOTAL_DAYS_SERVED_EU", precision = 20, scale = 0)
    public long getTotalDaysServedEu() {
        return totalDaysServedEu;
    }

    /**
     * Sets the value of the totalDaysServedEu property.
     * 
     */
    public void setTotalDaysServedEu(long value) {
        this.totalDaysServedEu = value;
    }

    /**
     * Gets the value of the active property.
     * 
     */
    @Basic
    @Column(name = "ACTIVE")
    public boolean isActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     */
    public void setActive(boolean value) {
        this.active = value;
    }

    /**
     * Gets the value of the activeEu property.
     * 
     */
    @Basic
    @Column(name = "ACTIVE_EU")
    public boolean isActiveEu() {
        return activeEu;
    }

    /**
     * Sets the value of the activeEu property.
     * 
     */
    public void setActiveEu(boolean value) {
        this.activeEu = value;
    }

    /**
     * Gets the value of the activeGovernment property.
     * 
     */
    @Basic
    @Column(name = "ACTIVE_GOVERNMENT")
    public boolean isActiveGovernment() {
        return activeGovernment;
    }

    /**
     * Sets the value of the activeGovernment property.
     * 
     */
    public void setActiveGovernment(boolean value) {
        this.activeGovernment = value;
    }

    /**
     * Gets the value of the activeCommittee property.
     * 
     */
    @Basic
    @Column(name = "ACTIVE_COMMITTEE")
    public boolean isActiveCommittee() {
        return activeCommittee;
    }

    /**
     * Sets the value of the activeCommittee property.
     * 
     */
    public void setActiveCommittee(boolean value) {
        this.activeCommittee = value;
    }

    /**
     * Gets the value of the activeParliament property.
     * 
     */
    @Basic
    @Column(name = "ACTIVE_PARLIAMENT")
    public boolean isActiveParliament() {
        return activeParliament;
    }

    /**
     * Sets the value of the activeParliament property.
     * 
     */
    public void setActiveParliament(boolean value) {
        this.activeParliament = value;
    }

    /**
     * Gets the value of the activeParty property.
     * 
     */
    @Basic
    @Column(name = "ACTIVE_PARTY")
    public boolean isActiveParty() {
        return activeParty;
    }

    /**
     * Sets the value of the activeParty property.
     * 
     */
    public void setActiveParty(boolean value) {
        this.activeParty = value;
    }

    /**
     * Gets the value of the activeSpeaker property.
     * 
     */
    @Basic
    @Column(name = "ACTIVE_SPEAKER")
    public boolean isActiveSpeaker() {
        return activeSpeaker;
    }

    /**
     * Sets the value of the activeSpeaker property.
     * 
     */
    public void setActiveSpeaker(boolean value) {
        this.activeSpeaker = value;
    }

    /**
     * Gets the value of the totalDaysServedSpeaker property.
     * 
     */
    @Basic
    @Column(name = "TOTAL_DAYS_SERVED_SPEAKER", precision = 20, scale = 0)
    public long getTotalDaysServedSpeaker() {
        return totalDaysServedSpeaker;
    }

    /**
     * Sets the value of the totalDaysServedSpeaker property.
     * 
     */
    public void setTotalDaysServedSpeaker(long value) {
        this.totalDaysServedSpeaker = value;
    }

    /**
     * Gets the value of the totalDaysServedParty property.
     * 
     */
    @Basic
    @Column(name = "TOTAL_DAYS_SERVED_PARTY", precision = 20, scale = 0)
    public long getTotalDaysServedParty() {
        return totalDaysServedParty;
    }

    /**
     * Sets the value of the totalDaysServedParty property.
     * 
     */
    public void setTotalDaysServedParty(long value) {
        this.totalDaysServedParty = value;
    }

    /**
     * Gets the value of the totalPartyAssignments property.
     * 
     */
    @Basic
    @Column(name = "TOTAL_PARTY_ASSIGNMENTS", precision = 20, scale = 0)
    public long getTotalPartyAssignments() {
        return totalPartyAssignments;
    }

    /**
     * Sets the value of the totalPartyAssignments property.
     * 
     */
    public void setTotalPartyAssignments(long value) {
        this.totalPartyAssignments = value;
    }

    /**
     * Gets the value of the totalMinistryAssignments property.
     * 
     */
    @Basic
    @Column(name = "TOTAL_MINISTRY_ASSIGNMENTS", precision = 20, scale = 0)
    public long getTotalMinistryAssignments() {
        return totalMinistryAssignments;
    }

    /**
     * Sets the value of the totalMinistryAssignments property.
     * 
     */
    public void setTotalMinistryAssignments(long value) {
        this.totalMinistryAssignments = value;
    }

    /**
     * Gets the value of the totalCommitteeAssignments property.
     * 
     */
    @Basic
    @Column(name = "TOTAL_COMMITTEE_ASSIGNMENTS", precision = 20, scale = 0)
    public long getTotalCommitteeAssignments() {
        return totalCommitteeAssignments;
    }

    /**
     * Sets the value of the totalCommitteeAssignments property.
     * 
     */
    public void setTotalCommitteeAssignments(long value) {
        this.totalCommitteeAssignments = value;
    }

    /**
     * Gets the value of the totalSpeakerAssignments property.
     * 
     */
    @Basic
    @Column(name = "TOTAL_SPEAKER_ASSIGNMENTS", precision = 20, scale = 0)
    public long getTotalSpeakerAssignments() {
        return totalSpeakerAssignments;
    }

    /**
     * Sets the value of the totalSpeakerAssignments property.
     * 
     */
    public void setTotalSpeakerAssignments(long value) {
        this.totalSpeakerAssignments = value;
    }

    /**
     * Gets the value of the currentPartyAssignments property.
     * 
     */
    @Basic
    @Column(name = "CURRENT_PARTY_ASSIGNMENTS", precision = 20, scale = 0)
    public long getCurrentPartyAssignments() {
        return currentPartyAssignments;
    }

    /**
     * Sets the value of the currentPartyAssignments property.
     * 
     */
    public void setCurrentPartyAssignments(long value) {
        this.currentPartyAssignments = value;
    }

    /**
     * Gets the value of the currentMinistryAssignments property.
     * 
     */
    @Basic
    @Column(name = "CURRENT_MINISTRY_ASSIGNMENTS", precision = 20, scale = 0)
    public long getCurrentMinistryAssignments() {
        return currentMinistryAssignments;
    }

    /**
     * Sets the value of the currentMinistryAssignments property.
     * 
     */
    public void setCurrentMinistryAssignments(long value) {
        this.currentMinistryAssignments = value;
    }

    /**
     * Gets the value of the currentCommitteeAssignments property.
     * 
     */
    @Basic
    @Column(name = "CURRENT_COMMITTEE_ASSIGNMENTS", precision = 20, scale = 0)
    public long getCurrentCommitteeAssignments() {
        return currentCommitteeAssignments;
    }

    /**
     * Sets the value of the currentCommitteeAssignments property.
     * 
     */
    public void setCurrentCommitteeAssignments(long value) {
        this.currentCommitteeAssignments = value;
    }

    /**
     * Gets the value of the currentSpeakerAssignments property.
     * 
     */
    @Basic
    @Column(name = "CURRENT_SPEAKER_ASSIGNMENTS", precision = 20, scale = 0)
    public long getCurrentSpeakerAssignments() {
        return currentSpeakerAssignments;
    }

    /**
     * Sets the value of the currentSpeakerAssignments property.
     * 
     */
    public void setCurrentSpeakerAssignments(long value) {
        this.currentSpeakerAssignments = value;
    }

    public ViewRiksdagenPolitician withPersonId(String value) {
        setPersonId(value);
        return this;
    }

    public ViewRiksdagenPolitician withFirstName(String value) {
        setFirstName(value);
        return this;
    }

    public ViewRiksdagenPolitician withLastName(String value) {
        setLastName(value);
        return this;
    }

    public ViewRiksdagenPolitician withParty(String value) {
        setParty(value);
        return this;
    }

    public ViewRiksdagenPolitician withGender(String value) {
        setGender(value);
        return this;
    }

    public ViewRiksdagenPolitician withBornYear(int value) {
        setBornYear(value);
        return this;
    }

    public ViewRiksdagenPolitician withTotalAssignments(long value) {
        setTotalAssignments(value);
        return this;
    }

    public ViewRiksdagenPolitician withCurrentAssignments(long value) {
        setCurrentAssignments(value);
        return this;
    }

    public ViewRiksdagenPolitician withFirstAssignmentDate(Date value) {
        setFirstAssignmentDate(value);
        return this;
    }

    public ViewRiksdagenPolitician withLastAssignmentDate(Date value) {
        setLastAssignmentDate(value);
        return this;
    }

    public ViewRiksdagenPolitician withTotalDaysServed(long value) {
        setTotalDaysServed(value);
        return this;
    }

    public ViewRiksdagenPolitician withTotalDaysServedParliament(long value) {
        setTotalDaysServedParliament(value);
        return this;
    }

    public ViewRiksdagenPolitician withTotalDaysServedCommittee(long value) {
        setTotalDaysServedCommittee(value);
        return this;
    }

    public ViewRiksdagenPolitician withTotalDaysServedGovernment(long value) {
        setTotalDaysServedGovernment(value);
        return this;
    }

    public ViewRiksdagenPolitician withTotalDaysServedEu(long value) {
        setTotalDaysServedEu(value);
        return this;
    }

    public ViewRiksdagenPolitician withActive(boolean value) {
        setActive(value);
        return this;
    }

    public ViewRiksdagenPolitician withActiveEu(boolean value) {
        setActiveEu(value);
        return this;
    }

    public ViewRiksdagenPolitician withActiveGovernment(boolean value) {
        setActiveGovernment(value);
        return this;
    }

    public ViewRiksdagenPolitician withActiveCommittee(boolean value) {
        setActiveCommittee(value);
        return this;
    }

    public ViewRiksdagenPolitician withActiveParliament(boolean value) {
        setActiveParliament(value);
        return this;
    }

    public ViewRiksdagenPolitician withActiveParty(boolean value) {
        setActiveParty(value);
        return this;
    }

    public ViewRiksdagenPolitician withActiveSpeaker(boolean value) {
        setActiveSpeaker(value);
        return this;
    }

    public ViewRiksdagenPolitician withTotalDaysServedSpeaker(long value) {
        setTotalDaysServedSpeaker(value);
        return this;
    }

    public ViewRiksdagenPolitician withTotalDaysServedParty(long value) {
        setTotalDaysServedParty(value);
        return this;
    }

    public ViewRiksdagenPolitician withTotalPartyAssignments(long value) {
        setTotalPartyAssignments(value);
        return this;
    }

    public ViewRiksdagenPolitician withTotalMinistryAssignments(long value) {
        setTotalMinistryAssignments(value);
        return this;
    }

    public ViewRiksdagenPolitician withTotalCommitteeAssignments(long value) {
        setTotalCommitteeAssignments(value);
        return this;
    }

    public ViewRiksdagenPolitician withTotalSpeakerAssignments(long value) {
        setTotalSpeakerAssignments(value);
        return this;
    }

    public ViewRiksdagenPolitician withCurrentPartyAssignments(long value) {
        setCurrentPartyAssignments(value);
        return this;
    }

    public ViewRiksdagenPolitician withCurrentMinistryAssignments(long value) {
        setCurrentMinistryAssignments(value);
        return this;
    }

    public ViewRiksdagenPolitician withCurrentCommitteeAssignments(long value) {
        setCurrentCommitteeAssignments(value);
        return this;
    }

    public ViewRiksdagenPolitician withCurrentSpeakerAssignments(long value) {
        setCurrentSpeakerAssignments(value);
        return this;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String thePersonId;
            thePersonId = this.getPersonId();
            strategy.appendField(locator, this, "personId", buffer, thePersonId);
        }
        {
            String theFirstName;
            theFirstName = this.getFirstName();
            strategy.appendField(locator, this, "firstName", buffer, theFirstName);
        }
        {
            String theLastName;
            theLastName = this.getLastName();
            strategy.appendField(locator, this, "lastName", buffer, theLastName);
        }
        {
            String theParty;
            theParty = this.getParty();
            strategy.appendField(locator, this, "party", buffer, theParty);
        }
        {
            String theGender;
            theGender = this.getGender();
            strategy.appendField(locator, this, "gender", buffer, theGender);
        }
        {
            int theBornYear;
            theBornYear = this.getBornYear();
            strategy.appendField(locator, this, "bornYear", buffer, theBornYear);
        }
        {
            long theTotalAssignments;
            theTotalAssignments = this.getTotalAssignments();
            strategy.appendField(locator, this, "totalAssignments", buffer, theTotalAssignments);
        }
        {
            long theCurrentAssignments;
            theCurrentAssignments = this.getCurrentAssignments();
            strategy.appendField(locator, this, "currentAssignments", buffer, theCurrentAssignments);
        }
        {
            Date theFirstAssignmentDate;
            theFirstAssignmentDate = this.getFirstAssignmentDate();
            strategy.appendField(locator, this, "firstAssignmentDate", buffer, theFirstAssignmentDate);
        }
        {
            Date theLastAssignmentDate;
            theLastAssignmentDate = this.getLastAssignmentDate();
            strategy.appendField(locator, this, "lastAssignmentDate", buffer, theLastAssignmentDate);
        }
        {
            long theTotalDaysServed;
            theTotalDaysServed = this.getTotalDaysServed();
            strategy.appendField(locator, this, "totalDaysServed", buffer, theTotalDaysServed);
        }
        {
            long theTotalDaysServedParliament;
            theTotalDaysServedParliament = this.getTotalDaysServedParliament();
            strategy.appendField(locator, this, "totalDaysServedParliament", buffer, theTotalDaysServedParliament);
        }
        {
            long theTotalDaysServedCommittee;
            theTotalDaysServedCommittee = this.getTotalDaysServedCommittee();
            strategy.appendField(locator, this, "totalDaysServedCommittee", buffer, theTotalDaysServedCommittee);
        }
        {
            long theTotalDaysServedGovernment;
            theTotalDaysServedGovernment = this.getTotalDaysServedGovernment();
            strategy.appendField(locator, this, "totalDaysServedGovernment", buffer, theTotalDaysServedGovernment);
        }
        {
            long theTotalDaysServedEu;
            theTotalDaysServedEu = this.getTotalDaysServedEu();
            strategy.appendField(locator, this, "totalDaysServedEu", buffer, theTotalDaysServedEu);
        }
        {
            boolean theActive;
            theActive = this.isActive();
            strategy.appendField(locator, this, "active", buffer, theActive);
        }
        {
            boolean theActiveEu;
            theActiveEu = this.isActiveEu();
            strategy.appendField(locator, this, "activeEu", buffer, theActiveEu);
        }
        {
            boolean theActiveGovernment;
            theActiveGovernment = this.isActiveGovernment();
            strategy.appendField(locator, this, "activeGovernment", buffer, theActiveGovernment);
        }
        {
            boolean theActiveCommittee;
            theActiveCommittee = this.isActiveCommittee();
            strategy.appendField(locator, this, "activeCommittee", buffer, theActiveCommittee);
        }
        {
            boolean theActiveParliament;
            theActiveParliament = this.isActiveParliament();
            strategy.appendField(locator, this, "activeParliament", buffer, theActiveParliament);
        }
        {
            boolean theActiveParty;
            theActiveParty = this.isActiveParty();
            strategy.appendField(locator, this, "activeParty", buffer, theActiveParty);
        }
        {
            boolean theActiveSpeaker;
            theActiveSpeaker = this.isActiveSpeaker();
            strategy.appendField(locator, this, "activeSpeaker", buffer, theActiveSpeaker);
        }
        {
            long theTotalDaysServedSpeaker;
            theTotalDaysServedSpeaker = this.getTotalDaysServedSpeaker();
            strategy.appendField(locator, this, "totalDaysServedSpeaker", buffer, theTotalDaysServedSpeaker);
        }
        {
            long theTotalDaysServedParty;
            theTotalDaysServedParty = this.getTotalDaysServedParty();
            strategy.appendField(locator, this, "totalDaysServedParty", buffer, theTotalDaysServedParty);
        }
        {
            long theTotalPartyAssignments;
            theTotalPartyAssignments = this.getTotalPartyAssignments();
            strategy.appendField(locator, this, "totalPartyAssignments", buffer, theTotalPartyAssignments);
        }
        {
            long theTotalMinistryAssignments;
            theTotalMinistryAssignments = this.getTotalMinistryAssignments();
            strategy.appendField(locator, this, "totalMinistryAssignments", buffer, theTotalMinistryAssignments);
        }
        {
            long theTotalCommitteeAssignments;
            theTotalCommitteeAssignments = this.getTotalCommitteeAssignments();
            strategy.appendField(locator, this, "totalCommitteeAssignments", buffer, theTotalCommitteeAssignments);
        }
        {
            long theTotalSpeakerAssignments;
            theTotalSpeakerAssignments = this.getTotalSpeakerAssignments();
            strategy.appendField(locator, this, "totalSpeakerAssignments", buffer, theTotalSpeakerAssignments);
        }
        {
            long theCurrentPartyAssignments;
            theCurrentPartyAssignments = this.getCurrentPartyAssignments();
            strategy.appendField(locator, this, "currentPartyAssignments", buffer, theCurrentPartyAssignments);
        }
        {
            long theCurrentMinistryAssignments;
            theCurrentMinistryAssignments = this.getCurrentMinistryAssignments();
            strategy.appendField(locator, this, "currentMinistryAssignments", buffer, theCurrentMinistryAssignments);
        }
        {
            long theCurrentCommitteeAssignments;
            theCurrentCommitteeAssignments = this.getCurrentCommitteeAssignments();
            strategy.appendField(locator, this, "currentCommitteeAssignments", buffer, theCurrentCommitteeAssignments);
        }
        {
            long theCurrentSpeakerAssignments;
            theCurrentSpeakerAssignments = this.getCurrentSpeakerAssignments();
            strategy.appendField(locator, this, "currentSpeakerAssignments", buffer, theCurrentSpeakerAssignments);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final ViewRiksdagenPolitician that = ((ViewRiksdagenPolitician) object);
        {
            String lhsPersonId;
            lhsPersonId = this.getPersonId();
            String rhsPersonId;
            rhsPersonId = that.getPersonId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "personId", lhsPersonId), LocatorUtils.property(thatLocator, "personId", rhsPersonId), lhsPersonId, rhsPersonId)) {
                return false;
            }
        }
        {
            String lhsFirstName;
            lhsFirstName = this.getFirstName();
            String rhsFirstName;
            rhsFirstName = that.getFirstName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "firstName", lhsFirstName), LocatorUtils.property(thatLocator, "firstName", rhsFirstName), lhsFirstName, rhsFirstName)) {
                return false;
            }
        }
        {
            String lhsLastName;
            lhsLastName = this.getLastName();
            String rhsLastName;
            rhsLastName = that.getLastName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "lastName", lhsLastName), LocatorUtils.property(thatLocator, "lastName", rhsLastName), lhsLastName, rhsLastName)) {
                return false;
            }
        }
        {
            String lhsParty;
            lhsParty = this.getParty();
            String rhsParty;
            rhsParty = that.getParty();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "party", lhsParty), LocatorUtils.property(thatLocator, "party", rhsParty), lhsParty, rhsParty)) {
                return false;
            }
        }
        {
            String lhsGender;
            lhsGender = this.getGender();
            String rhsGender;
            rhsGender = that.getGender();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "gender", lhsGender), LocatorUtils.property(thatLocator, "gender", rhsGender), lhsGender, rhsGender)) {
                return false;
            }
        }
        {
            int lhsBornYear;
            lhsBornYear = this.getBornYear();
            int rhsBornYear;
            rhsBornYear = that.getBornYear();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "bornYear", lhsBornYear), LocatorUtils.property(thatLocator, "bornYear", rhsBornYear), lhsBornYear, rhsBornYear)) {
                return false;
            }
        }
        {
            long lhsTotalAssignments;
            lhsTotalAssignments = this.getTotalAssignments();
            long rhsTotalAssignments;
            rhsTotalAssignments = that.getTotalAssignments();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "totalAssignments", lhsTotalAssignments), LocatorUtils.property(thatLocator, "totalAssignments", rhsTotalAssignments), lhsTotalAssignments, rhsTotalAssignments)) {
                return false;
            }
        }
        {
            long lhsCurrentAssignments;
            lhsCurrentAssignments = this.getCurrentAssignments();
            long rhsCurrentAssignments;
            rhsCurrentAssignments = that.getCurrentAssignments();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "currentAssignments", lhsCurrentAssignments), LocatorUtils.property(thatLocator, "currentAssignments", rhsCurrentAssignments), lhsCurrentAssignments, rhsCurrentAssignments)) {
                return false;
            }
        }
        {
            Date lhsFirstAssignmentDate;
            lhsFirstAssignmentDate = this.getFirstAssignmentDate();
            Date rhsFirstAssignmentDate;
            rhsFirstAssignmentDate = that.getFirstAssignmentDate();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "firstAssignmentDate", lhsFirstAssignmentDate), LocatorUtils.property(thatLocator, "firstAssignmentDate", rhsFirstAssignmentDate), lhsFirstAssignmentDate, rhsFirstAssignmentDate)) {
                return false;
            }
        }
        {
            Date lhsLastAssignmentDate;
            lhsLastAssignmentDate = this.getLastAssignmentDate();
            Date rhsLastAssignmentDate;
            rhsLastAssignmentDate = that.getLastAssignmentDate();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "lastAssignmentDate", lhsLastAssignmentDate), LocatorUtils.property(thatLocator, "lastAssignmentDate", rhsLastAssignmentDate), lhsLastAssignmentDate, rhsLastAssignmentDate)) {
                return false;
            }
        }
        {
            long lhsTotalDaysServed;
            lhsTotalDaysServed = this.getTotalDaysServed();
            long rhsTotalDaysServed;
            rhsTotalDaysServed = that.getTotalDaysServed();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "totalDaysServed", lhsTotalDaysServed), LocatorUtils.property(thatLocator, "totalDaysServed", rhsTotalDaysServed), lhsTotalDaysServed, rhsTotalDaysServed)) {
                return false;
            }
        }
        {
            long lhsTotalDaysServedParliament;
            lhsTotalDaysServedParliament = this.getTotalDaysServedParliament();
            long rhsTotalDaysServedParliament;
            rhsTotalDaysServedParliament = that.getTotalDaysServedParliament();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "totalDaysServedParliament", lhsTotalDaysServedParliament), LocatorUtils.property(thatLocator, "totalDaysServedParliament", rhsTotalDaysServedParliament), lhsTotalDaysServedParliament, rhsTotalDaysServedParliament)) {
                return false;
            }
        }
        {
            long lhsTotalDaysServedCommittee;
            lhsTotalDaysServedCommittee = this.getTotalDaysServedCommittee();
            long rhsTotalDaysServedCommittee;
            rhsTotalDaysServedCommittee = that.getTotalDaysServedCommittee();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "totalDaysServedCommittee", lhsTotalDaysServedCommittee), LocatorUtils.property(thatLocator, "totalDaysServedCommittee", rhsTotalDaysServedCommittee), lhsTotalDaysServedCommittee, rhsTotalDaysServedCommittee)) {
                return false;
            }
        }
        {
            long lhsTotalDaysServedGovernment;
            lhsTotalDaysServedGovernment = this.getTotalDaysServedGovernment();
            long rhsTotalDaysServedGovernment;
            rhsTotalDaysServedGovernment = that.getTotalDaysServedGovernment();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "totalDaysServedGovernment", lhsTotalDaysServedGovernment), LocatorUtils.property(thatLocator, "totalDaysServedGovernment", rhsTotalDaysServedGovernment), lhsTotalDaysServedGovernment, rhsTotalDaysServedGovernment)) {
                return false;
            }
        }
        {
            long lhsTotalDaysServedEu;
            lhsTotalDaysServedEu = this.getTotalDaysServedEu();
            long rhsTotalDaysServedEu;
            rhsTotalDaysServedEu = that.getTotalDaysServedEu();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "totalDaysServedEu", lhsTotalDaysServedEu), LocatorUtils.property(thatLocator, "totalDaysServedEu", rhsTotalDaysServedEu), lhsTotalDaysServedEu, rhsTotalDaysServedEu)) {
                return false;
            }
        }
        {
            boolean lhsActive;
            lhsActive = this.isActive();
            boolean rhsActive;
            rhsActive = that.isActive();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "active", lhsActive), LocatorUtils.property(thatLocator, "active", rhsActive), lhsActive, rhsActive)) {
                return false;
            }
        }
        {
            boolean lhsActiveEu;
            lhsActiveEu = this.isActiveEu();
            boolean rhsActiveEu;
            rhsActiveEu = that.isActiveEu();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "activeEu", lhsActiveEu), LocatorUtils.property(thatLocator, "activeEu", rhsActiveEu), lhsActiveEu, rhsActiveEu)) {
                return false;
            }
        }
        {
            boolean lhsActiveGovernment;
            lhsActiveGovernment = this.isActiveGovernment();
            boolean rhsActiveGovernment;
            rhsActiveGovernment = that.isActiveGovernment();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "activeGovernment", lhsActiveGovernment), LocatorUtils.property(thatLocator, "activeGovernment", rhsActiveGovernment), lhsActiveGovernment, rhsActiveGovernment)) {
                return false;
            }
        }
        {
            boolean lhsActiveCommittee;
            lhsActiveCommittee = this.isActiveCommittee();
            boolean rhsActiveCommittee;
            rhsActiveCommittee = that.isActiveCommittee();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "activeCommittee", lhsActiveCommittee), LocatorUtils.property(thatLocator, "activeCommittee", rhsActiveCommittee), lhsActiveCommittee, rhsActiveCommittee)) {
                return false;
            }
        }
        {
            boolean lhsActiveParliament;
            lhsActiveParliament = this.isActiveParliament();
            boolean rhsActiveParliament;
            rhsActiveParliament = that.isActiveParliament();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "activeParliament", lhsActiveParliament), LocatorUtils.property(thatLocator, "activeParliament", rhsActiveParliament), lhsActiveParliament, rhsActiveParliament)) {
                return false;
            }
        }
        {
            boolean lhsActiveParty;
            lhsActiveParty = this.isActiveParty();
            boolean rhsActiveParty;
            rhsActiveParty = that.isActiveParty();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "activeParty", lhsActiveParty), LocatorUtils.property(thatLocator, "activeParty", rhsActiveParty), lhsActiveParty, rhsActiveParty)) {
                return false;
            }
        }
        {
            boolean lhsActiveSpeaker;
            lhsActiveSpeaker = this.isActiveSpeaker();
            boolean rhsActiveSpeaker;
            rhsActiveSpeaker = that.isActiveSpeaker();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "activeSpeaker", lhsActiveSpeaker), LocatorUtils.property(thatLocator, "activeSpeaker", rhsActiveSpeaker), lhsActiveSpeaker, rhsActiveSpeaker)) {
                return false;
            }
        }
        {
            long lhsTotalDaysServedSpeaker;
            lhsTotalDaysServedSpeaker = this.getTotalDaysServedSpeaker();
            long rhsTotalDaysServedSpeaker;
            rhsTotalDaysServedSpeaker = that.getTotalDaysServedSpeaker();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "totalDaysServedSpeaker", lhsTotalDaysServedSpeaker), LocatorUtils.property(thatLocator, "totalDaysServedSpeaker", rhsTotalDaysServedSpeaker), lhsTotalDaysServedSpeaker, rhsTotalDaysServedSpeaker)) {
                return false;
            }
        }
        {
            long lhsTotalDaysServedParty;
            lhsTotalDaysServedParty = this.getTotalDaysServedParty();
            long rhsTotalDaysServedParty;
            rhsTotalDaysServedParty = that.getTotalDaysServedParty();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "totalDaysServedParty", lhsTotalDaysServedParty), LocatorUtils.property(thatLocator, "totalDaysServedParty", rhsTotalDaysServedParty), lhsTotalDaysServedParty, rhsTotalDaysServedParty)) {
                return false;
            }
        }
        {
            long lhsTotalPartyAssignments;
            lhsTotalPartyAssignments = this.getTotalPartyAssignments();
            long rhsTotalPartyAssignments;
            rhsTotalPartyAssignments = that.getTotalPartyAssignments();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "totalPartyAssignments", lhsTotalPartyAssignments), LocatorUtils.property(thatLocator, "totalPartyAssignments", rhsTotalPartyAssignments), lhsTotalPartyAssignments, rhsTotalPartyAssignments)) {
                return false;
            }
        }
        {
            long lhsTotalMinistryAssignments;
            lhsTotalMinistryAssignments = this.getTotalMinistryAssignments();
            long rhsTotalMinistryAssignments;
            rhsTotalMinistryAssignments = that.getTotalMinistryAssignments();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "totalMinistryAssignments", lhsTotalMinistryAssignments), LocatorUtils.property(thatLocator, "totalMinistryAssignments", rhsTotalMinistryAssignments), lhsTotalMinistryAssignments, rhsTotalMinistryAssignments)) {
                return false;
            }
        }
        {
            long lhsTotalCommitteeAssignments;
            lhsTotalCommitteeAssignments = this.getTotalCommitteeAssignments();
            long rhsTotalCommitteeAssignments;
            rhsTotalCommitteeAssignments = that.getTotalCommitteeAssignments();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "totalCommitteeAssignments", lhsTotalCommitteeAssignments), LocatorUtils.property(thatLocator, "totalCommitteeAssignments", rhsTotalCommitteeAssignments), lhsTotalCommitteeAssignments, rhsTotalCommitteeAssignments)) {
                return false;
            }
        }
        {
            long lhsTotalSpeakerAssignments;
            lhsTotalSpeakerAssignments = this.getTotalSpeakerAssignments();
            long rhsTotalSpeakerAssignments;
            rhsTotalSpeakerAssignments = that.getTotalSpeakerAssignments();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "totalSpeakerAssignments", lhsTotalSpeakerAssignments), LocatorUtils.property(thatLocator, "totalSpeakerAssignments", rhsTotalSpeakerAssignments), lhsTotalSpeakerAssignments, rhsTotalSpeakerAssignments)) {
                return false;
            }
        }
        {
            long lhsCurrentPartyAssignments;
            lhsCurrentPartyAssignments = this.getCurrentPartyAssignments();
            long rhsCurrentPartyAssignments;
            rhsCurrentPartyAssignments = that.getCurrentPartyAssignments();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "currentPartyAssignments", lhsCurrentPartyAssignments), LocatorUtils.property(thatLocator, "currentPartyAssignments", rhsCurrentPartyAssignments), lhsCurrentPartyAssignments, rhsCurrentPartyAssignments)) {
                return false;
            }
        }
        {
            long lhsCurrentMinistryAssignments;
            lhsCurrentMinistryAssignments = this.getCurrentMinistryAssignments();
            long rhsCurrentMinistryAssignments;
            rhsCurrentMinistryAssignments = that.getCurrentMinistryAssignments();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "currentMinistryAssignments", lhsCurrentMinistryAssignments), LocatorUtils.property(thatLocator, "currentMinistryAssignments", rhsCurrentMinistryAssignments), lhsCurrentMinistryAssignments, rhsCurrentMinistryAssignments)) {
                return false;
            }
        }
        {
            long lhsCurrentCommitteeAssignments;
            lhsCurrentCommitteeAssignments = this.getCurrentCommitteeAssignments();
            long rhsCurrentCommitteeAssignments;
            rhsCurrentCommitteeAssignments = that.getCurrentCommitteeAssignments();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "currentCommitteeAssignments", lhsCurrentCommitteeAssignments), LocatorUtils.property(thatLocator, "currentCommitteeAssignments", rhsCurrentCommitteeAssignments), lhsCurrentCommitteeAssignments, rhsCurrentCommitteeAssignments)) {
                return false;
            }
        }
        {
            long lhsCurrentSpeakerAssignments;
            lhsCurrentSpeakerAssignments = this.getCurrentSpeakerAssignments();
            long rhsCurrentSpeakerAssignments;
            rhsCurrentSpeakerAssignments = that.getCurrentSpeakerAssignments();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "currentSpeakerAssignments", lhsCurrentSpeakerAssignments), LocatorUtils.property(thatLocator, "currentSpeakerAssignments", rhsCurrentSpeakerAssignments), lhsCurrentSpeakerAssignments, rhsCurrentSpeakerAssignments)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String thePersonId;
            thePersonId = this.getPersonId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "personId", thePersonId), currentHashCode, thePersonId);
        }
        {
            String theFirstName;
            theFirstName = this.getFirstName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "firstName", theFirstName), currentHashCode, theFirstName);
        }
        {
            String theLastName;
            theLastName = this.getLastName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "lastName", theLastName), currentHashCode, theLastName);
        }
        {
            String theParty;
            theParty = this.getParty();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "party", theParty), currentHashCode, theParty);
        }
        {
            String theGender;
            theGender = this.getGender();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "gender", theGender), currentHashCode, theGender);
        }
        {
            int theBornYear;
            theBornYear = this.getBornYear();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "bornYear", theBornYear), currentHashCode, theBornYear);
        }
        {
            long theTotalAssignments;
            theTotalAssignments = this.getTotalAssignments();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "totalAssignments", theTotalAssignments), currentHashCode, theTotalAssignments);
        }
        {
            long theCurrentAssignments;
            theCurrentAssignments = this.getCurrentAssignments();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "currentAssignments", theCurrentAssignments), currentHashCode, theCurrentAssignments);
        }
        {
            Date theFirstAssignmentDate;
            theFirstAssignmentDate = this.getFirstAssignmentDate();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "firstAssignmentDate", theFirstAssignmentDate), currentHashCode, theFirstAssignmentDate);
        }
        {
            Date theLastAssignmentDate;
            theLastAssignmentDate = this.getLastAssignmentDate();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "lastAssignmentDate", theLastAssignmentDate), currentHashCode, theLastAssignmentDate);
        }
        {
            long theTotalDaysServed;
            theTotalDaysServed = this.getTotalDaysServed();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "totalDaysServed", theTotalDaysServed), currentHashCode, theTotalDaysServed);
        }
        {
            long theTotalDaysServedParliament;
            theTotalDaysServedParliament = this.getTotalDaysServedParliament();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "totalDaysServedParliament", theTotalDaysServedParliament), currentHashCode, theTotalDaysServedParliament);
        }
        {
            long theTotalDaysServedCommittee;
            theTotalDaysServedCommittee = this.getTotalDaysServedCommittee();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "totalDaysServedCommittee", theTotalDaysServedCommittee), currentHashCode, theTotalDaysServedCommittee);
        }
        {
            long theTotalDaysServedGovernment;
            theTotalDaysServedGovernment = this.getTotalDaysServedGovernment();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "totalDaysServedGovernment", theTotalDaysServedGovernment), currentHashCode, theTotalDaysServedGovernment);
        }
        {
            long theTotalDaysServedEu;
            theTotalDaysServedEu = this.getTotalDaysServedEu();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "totalDaysServedEu", theTotalDaysServedEu), currentHashCode, theTotalDaysServedEu);
        }
        {
            boolean theActive;
            theActive = this.isActive();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "active", theActive), currentHashCode, theActive);
        }
        {
            boolean theActiveEu;
            theActiveEu = this.isActiveEu();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "activeEu", theActiveEu), currentHashCode, theActiveEu);
        }
        {
            boolean theActiveGovernment;
            theActiveGovernment = this.isActiveGovernment();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "activeGovernment", theActiveGovernment), currentHashCode, theActiveGovernment);
        }
        {
            boolean theActiveCommittee;
            theActiveCommittee = this.isActiveCommittee();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "activeCommittee", theActiveCommittee), currentHashCode, theActiveCommittee);
        }
        {
            boolean theActiveParliament;
            theActiveParliament = this.isActiveParliament();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "activeParliament", theActiveParliament), currentHashCode, theActiveParliament);
        }
        {
            boolean theActiveParty;
            theActiveParty = this.isActiveParty();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "activeParty", theActiveParty), currentHashCode, theActiveParty);
        }
        {
            boolean theActiveSpeaker;
            theActiveSpeaker = this.isActiveSpeaker();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "activeSpeaker", theActiveSpeaker), currentHashCode, theActiveSpeaker);
        }
        {
            long theTotalDaysServedSpeaker;
            theTotalDaysServedSpeaker = this.getTotalDaysServedSpeaker();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "totalDaysServedSpeaker", theTotalDaysServedSpeaker), currentHashCode, theTotalDaysServedSpeaker);
        }
        {
            long theTotalDaysServedParty;
            theTotalDaysServedParty = this.getTotalDaysServedParty();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "totalDaysServedParty", theTotalDaysServedParty), currentHashCode, theTotalDaysServedParty);
        }
        {
            long theTotalPartyAssignments;
            theTotalPartyAssignments = this.getTotalPartyAssignments();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "totalPartyAssignments", theTotalPartyAssignments), currentHashCode, theTotalPartyAssignments);
        }
        {
            long theTotalMinistryAssignments;
            theTotalMinistryAssignments = this.getTotalMinistryAssignments();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "totalMinistryAssignments", theTotalMinistryAssignments), currentHashCode, theTotalMinistryAssignments);
        }
        {
            long theTotalCommitteeAssignments;
            theTotalCommitteeAssignments = this.getTotalCommitteeAssignments();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "totalCommitteeAssignments", theTotalCommitteeAssignments), currentHashCode, theTotalCommitteeAssignments);
        }
        {
            long theTotalSpeakerAssignments;
            theTotalSpeakerAssignments = this.getTotalSpeakerAssignments();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "totalSpeakerAssignments", theTotalSpeakerAssignments), currentHashCode, theTotalSpeakerAssignments);
        }
        {
            long theCurrentPartyAssignments;
            theCurrentPartyAssignments = this.getCurrentPartyAssignments();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "currentPartyAssignments", theCurrentPartyAssignments), currentHashCode, theCurrentPartyAssignments);
        }
        {
            long theCurrentMinistryAssignments;
            theCurrentMinistryAssignments = this.getCurrentMinistryAssignments();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "currentMinistryAssignments", theCurrentMinistryAssignments), currentHashCode, theCurrentMinistryAssignments);
        }
        {
            long theCurrentCommitteeAssignments;
            theCurrentCommitteeAssignments = this.getCurrentCommitteeAssignments();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "currentCommitteeAssignments", theCurrentCommitteeAssignments), currentHashCode, theCurrentCommitteeAssignments);
        }
        {
            long theCurrentSpeakerAssignments;
            theCurrentSpeakerAssignments = this.getCurrentSpeakerAssignments();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "currentSpeakerAssignments", theCurrentSpeakerAssignments), currentHashCode, theCurrentSpeakerAssignments);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
