@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>JmsSender\n<size:10>com.hack23.cia.service.component.agent.impl.common.jms" as com.hack23.cia.service.component.agent.impl.common.jms.JmsSender [[JmsSender.html]] {
        {abstract} +send(Destination, Serializable): void
    }

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
