@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>StreamSourceImplementation\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.pagelinks.impl" as com.hack23.cia.web.impl.ui.application.views.common.pagelinks.impl.StreamSourceImplementation [[StreamSourceImplementation.html]] {
        +StreamSourceImplementation(String)
        +getStream(): InputStream
    }

    interface "<size:14>StreamResource.StreamSource\n<size:10>com.vaadin.server" as com.vaadin.server.StreamResource.StreamSource {
        {abstract} +getStream(): InputStream
    }

    com.vaadin.server.StreamResource.StreamSource <|.. com.hack23.cia.web.impl.ui.application.views.common.pagelinks.impl.StreamSourceImplementation

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
