@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>AdminApplicationEventsPageModContentFactoryImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.admin.system.pagemode" as com.hack23.cia.web.impl.ui.application.views.admin.system.pagemode.AdminApplicationEventsPageModContentFactoryImpl [[AdminApplicationEventsPageModContentFactoryImpl.html]] {
        {static} +NAME: String
        +matches(String, String): boolean
        +createContent(String, MenuBar, Panel): Layout
    }

    abstract class "<size:14>AbstractAdminSystemPageModContentFactoryImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.admin.system.pagemode" as com.hack23.cia.web.impl.ui.application.views.admin.system.pagemode.AbstractAdminSystemPageModContentFactoryImpl [[AbstractAdminSystemPageModContentFactoryImpl.html]]

    com.hack23.cia.web.impl.ui.application.views.admin.system.pagemode.AbstractAdminSystemPageModContentFactoryImpl <|-- com.hack23.cia.web.impl.ui.application.views.admin.system.pagemode.AdminApplicationEventsPageModContentFactoryImpl

    center footer UMLDoclet 2.0.3, PlantUML 1.2019.06
@enduml
