package com.hack23.cia.service.impl.rules

import org.kie.api.runtime.KieRuntime

import com.hack23.cia.model.internal.application.data.party.impl.ViewRiksdagenPartySummary
import com.hack23.cia.service.api.action.kpi.Status
import com.hack23.cia.service.impl.rules.PartyComplianceCheckImpl
import com.hack23.cia.service.api.action.kpi.ComplianceCheck

rule "We have an active Party with no government experience"
	dialect "java"
    when
        $p : PartyComplianceCheckImpl( party.active == true && party.totalDaysServedGovernment == 0 )
    then
    	$p.addViolation( Status.MINOR, kcontext.getRule().getName());
end