package com.hack23.cia.service.impl.rules

import org.kie.api.runtime.KieRuntime

import com.hack23.cia.model.internal.application.data.party.impl.ViewRiksdagenPartySummary
import com.hack23.cia.model.internal.application.data.committee.impl.ViewRiksdagenVoteDataBallotPartySummaryDaily
import com.hack23.cia.model.internal.application.data.committee.impl.ViewRiksdagenVoteDataBallotPartySummaryMonthly
import com.hack23.cia.model.internal.application.data.committee.impl.ViewRiksdagenVoteDataBallotPartySummaryAnnual
import com.hack23.cia.service.api.action.kpi.Status
import com.hack23.cia.service.impl.rules.PartyComplianceCheckImpl
import com.hack23.cia.service.api.action.kpi.ComplianceCheck

rule "We have a lazy party, absent 15 % last day of ballots in parliament"
	dialect "java"
	salience 10
    when
        $p : PartyComplianceCheckImpl(party.activeParliament && party.party != "-" && dailySummary != null && dailySummary.partyPercentageAbsent >= 15)
    then
    	$p.addViolation( Status.MINOR, "PartyLazy","Behavior", kcontext.getRule().getName(),"NA");
end

rule "We have a lazy party, absent more than 15 % of ballots last month"
	dialect "java"
	salience 50
    when
        $p : PartyComplianceCheckImpl( party.activeParliament && party.party != "-" && monthlySummary != null && monthlySummary.partyPercentageAbsent >= 15)
    then
    	$p.addViolation( Status.MAJOR, "PartyLazy","Behavior", kcontext.getRule().getName(),"NA");
end

rule "We have a lazy party, absent more than 15 % of ballots last year"
	dialect "java"
	salience 100
    when
        $p : PartyComplianceCheckImpl( party.activeParliament && party.party != "-" && annualSummary != null && annualSummary.partyPercentageAbsent >= 15)
    then
    	$p.addViolation( Status.CRITICAL, "PartyLazy","Behavior", kcontext.getRule().getName(),"NA");
end
