@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>DocumentChartDataManagerImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.DocumentChartDataManagerImpl [[DocumentChartDataManagerImpl.html]] {
        +createDocumentTypeChart(AbstractOrderedLayout): void
    }

    abstract class "<size:14>AbstractChartDataManagerImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.AbstractChartDataManagerImpl [[AbstractChartDataManagerImpl.html]]
    interface "<size:14>DocumentChartDataManager\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api.DocumentChartDataManager [[../api/DocumentChartDataManager.html]] {
        {abstract} +createDocumentTypeChart(AbstractOrderedLayout): void
    }

    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.AbstractChartDataManagerImpl <|-- com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.DocumentChartDataManagerImpl
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api.DocumentChartDataManager <|.. com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.DocumentChartDataManagerImpl

    center footer UMLDoclet 2.0.3, PlantUML 1.2019.06
@enduml
