@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>PartyChartDataManagerImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.PartyChartDataManagerImpl [[PartyChartDataManagerImpl.html]] {
        +createPartyAgeChart(AbstractOrderedLayout): void
        +createPartyGenderChart(AbstractOrderedLayout): void
        +createPartyLineChart(AbstractOrderedLayout, String): void
        +createPartyWinnerChart(AbstractOrderedLayout): void
    }

    abstract class "<size:14>AbstractChartDataManagerImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.AbstractChartDataManagerImpl [[AbstractChartDataManagerImpl.html]]
    interface "<size:14>PartyChartDataManager\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api.PartyChartDataManager [[../api/PartyChartDataManager.html]] {
        {abstract} +createPartyAgeChart(AbstractOrderedLayout): void
        {abstract} +createPartyGenderChart(AbstractOrderedLayout): void
        {abstract} +createPartyLineChart(AbstractOrderedLayout, String): void
        {abstract} +createPartyWinnerChart(AbstractOrderedLayout): void
    }

    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.AbstractChartDataManagerImpl <|-- com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.PartyChartDataManagerImpl
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api.PartyChartDataManager <|.. com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.PartyChartDataManagerImpl

    center footer UMLDoclet 2.0.7, PlantUML 1.2019.12
@enduml
