@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>PoliticianDataManagerImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.PoliticianDataManagerImpl [[PoliticianDataManagerImpl.html]] {
        +createPersonLineChart(AbstractOrderedLayout, String): void
    }

    abstract class "<size:14>AbstractChartDataManagerImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.AbstractChartDataManagerImpl [[AbstractChartDataManagerImpl.html]]
    interface "<size:14>PoliticianChartDataManager\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api.PoliticianChartDataManager [[../api/PoliticianChartDataManager.html]] {
        {abstract} +createPersonLineChart(AbstractOrderedLayout, String): void
    }

    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.AbstractChartDataManagerImpl <|-- com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.PoliticianDataManagerImpl
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api.PoliticianChartDataManager <|.. com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.PoliticianDataManagerImpl

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
