@startuml
    namespace com.hack23.cia.web.impl.ui.application.views.user.goverment {

        class MinistryView [[MinistryView.html]] {
            {static} +NAME: String
            +MinistryView(ApplicationContext)
        }

        class MinistryRankingView [[MinistryRankingView.html]] {
            {static} +NAME: String
            +MinistryRankingView(ApplicationContext)
        }

        com.hack23.cia.web.impl.ui.application.views.user.common.AbstractGroupView <|-- MinistryView
        com.hack23.cia.web.impl.ui.application.views.user.common.AbstractRankingView <|-- MinistryRankingView
    }

    namespace com.hack23.cia.web.impl.ui.application.views.user.common {
        abstract class AbstractGroupView [[../common/AbstractGroupView.html]] {
        }
        abstract class AbstractRankingView [[../common/AbstractRankingView.html]] {
        }
    }

    center footer UMLDoclet 2.0.7, PlantUML 1.2019.12
@enduml
