@startuml(id="Web")
title Citizen Intelligence Agency System - Web Application - Components
caption "Web"

skinparam {
  shadowing false
  arrowColor #707070
  actorBorderColor #707070
  componentBorderColor #707070
  rectangleBorderColor #707070
  noteBackgroundColor #ffffff
  noteBorderColor #707070
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
package "Web Application" <<Container: Jetty/Java>> {
}
@enduml