@startuml(id="System_context")
scale max 16384x16384
title Citizen Intelligence Agency System - System Context
caption "System context"

skinparam {
  shadowing false
  arrowColor #707070
  actorBorderColor #707070
  componentBorderColor #707070
  rectangleBorderColor #707070
  noteBackgroundColor #ffffff
  noteBorderColor #707070
}
actor "Admin" <<Person>> as 2 #519823
note right of 2
  Manager of the system
end note
rectangle 3 <<Software System>> #1168bd [
  Citizen Intelligence Agency System
  --
  Tracking politicians like
  bugs!
]
actor "User" <<Person>> as 1 #519823
note right of 1
  User of the system
end note
rectangle 4 <<Software System>> #1168bd [
  data.riksdagen.se
  --
  Public API Swedish Parliament
  data
]
rectangle 5 <<Software System>> #1168bd [
  data.worldbank.org
  --
  Public API Country indicators
]
rectangle 7 <<Software System>> #1168bd [
  www.esv.se
  --
  Public Data Swedish public
  sector spending data
]
rectangle 6 <<Software System>> #1168bd [
  www.val.se
  --
  Public API Swedish Election
  data
]
2 .[#707070].> 3 : Manages
3 .[#707070].> 4 : Loads data
3 .[#707070].> 5 : Loads data
3 .[#707070].> 7 : Loads data
3 .[#707070].> 6 : Loads data
1 .[#707070].> 3 : Uses
@enduml