@startuml(id="Web")
scale max 16384x16384
title Citizen Intelligence Agency System - Web Application - Components
caption "Web"

skinparam {
  shadowing false
  arrowColor #707070
  actorBorderColor #707070
  componentBorderColor #707070
  rectangleBorderColor #707070
  noteBackgroundColor #ffffff
  noteBorderColor #707070
}
package "Web Application" <<Container>> {
  component "AdminChartDataManager" <<Spring Service>> as 10 #1168bd
  component "AgentContainer" <<Spring Component>> as 57 #1168bd
  component "ApplicationManager" <<Spring Service>> as 33 #1168bd
  component "ApplicationMenuItemFactory" <<Spring Service>> as 13 #1168bd
  component "AuthenticationProvider" <<Spring Component>> as 63 #1168bd
  component "BallotChartDataManager" <<Spring Service>> as 26 #1168bd
  component "BallotMenuItemFactory" <<Spring Service>> as 46 #1168bd
  component "BootstrapDefaultConfig" <<Spring Component>> as 59 #1168bd
  component "ChartDataManager" <<Spring Service>> as 20 #1168bd
  component "ChartOptions" <<Spring Component>> as 64 #1168bd
  component "CommitteeDataSeriesFactory" <<Spring Service>> as 54 #1168bd
  component "CommitteeGhantChartManager" <<Spring Service>> as 47 #1168bd
  component "CommitteeMenuItemFactory" <<Spring Service>> as 44 #1168bd
  component "CommitteeRankingMenuItemFactory" <<Spring Service>> as 23 #1168bd
  component "ConfigurationManager" <<Spring Service>> as 35 #1168bd
  component "CountryMenuItemFactory" <<Spring Service>> as 53 #1168bd
  component "DecisionChartDataManager" <<Spring Service>> as 19 #1168bd
  component "DecisionDataFactory" <<Spring Service>> as 37 #1168bd
  component "DecisionFlowChartManager" <<Spring Service>> as 25 #1168bd
  component "DocumentChartDataManager" <<Spring Service>> as 12 #1168bd
  component "DocumentMenuItemFactory" <<Spring Service>> as 50 #1168bd
  component "FormFactory" <<Spring Service>> as 15 #1168bd
  component "GovernmentBodyChartDataManager" <<Spring Service>> as 21 #1168bd
  component "GovernmentBodyMenuItemFactory" <<Spring Service>> as 56 #1168bd
  component "GovernmentBodyRankingMenuItemFactory" <<Spring Service>> as 18 #1168bd
  component "GovernmentOutcomeChartDataManager" <<Spring Service>> as 22 #1168bd
  component "GridFactory" <<Spring Service>> as 17 #1168bd
  component "MainView" <<Spring Service>> as 38 #1168bd
  component "MainViewLoginPageModContentFactoryImpl" <<Spring Component>> as 62 #1168bd
  component "MainViewOverviewPageModContentFactoryImpl" <<Spring Component>> as 58 #1168bd
  component "MainViewPageVisitHistoryPageModContentFactoryImpl" <<Spring Component>> as 67 #1168bd
  component "MainViewRegisterPageModContentFactoryImpl" <<Spring Component>> as 61 #1168bd
  component "MinistryDataSeriesFactory" <<Spring Service>> as 24 #1168bd
  component "MinistryGhantChartManager" <<Spring Service>> as 14 #1168bd
  component "MinistryMenuItemFactory" <<Spring Service>> as 28 #1168bd
  component "MinistryRankingMenuItemFactory" <<Spring Service>> as 39 #1168bd
  component "OrgDocumentChartDataManager" <<Spring Service>> as 11 #1168bd
  component "PageActionEventHelper" <<Spring Service>> as 29 #1168bd
  component "PagingUtil" <<Spring Component>> as 66 #1168bd
  component "ParliamentMenuItemFactory" <<Spring Service>> as 30 #1168bd
  component "PartyChartDataManager" <<Spring Service>> as 51 #1168bd
  component "PartyDataSeriesFactory" <<Spring Service>> as 16 #1168bd
  component "PartyDocumentChartDataManager" <<Spring Service>> as 34 #1168bd
  component "PartyGhantChartManager" <<Spring Service>> as 41 #1168bd
  component "PartyMenuItemFactory" <<Spring Service>> as 48 #1168bd
  component "PartyRankingMenuItemFactory" <<Spring Service>> as 31 #1168bd
  component "PersonDocumentChartDataManager" <<Spring Service>> as 40 #1168bd
  component "PoliticianDataManagerImpl" <<Spring Service>> as 52 #1168bd
  component "PoliticianGhantChartManager" <<Spring Service>> as 36 #1168bd
  component "PoliticianMenuItemFactory" <<Spring Service>> as 32 #1168bd
  component "PoliticianRankingMenuItemFactory" <<Spring Service>> as 43 #1168bd
  component "UserHomeMenuItemFactory" <<Spring Service>> as 45 #1168bd
  component "ViewDataDataContainerFactory" <<Spring Component>> as 65 #1168bd
  component "ViewRiksdagenCommitteeDataContainer" <<Spring Component>> as 60 #1168bd
  component "ViewRiksdagenVoteDataBallotPartySummaryChartDataManagerImpl" <<Spring Service>> as 42 #1168bd
  component "ViewRiksdagenVoteDataBallotPoliticianSummaryChartDataManagerImpl" <<Spring Service>> as 55 #1168bd
  component "ViewRiksdagenVoteDataBallotPoliticianSummaryDailyChartDataManagerImpl" <<Spring Service>> as 49 #1168bd
  component "WorldIndicatorChartDataManager" <<Spring Service>> as 27 #1168bd
}
10 .[#707070].> 33 
10 .[#707070].> 64 
33 .[#707070].> 57 
33 .[#707070].> 65 
13 .[#707070].> 23 
13 .[#707070].> 53 
13 .[#707070].> 18 
13 .[#707070].> 39 
13 .[#707070].> 30 
13 .[#707070].> 31 
13 .[#707070].> 43 
26 .[#707070].> 33 
26 .[#707070].> 64 
59 .[#707070].> 35 
20 .[#707070].> 33 
20 .[#707070].> 64 
54 .[#707070].> 33 
44 .[#707070].> 13 
44 .[#707070].> 23 
23 .[#707070].> 13 
53 .[#707070].> 33 
53 .[#707070].> 13 
19 .[#707070].> 33 
19 .[#707070].> 64 
37 .[#707070].> 33 
25 .[#707070].> 37 
12 .[#707070].> 33 
12 .[#707070].> 64 
50 .[#707070].> 13 
21 .[#707070].> 33 
21 .[#707070].> 64 
56 .[#707070].> 13 
56 .[#707070].> 18 
18 .[#707070].> 13 
22 .[#707070].> 33 
22 .[#707070].> 64 
38 .[#707070].> 33 
38 .[#707070].> 13 
62 .[#707070].> 10 
62 .[#707070].> 33 
62 .[#707070].> 13 
62 .[#707070].> 15 
62 .[#707070].> 17 
62 .[#707070].> 29 
58 .[#707070].> 10 
58 .[#707070].> 33 
58 .[#707070].> 13 
58 .[#707070].> 15 
58 .[#707070].> 17 
58 .[#707070].> 29 
38 .[#707070].> 29 
67 .[#707070].> 10 
67 .[#707070].> 33 
67 .[#707070].> 13 
67 .[#707070].> 15 
67 .[#707070].> 17 
67 .[#707070].> 29 
61 .[#707070].> 10 
61 .[#707070].> 33 
61 .[#707070].> 13 
61 .[#707070].> 15 
61 .[#707070].> 17 
61 .[#707070].> 29 
24 .[#707070].> 33 
28 .[#707070].> 13 
28 .[#707070].> 39 
39 .[#707070].> 13 
11 .[#707070].> 33 
11 .[#707070].> 64 
29 .[#707070].> 33 
30 .[#707070].> 13 
51 .[#707070].> 33 
51 .[#707070].> 64 
16 .[#707070].> 33 
34 .[#707070].> 33 
34 .[#707070].> 64 
48 .[#707070].> 13 
48 .[#707070].> 31 
31 .[#707070].> 13 
40 .[#707070].> 33 
40 .[#707070].> 64 
52 .[#707070].> 33 
52 .[#707070].> 64 
32 .[#707070].> 13 
32 .[#707070].> 43 
43 .[#707070].> 13 
45 .[#707070].> 13 
42 .[#707070].> 33 
55 .[#707070].> 33 
49 .[#707070].> 33 
27 .[#707070].> 33 
27 .[#707070].> 64 
@enduml