@startuml(id="Production_Aws_Account_structure")
title Citizen Intelligence Agency - Deployment - Default
caption "Production Aws Account structure"

skinparam {
  shadowing false
  arrowColor #707070
  actorBorderColor #707070
  componentBorderColor #707070
  rectangleBorderColor #707070
  noteBackgroundColor #ffffff
  noteBorderColor #707070
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
node "Application Account" <<Deployment Node: Aws Account>> as 12 {
  rectangle 34 <<Container: Aws Account>> #1168bd [
    Application Account
    --
    AWS
  ]
}
node "Audit Account" <<Deployment Node: Aws Account>> as 10 {
  rectangle 30 <<Container: Aws Account>> #1168bd [
    Audit Account
    --
    AWS
  ]
}
node "Development Account" <<Deployment Node: Aws Account>> as 6 {
  rectangle 29 <<Container: Aws Account>> #1168bd [
    Development Account
    --
    AWS
  ]
}
node "IAM Account" <<Deployment Node: Aws Account>> as 4 {
  rectangle 36 <<Container: Aws Account>> #1168bd [
    IAM Account
    --
    AWS
  ]
}
node "Master Account" <<Deployment Node: Aws Account>> as 2 {
  rectangle 41 <<Container: Aws Account>> #1168bd [
    Master Account
    --
    AWS
  ]
}
node "Operation Center Account" <<Deployment Node: Aws Account>> as 8 {
  rectangle 28 <<Container: Aws Account>> #1168bd [
    Operation Center Account
    --
    AWS
  ]
}
34 .[#707070].> 30 : publish event/audit
29 .[#707070].> 30 : publish event/audit
36 .[#707070].> 34 : manage access
36 .[#707070].> 30 : publish event/audit
36 .[#707070].> 29 : manage access
36 .[#707070].> 28 : manage access
41 .[#707070].> 34 : create/restrict
41 .[#707070].> 30 : create/restrict
41 .[#707070].> 30 : publish event/audit
41 .[#707070].> 29 : create/restrict
41 .[#707070].> 36 : create/restrict
41 .[#707070].> 28 : create/restrict
28 .[#707070].> 30 : publish event/audit
28 .[#707070].> 30 : Monitor event/audit
@enduml