@startuml(id="Deployment")
scale max 16384x16384
title Citizen Intelligence Agency System - Deployment
caption "Deployment Aws."

skinparam {
  shadowing false
  arrowColor #707070
  actorBorderColor #707070
  componentBorderColor #707070
  rectangleBorderColor #707070
  noteBackgroundColor #ffffff
  noteBorderColor #707070
}
node "AppOrg Account" <<Aws Account>> as 169 {
  node "Project Network" <<VPC>> as 170 {
    node "Database (x2)" <<RDS>> as 222 {
      database "Database" <<Container>> as 223 #1168bd
    }
    node "Application (x2)" <<EC2>> as 214 {
      node "Jetty" <<JVM>> as 215 {
        rectangle "Web Application" <<Container>> as 216 #1168bd
      }
    }
  }
  node "Business analytics" <<QuickSight>> as 187 {
    rectangle "Dashboards" <<Container>> as 189 #1168bd
  }
  node "Patch Compliance" <<System Mananger>> as 183 {
    rectangle "InventoryList" <<Container>> as 185 #1168bd
  }
  node "System Compliance checks" <<Inspector>> as 179 {
    rectangle "ScanningRules" <<Container>> as 181 #1168bd
  }
  node "Application Loadbalancer" <<ALB>> as 209 {
    rectangle "Loadbalancer" <<Container>> as 210 #1168bd
  }
  node "Web Application Firewall" <<WAF>> as 171 {
    rectangle "WebACL Rules" <<Container>> as 173 #1168bd
  }
}
node "Audit Account" <<Aws Account>> as 175 {
  node "Audit" <<Cloudtrail>> as 202 {
    rectangle "LogBucket" <<Container>> as 204 #1168bd
  }
  node "Guard Duty" <<GuardDuty>> as 191 {
    rectangle "Intelligent threat detection and continuous monitoring" <<Container>> as 193 #1168bd
  }
  node "LogGroup" <<Cloudwatch>> as 197 {
    rectangle "Logstreams" <<Container>> as 199 #1168bd
  }
  node "Config" <<Config>> as 176 {
    rectangle "Rules" <<Container>> as 178 #1168bd
  }
  node "A machine learning-powered security" <<macie>> as 194 {
    rectangle "discover, classify, and protect sensitive data" <<Container>> as 196 #1168bd
  }
  node "Access Logs" <<S3>> as 205 {
    rectangle "AccessLogBucket" <<Container>> as 207 #1168bd
  }
}
node "Dev Network" <<Dev Network>> as 233 {
  rectangle "Nexus" <<Container>> as 235 #1168bd
  rectangle "Jenkins" <<Container>> as 243 #1168bd
  rectangle "Sonarqube" <<Container>> as 237 #1168bd
}
node "Github Org" <<Github Org>> as 228 {
  rectangle "SCM" <<Container>> as 230 #1168bd
  rectangle "Documentation" <<Container>> as 232 #1168bd
}
node "Security Account" <<Sumologic Account>> as 248 {
  node "AWS Account Security Dashboard" <<AWS Account Security Dashboard>> as 251 {
    rectangle "AwsConfigLogs" <<Container>> as 263 #1168bd
    rectangle "CloudTrailLogs" <<Container>> as 259 #1168bd
  }
  node "Server Security Dashboard" <<Server Security Dashboard>> as 250 {
    rectangle "Ec2SystemLogs" <<Container>> as 267 #1168bd
    rectangle "AwsInspectorResults" <<Container>> as 275 #1168bd
  }
  node "Nework Security Dashboard" <<Nework Security Dashboard>> as 249 {
    rectangle "VpcFlowLogs" <<Container>> as 255 #1168bd
    rectangle "AwsLoadbalancerAccessLogs" <<Container>> as 279 #1168bd
  }
  node "Application Security Dashboard" <<Application Security Dashboard>> as 252 {
    rectangle "Ec2ApplicationLogs" <<Container>> as 271 #1168bd
  }
}
209 .[#707070].> 214 : <<https>>\nUses
214 .[#707070].> 222 : <<jdbc>>\nUses
171 .[#707070].> 209 : <<filter rules>>\nProtects
173 .[#707070].> 210 : Protects/Filter
210 .[#707070].> 207 : Write logs
181 .[#707070].> 216 : Inspects
263 .[#707070].> 178 : Recieve logs
255 .[#707070].> 199 : Recieve logs
243 .[#707070].> 230 : builds
243 .[#707070].> 237 : <<https>>\nPublish QA metrics
275 .[#707070].> 181 : Recieve reports
243 .[#707070].> 232 : <<https>>\npublish Documentation
223 .[#707070].> 199 : Write logs
267 .[#707070].> 199 : Recieve logs
243 .[#707070].> 235 : <<https>>\npublish artifacts
185 .[#707070].> 216 : Run Commands
216 .[#707070].> 223 : JDBC
216 .[#707070].> 199 : Write logs
189 .[#707070].> 223 : Loads Data
210 .[#707070].> 216 : HTTPS/H2
279 .[#707070].> 207 : Recieve logs
259 .[#707070].> 204 : Recieve logs
271 .[#707070].> 199 : Recieve logs
@enduml