@startuml(id="Deployment")
title Citizen Intelligence Agency System - Deployment - Default
caption "Deployment Aws."

skinparam {
  shadowing false
  arrowColor #707070
  actorBorderColor #707070
  componentBorderColor #707070
  rectangleBorderColor #707070
  noteBackgroundColor #ffffff
  noteBorderColor #707070
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
node "AppOrg Account" <<Deployment Node: Aws Account>> as 19 {
  node "Application Loadbalancer" <<Deployment Node: ALB>> as 59 {
    rectangle 60 <<Container: ALB/ELB/Apache/Nginx/HaProxy>> #1168bd [
      Loadbalancer
      --
      Loadbalancer
    ]
  }
  node "Business analytics" <<Deployment Node: QuickSight>> as 37 {
    rectangle 39 <<Container: Dashboards>> #1168bd [
      Dashboards
      --
      AWS
    ]
  }
  node "Patch Compliance" <<Deployment Node: System Mananger>> as 33 {
    rectangle 35 <<Container: InventoryList>> #1168bd [
      InventoryList
      --
      AWS
    ]
  }
  node "Project Network" <<Deployment Node: VPC>> as 20 {
    node "Application (x2)" <<Deployment Node: EC2>> as 64 {
      node "Jetty" <<Deployment Node: JVM>> as 65 {
        rectangle 66 <<Container: Jetty/Java>> #1168bd [
          Web Application
          --
          Web Application
        ]
      }
    }
    node "Database (x2)" <<Deployment Node: RDS>> as 72 {
      database 73 <<Container: Postgresql>> #1168bd [
        Database
        --
        Stores information
      ]
    }
  }
  node "System Compliance checks" <<Deployment Node: Inspector>> as 29 {
    rectangle 31 <<Container: Scanning Rules>> #1168bd [
      ScanningRules
      --
      AWS
    ]
  }
  node "Web Application Firewall" <<Deployment Node: WAF>> as 21 {
    rectangle 23 <<Container: WAF>> #1168bd [
      WebACL Rules
      --
      AWS
    ]
  }
}
node "Audit Account" <<Deployment Node: Aws Account>> as 25 {
  node "A machine learning-powered security" <<Deployment Node: macie>> as 44 {
    rectangle 46 <<Container: discover, classify, and protect sensitive data>> #1168bd [
      discover, classify, and protect sensitive data
      --
      AWS
    ]
  }
  node "Access Logs" <<Deployment Node: S3>> as 55 {
    rectangle 57 <<Container: S3>> #1168bd [
      AccessLogBucket
      --
      AWS
    ]
  }
  node "Audit" <<Deployment Node: Cloudtrail>> as 52 {
    rectangle 54 <<Container: S3>> #1168bd [
      LogBucket
      --
      AWS
    ]
  }
  node "Config" <<Deployment Node: Config>> as 26 {
    rectangle 28 <<Container: Config Rules>> #1168bd [
      Rules
      --
      AWS
    ]
  }
  node "Guard Duty" <<Deployment Node: GuardDuty>> as 41 {
    rectangle 43 <<Container: Intelligent threat detection and continuous monitoring>> #1168bd [
      Intelligent threat detection and continuous monitoring
      --
      AWS
    ]
  }
  node "LogGroup" <<Deployment Node: Cloudwatch>> as 47 {
    rectangle 49 <<Container: LogStream>> #1168bd [
      Logstreams
      --
      AWS
    ]
  }
}
node "Dev Network" <<Deployment Node: Dev Network>> as 83 {
  rectangle 93 <<Container: Jenkins>> #1168bd [
    Jenkins
    --
    Dev
  ]
  rectangle 85 <<Container: Nexus>> #1168bd [
    Nexus
    --
    Dev
  ]
  rectangle 87 <<Container: Sonarqube>> #1168bd [
    Sonarqube
    --
    Dev
  ]
}
node "Github Org" <<Deployment Node: Github Org>> as 78 {
  rectangle 82 <<Container: Documentation>> #1168bd [
    Documentation
    --
    Github
  ]
  rectangle 80 <<Container: Scm>> #1168bd [
    SCM
    --
    Github
  ]
}
node "Security Account" <<Deployment Node: Sumologic Account>> as 98 {
  node "AWS Account Security Dashboard" <<Deployment Node: AWS Account Security Dashboard>> as 101 {
    rectangle 113 <<Container: AwsConfigLogs>> #1168bd [
      AwsConfigLogs
      --
      Sumologic
    ]
    rectangle 109 <<Container: CloudTrailLogs>> #1168bd [
      CloudTrailLogs
      --
      Sumologic
    ]
  }
  node "Application Security Dashboard" <<Deployment Node: Application Security Dashboard>> as 102 {
    rectangle 121 <<Container: Ec2ApplicationLogs>> #1168bd [
      Ec2ApplicationLogs
      --
      Sumologic
    ]
  }
  node "Nework Security Dashboard" <<Deployment Node: Nework Security Dashboard>> as 99 {
    rectangle 129 <<Container: AwsLoadbalancerAccessLogs>> #1168bd [
      AwsLoadbalancerAccessLogs
      --
      Sumologic
    ]
    rectangle 105 <<Container: VpcFlowLogs>> #1168bd [
      VpcFlowLogs
      --
      Sumologic
    ]
  }
  node "Server Security Dashboard" <<Deployment Node: Server Security Dashboard>> as 100 {
    rectangle 125 <<Container: AwsInspectorResults>> #1168bd [
      AwsInspectorResults
      --
      Sumologic
    ]
    rectangle 117 <<Container: Ec2SystemLogs>> #1168bd [
      Ec2SystemLogs
      --
      Sumologic
    ]
  }
}
59 .[#707070].> 64 : <<https>>\nUses
64 .[#707070].> 72 : <<jdbc>>\nUses
113 .[#707070].> 28 : Recieve logs
125 .[#707070].> 31 : Recieve reports
129 .[#707070].> 57 : Recieve logs
109 .[#707070].> 54 : Recieve logs
39 .[#707070].> 73 : Loads Data
73 .[#707070].> 49 : Write logs
121 .[#707070].> 49 : Recieve logs
117 .[#707070].> 49 : Recieve logs
35 .[#707070].> 66 : Run Commands
93 .[#707070].> 82 : <<https>>\npublish Documentation
93 .[#707070].> 85 : <<https>>\npublish artifacts
93 .[#707070].> 80 : builds
93 .[#707070].> 87 : <<https>>\nPublish QA metrics
60 .[#707070].> 57 : Write logs
60 .[#707070].> 66 : HTTPS/H2
31 .[#707070].> 66 : Inspects
105 .[#707070].> 49 : Recieve logs
21 .[#707070].> 59 : <<filter rules>>\nProtects
66 .[#707070].> 73 : JDBC
66 .[#707070].> 49 : Write logs
23 .[#707070].> 60 : Protects/Filter
@enduml