@startuml(id="Production_Aws_Account_structure")
scale max 2000x2000
title Citizen Intelligence Agency - Deployment
caption "Production Aws Account structure"

skinparam {
  shadowing false
  arrowColor #707070
  actorBorderColor #707070
  componentBorderColor #707070
  rectangleBorderColor #707070
  noteBackgroundColor #ffffff
  noteBorderColor #707070
}
node "Application Account" <<Aws Account>> as 12 {
  rectangle "Application Account" <<Container>> as 34 #1168bd
}
node "Audit Account" <<Aws Account>> as 10 {
  rectangle "Audit Account" <<Container>> as 30 #1168bd
}
node "Development Account" <<Aws Account>> as 6 {
  rectangle "Development Account" <<Container>> as 29 #1168bd
}
node "IAM Account" <<Aws Account>> as 4 {
  rectangle "IAM Account" <<Container>> as 36 #1168bd
}
node "Master Account" <<Aws Account>> as 2 {
  rectangle "Master Account" <<Container>> as 41 #1168bd
}
node "Operation Center Account" <<Aws Account>> as 8 {
  rectangle "Operation Center Account" <<Container>> as 28 #1168bd
}
36 .[#707070].> 28 : manage access
41 .[#707070].> 30 : create/restrict
41 .[#707070].> 30 : publish event/audit
28 .[#707070].> 30 : publish event/audit
29 .[#707070].> 30 : publish event/audit
36 .[#707070].> 30 : publish event/audit
34 .[#707070].> 30 : publish event/audit
28 .[#707070].> 30 : Monitor event/audit
41 .[#707070].> 36 : create/restrict
41 .[#707070].> 34 : create/restrict
41 .[#707070].> 29 : create/restrict
41 .[#707070].> 28 : create/restrict
36 .[#707070].> 34 : manage access
36 .[#707070].> 29 : manage access
@enduml