@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>MinistryDocumentHistoryPageModContentFactoryImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.user.goverment.pagemode" as com.hack23.cia.web.impl.ui.application.views.user.goverment.pagemode.MinistryDocumentHistoryPageModContentFactoryImpl [[MinistryDocumentHistoryPageModContentFactoryImpl.html]] {
        +matches(String, String): boolean
        +createContent(String, MenuBar, Panel): Layout
    }

    abstract class "<size:14>AbstractItemPageModContentFactoryImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.pagemode" as com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractItemPageModContentFactoryImpl<ViewRiksdagenMinistry> [[../../../common/pagemode/AbstractItemPageModContentFactoryImpl.html]] {
        {abstract} #getItem(String): ViewRiksdagenMinistry
    }

    com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractItemPageModContentFactoryImpl <|-- com.hack23.cia.web.impl.ui.application.views.user.goverment.pagemode.MinistryDocumentHistoryPageModContentFactoryImpl

    center footer UMLDoclet 2.0.3, PlantUML 1.2019.06
@enduml
