//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.25 at 12:05:09 AM CET 
//


package com.hack23.cia.model.internal.application.data.impl;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.hack23.cia.model.common.api.ModelObject;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for WorldbankIndicatorDataCountrySummaryEmbeddedId complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WorldbankIndicatorDataCountrySummaryEmbeddedId"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="indicator_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="country_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WorldbankIndicatorDataCountrySummaryEmbeddedId", propOrder = {
    "indicatorId",
    "countryId"
})
@Embeddable
public class WorldbankIndicatorDataCountrySummaryEmbeddedId
    implements Serializable, ModelObject, Equals, HashCode, ToString
{

    @XmlElement(name = "indicator_id", required = true)
    protected String indicatorId;
    @XmlElement(name = "country_id", required = true)
    protected String countryId;

    /**
     * Gets the value of the indicatorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "INDICATOR_ID", length = 255)
    public String getIndicatorId() {
        return indicatorId;
    }

    /**
     * Sets the value of the indicatorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndicatorId(String value) {
        this.indicatorId = value;
    }

    /**
     * Gets the value of the countryId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "COUNTRY_ID", length = 255)
    public String getCountryId() {
        return countryId;
    }

    /**
     * Sets the value of the countryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryId(String value) {
        this.countryId = value;
    }

    public WorldbankIndicatorDataCountrySummaryEmbeddedId withIndicatorId(String value) {
        setIndicatorId(value);
        return this;
    }

    public WorldbankIndicatorDataCountrySummaryEmbeddedId withCountryId(String value) {
        setCountryId(value);
        return this;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theIndicatorId;
            theIndicatorId = this.getIndicatorId();
            strategy.appendField(locator, this, "indicatorId", buffer, theIndicatorId);
        }
        {
            String theCountryId;
            theCountryId = this.getCountryId();
            strategy.appendField(locator, this, "countryId", buffer, theCountryId);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final WorldbankIndicatorDataCountrySummaryEmbeddedId that = ((WorldbankIndicatorDataCountrySummaryEmbeddedId) object);
        {
            String lhsIndicatorId;
            lhsIndicatorId = this.getIndicatorId();
            String rhsIndicatorId;
            rhsIndicatorId = that.getIndicatorId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "indicatorId", lhsIndicatorId), LocatorUtils.property(thatLocator, "indicatorId", rhsIndicatorId), lhsIndicatorId, rhsIndicatorId)) {
                return false;
            }
        }
        {
            String lhsCountryId;
            lhsCountryId = this.getCountryId();
            String rhsCountryId;
            rhsCountryId = that.getCountryId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "countryId", lhsCountryId), LocatorUtils.property(thatLocator, "countryId", rhsCountryId), lhsCountryId, rhsCountryId)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String theIndicatorId;
            theIndicatorId = this.getIndicatorId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "indicatorId", theIndicatorId), currentHashCode, theIndicatorId);
        }
        {
            String theCountryId;
            theCountryId = this.getCountryId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "countryId", theCountryId), currentHashCode, theCountryId);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
