@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ValImportServiceAutoLoadAtStartup\n<size:10>com.hack23.cia.service.component.agent.impl.val" as com.hack23.cia.service.component.agent.impl.val.ValImportServiceAutoLoadAtStartup [[ValImportServiceAutoLoadAtStartup.html]] {
        +autoLoad(): void
    }

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
