@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    enum "<size:14>UserType\n<size:10>com.hack23.cia.model.internal.application.user.impl" as com.hack23.cia.model.internal.application.user.impl.UserType [[UserType.html]] {
        {static} +ANONYMOUS
        {static} +PRIVATE
        {static} +BUSINESS
        +value(): String
        {static} +fromValue(String): UserType
    }

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
