@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    enum "<size:14>UserEmailStatus\n<size:10>com.hack23.cia.model.internal.application.user.impl" as com.hack23.cia.model.internal.application.user.impl.UserEmailStatus [[UserEmailStatus.html]] {
        {static} +VERIFIED
        {static} +UNKNOWN
        +value(): String
        {static} +fromValue(String): UserEmailStatus
    }

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
