@startuml
    namespace com.hack23.cia.web.impl.ui.application.views.common.labelfactory {

        class LabelFactory [[LabelFactory.html]] {
            {static} +createHeader2Label(AbstractOrderedLayout, String): void
        }

    }

    center footer UMLDoclet 2.0.3, PlantUML 1.2019.06
@enduml
