package com.hack23.cia.service.impl.rules
 
import com.hack23.cia.model.internal.application.data.politician.impl.ViewRiksdagenPolitician
import com.hack23.cia.service.api.action.kpi.Status
import com.hack23.cia.service.impl.rules.PoliticianComplianceCheckImpl
import java.util.Date
import java.util.concurrent.TimeUnit

function long busyFactor(Date firstAssignmentDate, long totalDaysServed){
  return ( totalDaysServed / TimeUnit.MILLISECONDS.toDays(new Date().getTime() - firstAssignmentDate.getTime()) );
}

rule "We have an politician with busy schedule, more than 4 current roles and busy past"
	dialect "java"
    when
        $p : PoliticianComplianceCheckImpl( politician.active == true && politician.currentAssignments > 4 && ( busyFactor(politician.firstAssignmentDate, politician.totalDaysServed ) > 4 ))
    then
    	modify( $p ) {
      		setStatus( Status.MINOR )
		}
end

rule "We have an politician with busy schedule, more than 5 current roles and busy past"
	dialect "java"
    when
        $p : PoliticianComplianceCheckImpl( politician.active == true && politician.currentAssignments > 5 && ( busyFactor(politician.firstAssignmentDate, politician.totalDaysServed ) > 5 ))
    then
    	modify( $p ) {
      		setStatus( Status.MAJOR )
		}
end

rule "We have an politician with busy schedule, more than 6 current roles and busy past"
	dialect "java"
    when
        $p : PoliticianComplianceCheckImpl( politician.active == true && politician.currentAssignments > 6 && ( busyFactor(politician.firstAssignmentDate, politician.totalDaysServed ) > 6 ))
    then
    	modify( $p ) {
      		setStatus( Status.CRITICAL )
		}
end
