package com.hack23.cia.service.impl.rules

import org.kie.api.runtime.KieRuntime

import com.hack23.cia.model.internal.application.data.politician.impl.ViewRiksdagenPolitician
import com.hack23.cia.service.api.action.kpi.Status
import com.hack23.cia.service.impl.rules.PoliticianComplianceCheckImpl

rule "We have an politician that left the party still holding assignments"
	dialect "java"
    when
        $p : PoliticianComplianceCheckImpl(politician.party == "-" && politician.active )
    then
    	$p.addViolation( Status.CRITICAL, "PoliticianLeftPartyStillHoldingPositions","Behavior", kcontext.getRule().getName(),"PartyIndependent");
end
