package com.hack23.cia.service.impl.rules
import org.kie.api.runtime.KieRuntime
import com.hack23.cia.model.internal.application.data.politician.impl.ViewRiksdagenPolitician
import com.hack23.cia.service.api.action.kpi.Status
import com.hack23.cia.service.impl.rules.PoliticianComplianceCheckImpl
import java.util.Calendar
 
rule "We have an politician supporting FRA committee_report=FöU15 and rm=2007/08"
    dialect "java"
    salience 50
    when
        $p : PoliticianComplianceCheckImpl( supports("FöU15","2007/08" ) )
    then
        $p.addViolation( Status.MINOR, "PoliticianSupports","Behavior", kcontext.getRule().getName(),"n/a");
end

rule "We have an politician against FRA committee_report=FöU15 and rm=2007/08"
    dialect "java"
    salience 50
    when
        $p : PoliticianComplianceCheckImpl( against("FöU15","2007/08" ) )
    then
        $p.addViolation( Status.MINOR, "PoliticianAgainst","Behavior", kcontext.getRule().getName(),"n/a");
end
