@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>WordCounter\n<size:10>com.hack23.cia.service.impl.action.user.wordcount" as com.hack23.cia.service.impl.action.user.wordcount.WordCounter [[WordCounter.html]] {
        {abstract} +calculateWordCount(DocumentContentData, int): Map<String, Integer>
    }

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
