package com.hack23.cia.service.impl.rules.activity

import org.kie.api.runtime.KieRuntime

import com.hack23.cia.model.internal.application.data.party.impl.ViewRiksdagenPartyDocumentDailySummary
import com.hack23.cia.model.internal.application.data.rules.impl.Status
import com.hack23.cia.service.impl.rules.PartyComplianceCheckImpl

rule "Party with no official documents"
    dialect "java"
    when
        $p : PartyComplianceCheckImpl(
            party.active,
            eval( $p.getDailyDocumentOutput() == 0 )
        )
    then
        $p.addViolation(
            Status.MAJOR,
            "PartyDocumentActivity",
            "DocumentOutput",
            kcontext.getRule().getName(),
            "No Official Documents"
        );
end

rule "Rule #13: Party with no official documents this year"
    when
        $p : PartyComplianceCheckImpl(
              annualSummary != null,
              eval( $p.getAnnualSummary().getDocumentCount() == 0 )
        )
    then
        $p.addViolation(
            Status.MAJOR,
            "DocumentActivity",
            "NoDocuments",
            kcontext.getRule().getName(),
            "Party published 0 documents this year"
        );
end
