@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>CitizenIntelligenceAgencySpringVaadinServlet\n<size:10>com.hack23.cia.web.impl.ui.application" as com.hack23.cia.web.impl.ui.application.CitizenIntelligenceAgencySpringVaadinServlet [[CitizenIntelligenceAgencySpringVaadinServlet.html]] {
        #service(HttpServletRequest, HttpServletResponse): void
        #servletInitialized(): void
    }

    class "<size:14>SpringVaadinServlet\n<size:10>com.vaadin.spring.server" as com.vaadin.spring.server.SpringVaadinServlet

    com.vaadin.spring.server.SpringVaadinServlet <|-- com.hack23.cia.web.impl.ui.application.CitizenIntelligenceAgencySpringVaadinServlet

    center footer UMLDoclet 2.0.4, PlantUML 1.2019.06
@enduml
