@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    enum "<size:14>DataSummaryPageMode\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.viewnames" as com.hack23.cia.web.impl.ui.application.views.common.viewnames.DataSummaryPageMode [[DataSummaryPageMode.html]] {
        {static} +AUTHORS
    }

    center footer UMLDoclet 2.0.4, PlantUML 1.2019.06
@enduml
