@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    enum "<size:14>PartyPageMode\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.viewnames" as com.hack23.cia.web.impl.ui.application.views.common.viewnames.PartyPageMode [[PartyPageMode.html]] {
        {static} +COMMITTEEBALLOTDECISIONSUMMARY
        {static} +COMMITTEEROLES
        {static} +CURRENTLEADERS
        {static} +CURRENTMEMBERS
        {static} +DOCUMENTACTIVITY
        {static} +DOCUMENTHISTORY
        {static} +GOVERNMENTROLES
        {static} +LEADERHISTORY
        {static} +MEMBERHISTORY
        {static} +PARTYAGAINSTCOALATIONSSUMMARY
        {static} +PARTYSUPPORTSUMMARY
        {static} +PARTYWONDAILYSUMMARYCHART
        {static} +ROLEGHANT
        {static} +VOTEHISTORY
    }

    center footer UMLDoclet 2.0.12, PlantUML 1.2020.16
@enduml
