@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>CommitteeDataSeriesFactoryImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.impl" as com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.impl.CommitteeDataSeriesFactoryImpl [[CommitteeDataSeriesFactoryImpl.html]] {
        +createChartTimeSeriesTotalDaysServedCommitteeByParty(): DataSeries
        +createCommitteeChartTimeSeriesAll(): DataSeries
        +createCommitteeChartTimeSeriesCurrent(): DataSeries
    }

    interface "<size:14>CommitteeDataSeriesFactory\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.api" as com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.api.CommitteeDataSeriesFactory [[../api/CommitteeDataSeriesFactory.html]] {
        {abstract} +createChartTimeSeriesTotalDaysServedCommitteeByParty(): DataSeries
        {abstract} +createCommitteeChartTimeSeriesAll(): DataSeries
        {abstract} +createCommitteeChartTimeSeriesCurrent(): DataSeries
    }

    com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.api.CommitteeDataSeriesFactory <|.. com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.impl.CommitteeDataSeriesFactoryImpl

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
