@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>XmlDateTypeAdapter\n<size:10>com.hack23.cia.model.common.impl.xml" as com.hack23.cia.model.common.impl.xml.XmlDateTypeAdapter [[XmlDateTypeAdapter.html]] {
        +unmarshal(String): Date
        +marshal(Date): String
    }

    abstract class "<size:14>XmlAdapter\n<size:10>javax.xml.bind.annotation.adapters" as javax.xml.bind.annotation.adapters.XmlAdapter<String, Date> {
        {abstract} +unmarshal(String): Date
        {abstract} +marshal(Date): String
    }

    javax.xml.bind.annotation.adapters.XmlAdapter <|-- com.hack23.cia.model.common.impl.xml.XmlDateTypeAdapter

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
