@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>BallotMenuItemFactory\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.menufactory.api" as com.hack23.cia.web.impl.ui.application.views.common.menufactory.api.BallotMenuItemFactory [[BallotMenuItemFactory.html]] {
        {abstract} +createBallotMenuBar(MenuBar, String): void
        {abstract} +createOverviewPage(VerticalLayout, String): void
    }

    center footer UMLDoclet 2.0.6, PlantUML 1.2019.12
@enduml
