@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>DocumentMenuItemFactory\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.menufactory.api" as com.hack23.cia.web.impl.ui.application.views.common.menufactory.api.DocumentMenuItemFactory [[DocumentMenuItemFactory.html]] {
        {abstract} +createDocumentMenuBar(MenuBar, String): void
        {abstract} +createDocumentsMenuBar(MenuBar): void
        {abstract} +createOverviewPage(VerticalLayout, String): void
    }

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
