@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>MinistryRankingMenuItemFactory\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.menufactory.api" as com.hack23.cia.web.impl.ui.application.views.common.menufactory.api.MinistryRankingMenuItemFactory [[MinistryRankingMenuItemFactory.html]] {
        {abstract} +createMinistryRankingMenuBar(MenuBar): void
        {abstract} +createMinistryRankingTopics(MenuItem): void
        {abstract} +createOverviewPage(VerticalLayout): void
    }

    center footer UMLDoclet 2.0.7, PlantUML 1.2019.12
@enduml
