@startuml
    namespace com.hack23.cia.web.impl.ui.application.views.common.menufactory.api {

        interface MinistryMenuItemFactory [[MinistryMenuItemFactory.html]] {
            {abstract} +createMinistryMenuBar(MenuBar, String): void
            {abstract} +createOverviewPage(VerticalLayout, String): void
        }

        interface MinistryRankingMenuItemFactory [[MinistryRankingMenuItemFactory.html]] {
            {abstract} +createMinistryRankingMenuBar(MenuBar): void
            {abstract} +createMinistryRankingTopics(MenuItem): void
            {abstract} +createOverviewPage(VerticalLayout): void
        }

        interface CountryMenuItemFactory [[CountryMenuItemFactory.html]] {
            {abstract} +createCountryTopicMenu(MenuBar): void
            {abstract} +createCountryTopicMenu(MenuItem): void
            {abstract} +createOverviewPage(VerticalLayout): void
        }

        interface BallotMenuItemFactory [[BallotMenuItemFactory.html]] {
            {abstract} +createBallotMenuBar(MenuBar, String): void
            {abstract} +createOverviewPage(VerticalLayout, String): void
        }

        interface UserHomeMenuItemFactory [[UserHomeMenuItemFactory.html]] {
            {abstract} +createUserHomeMenuBar(MenuBar, String): void
            {abstract} +createOverviewPage(VerticalLayout): void
        }

        interface PoliticianRankingMenuItemFactory [[PoliticianRankingMenuItemFactory.html]] {
            {abstract} +createPoliticianRankingMenuBar(MenuBar): void
            {abstract} +createPoliticianRankingTopics(MenuItem): void
            {abstract} +createOverviewPage(VerticalLayout): void
        }

        interface GovernmentBodyMenuItemFactory [[GovernmentBodyMenuItemFactory.html]] {
            {abstract} +createGovernmentBodyMenuBar(MenuBar, String): void
            {abstract} +createOverviewPage(VerticalLayout, String): void
        }

        interface ParliamentMenuItemFactory [[ParliamentMenuItemFactory.html]] {
            {abstract} +createParliamentTopicMenu(MenuBar): void
            {abstract} +createParliamentTopicMenu(MenuItem): void
            {abstract} +createOverviewPage(VerticalLayout): void
        }

        interface PoliticianMenuItemFactory [[PoliticianMenuItemFactory.html]] {
            {abstract} +createPoliticianMenuBar(MenuBar, String): void
            {abstract} +createOverviewPage(VerticalLayout, String): void
        }

        interface GovernmentBodyRankingMenuItemFactory [[GovernmentBodyRankingMenuItemFactory.html]] {
            {abstract} +createGovernmentBodyRankingMenuBar(MenuBar): void
            {abstract} +createOverviewPage(VerticalLayout): void
            {abstract} +createGovernmentBodyRankingTopics(MenuItem): void
        }

        interface ApplicationMenuItemFactory [[ApplicationMenuItemFactory.html]] {
            {abstract} +createMainPageMenuBar(MenuBar): MenuBar
            {abstract} +addRankingMenu(MenuBar): void
            {abstract} +createOverviewPage(VerticalLayout): void
        }

        interface CommitteeRankingMenuItemFactory [[CommitteeRankingMenuItemFactory.html]] {
            {abstract} +createCommitteeeRankingMenuBar(MenuBar): void
            {abstract} +createCommitteeRankingTopics(MenuItem): void
            {abstract} +createOverviewPage(VerticalLayout): void
        }

        interface DocumentMenuItemFactory [[DocumentMenuItemFactory.html]] {
            {abstract} +createDocumentMenuBar(MenuBar, String): void
            {abstract} +createDocumentsMenuBar(MenuBar): void
            {abstract} +createOverviewPage(VerticalLayout, String): void
        }

        interface PartyRankingMenuItemFactory [[PartyRankingMenuItemFactory.html]] {
            {abstract} +createPartyRankingMenuBar(MenuBar): void
            {abstract} +createPartyRankingTopics(MenuItem): void
            {abstract} +createOverviewPage(VerticalLayout): void
        }

        interface PartyMenuItemFactory [[PartyMenuItemFactory.html]] {
            {abstract} +createPartyMenuBar(MenuBar, String): void
            {abstract} +createOverviewPage(VerticalLayout, String): void
        }

        interface CommitteeMenuItemFactory [[CommitteeMenuItemFactory.html]] {
            {abstract} +createCommitteeeMenuBar(MenuBar, String): void
            {abstract} +createOverviewPage(VerticalLayout, String): void
        }

    }

    center footer UMLDoclet 2.0.3, PlantUML 1.2019.06
@enduml
