@startuml
    set namespaceSeparator none
    hide circle
    hide empty fields
    hide empty methods

    com.hack23.cia.service.external.common.api --> org.springframework.oxm

    ' Package links
    class "com.hack23.cia.service.external.common.api" [[com/hack23/cia/service/external/common/api/package-summary.html]] {
    }

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
