//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.25 at 12:05:09 AM CET 
//


package com.hack23.cia.model.internal.application.data.document.impl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hack23.cia.model.internal.application.data.document.impl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hack23.cia.model.internal.application.data.document.impl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ViewRiksdagenPoliticianDocument }
     * 
     */
    public ViewRiksdagenPoliticianDocument createViewRiksdagenPoliticianDocument() {
        return new ViewRiksdagenPoliticianDocument();
    }

    /**
     * Create an instance of {@link RiksdagenDocumentTypeSummaryEmbeddedId }
     * 
     */
    public RiksdagenDocumentTypeSummaryEmbeddedId createRiksdagenDocumentTypeSummaryEmbeddedId() {
        return new RiksdagenDocumentTypeSummaryEmbeddedId();
    }

    /**
     * Create an instance of {@link ViewRiksdagenDocumentTypeDailySummary }
     * 
     */
    public ViewRiksdagenDocumentTypeDailySummary createViewRiksdagenDocumentTypeDailySummary() {
        return new ViewRiksdagenDocumentTypeDailySummary();
    }

    /**
     * Create an instance of {@link RiksdagenDocumentPersonSummaryEmbeddedId }
     * 
     */
    public RiksdagenDocumentPersonSummaryEmbeddedId createRiksdagenDocumentPersonSummaryEmbeddedId() {
        return new RiksdagenDocumentPersonSummaryEmbeddedId();
    }

    /**
     * Create an instance of {@link ViewRiksdagenPoliticianDocumentDailySummary }
     * 
     */
    public ViewRiksdagenPoliticianDocumentDailySummary createViewRiksdagenPoliticianDocumentDailySummary() {
        return new ViewRiksdagenPoliticianDocumentDailySummary();
    }

    /**
     * Create an instance of {@link RiksdagenDocumentPartySummaryEmbeddedId }
     * 
     */
    public RiksdagenDocumentPartySummaryEmbeddedId createRiksdagenDocumentPartySummaryEmbeddedId() {
        return new RiksdagenDocumentPartySummaryEmbeddedId();
    }

    /**
     * Create an instance of {@link ViewRiksdagenPartyDocumentDailySummary }
     * 
     */
    public ViewRiksdagenPartyDocumentDailySummary createViewRiksdagenPartyDocumentDailySummary() {
        return new ViewRiksdagenPartyDocumentDailySummary();
    }

    /**
     * Create an instance of {@link RiksdagenDocumentOrgSummaryEmbeddedId }
     * 
     */
    public RiksdagenDocumentOrgSummaryEmbeddedId createRiksdagenDocumentOrgSummaryEmbeddedId() {
        return new RiksdagenDocumentOrgSummaryEmbeddedId();
    }

    /**
     * Create an instance of {@link ViewRiksdagenOrgDocumentDailySummary }
     * 
     */
    public ViewRiksdagenOrgDocumentDailySummary createViewRiksdagenOrgDocumentDailySummary() {
        return new ViewRiksdagenOrgDocumentDailySummary();
    }

}
