@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>CommitteeDocumentHistoryPageModContentFactoryImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.user.committee.pagemode" as com.hack23.cia.web.impl.ui.application.views.user.committee.pagemode.CommitteeDocumentHistoryPageModContentFactoryImpl [[CommitteeDocumentHistoryPageModContentFactoryImpl.html]] {
        +createContent(String, MenuBar, Panel): Layout
        +matches(String, String): boolean
    }

    abstract class "<size:14>AbstractItemPageModContentFactoryImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.pagemode" as com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractItemPageModContentFactoryImpl<ViewRiksdagenCommittee> [[../../../common/pagemode/AbstractItemPageModContentFactoryImpl.html]] {
        {abstract} #getItem(String): ViewRiksdagenCommittee
    }

    com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractItemPageModContentFactoryImpl <|-- com.hack23.cia.web.impl.ui.application.views.user.committee.pagemode.CommitteeDocumentHistoryPageModContentFactoryImpl

    center footer UMLDoclet 2.0.12, PlantUML 1.2020.16
@enduml
