@startuml
    namespace com.hack23.cia.web.impl.ui.application.views.user.committee.pagemode {

        class CommitteeRankingPageVisitHistoryPageModContentFactoryImpl [[CommitteeRankingPageVisitHistoryPageModContentFactoryImpl.html]] {
            {static} +NAME: String
            +matches(String, String): boolean
            +createContent(String, MenuBar, Panel): Layout
        }

        class CommitteeOverviewPageModContentFactoryImpl [[CommitteeOverviewPageModContentFactoryImpl.html]] {
            +matches(String, String): boolean
            +createContent(String, MenuBar, Panel): Layout
        }

        class CommitteeRoleGhantPageModContentFactoryImpl [[CommitteeRoleGhantPageModContentFactoryImpl.html]] {
            +matches(String, String): boolean
            +createContent(String, MenuBar, Panel): Layout
        }

        class CommitteeRankingCurrentCommitteesChartsPageModContentFactoryImpl [[CommitteeRankingCurrentCommitteesChartsPageModContentFactoryImpl.html]] {
            {static} +NAME: String
            +matches(String, String): boolean
            +createContent(String, MenuBar, Panel): Layout
        }

        class CommitteeRankingDataGridPageModContentFactoryImpl [[CommitteeRankingDataGridPageModContentFactoryImpl.html]] {
            {static} +NAME: String
            +matches(String, String): boolean
            +createContent(String, MenuBar, Panel): Layout
        }

        class CommitteeRankingOverviewPageModContentFactoryImpl [[CommitteeRankingOverviewPageModContentFactoryImpl.html]] {
            {static} +NAME: String
            +matches(String, String): boolean
            +createContent(String, MenuBar, Panel): Layout
        }

        class CommitteePageVisitHistoryPageModContentFactoryImpl [[CommitteePageVisitHistoryPageModContentFactoryImpl.html]] {
            +matches(String, String): boolean
            +createContent(String, MenuBar, Panel): Layout
        }

        class CommitteeDocumentHistoryPageModContentFactoryImpl [[CommitteeDocumentHistoryPageModContentFactoryImpl.html]] {
            +matches(String, String): boolean
            +createContent(String, MenuBar, Panel): Layout
        }

        class CommitteeCurrentMembersHistoryPageModContentFactoryImpl [[CommitteeCurrentMembersHistoryPageModContentFactoryImpl.html]] {
            +matches(String, String): boolean
            +createContent(String, MenuBar, Panel): Layout
        }

        class CommitteeBallotDecisionSummaryPageModContentFactoryImpl [[CommitteeBallotDecisionSummaryPageModContentFactoryImpl.html]] {
            +matches(String, String): boolean
            +createContent(String, MenuBar, Panel): Layout
        }

        class CommitteeRankingAllCommitteesChartsPageModContentFactoryImpl [[CommitteeRankingAllCommitteesChartsPageModContentFactoryImpl.html]] {
            {static} +NAME: String
            +matches(String, String): boolean
            +createContent(String, MenuBar, Panel): Layout
        }

        class CommitteeDecisionFlowPageModContentFactoryImpl [[CommitteeDecisionFlowPageModContentFactoryImpl.html]] {
            +matches(String, String): boolean
            +createContent(String, MenuBar, Panel): Layout
        }

        class CommitteeDocumentActivityPageModContentFactoryImpl [[CommitteeDocumentActivityPageModContentFactoryImpl.html]] {
            +matches(String, String): boolean
            +createContent(String, MenuBar, Panel): Layout
        }

        class CommitteeDecisionTypeDailySummaryPageModContentFactoryImpl2 [[CommitteeDecisionTypeDailySummaryPageModContentFactoryImpl2.html]] {
            +matches(String, String): boolean
            +createContent(String, MenuBar, Panel): Layout
        }

        class CommitteeRankingCommitteeByPartyChartsPageModContentFactoryImpl [[CommitteeRankingCommitteeByPartyChartsPageModContentFactoryImpl.html]] {
            {static} +NAME: String
            +matches(String, String): boolean
            +createContent(String, MenuBar, Panel): Layout
        }

        class CommitteeRankingCurrentCommitteePartiesChartsPageModContentFactoryImpl [[CommitteeRankingCurrentCommitteePartiesChartsPageModContentFactoryImpl.html]] {
            {static} +NAME: String
            +matches(String, String): boolean
            +createContent(String, MenuBar, Panel): Layout
        }

        class CommitteeDecisionSummaryPageModContentFactoryImpl [[CommitteeDecisionSummaryPageModContentFactoryImpl.html]] {
            +matches(String, String): boolean
            +createContent(String, MenuBar, Panel): Layout
        }

        class CommitteeMemberHistoryPageModContentFactoryImpl [[CommitteeMemberHistoryPageModContentFactoryImpl.html]] {
            +matches(String, String): boolean
            +createContent(String, MenuBar, Panel): Layout
        }

        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- CommitteeRankingPageVisitHistoryPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractItemPageModContentFactoryImpl <|-- CommitteeOverviewPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractItemPageModContentFactoryImpl <|-- CommitteeRoleGhantPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- CommitteeRankingCurrentCommitteesChartsPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- CommitteeRankingDataGridPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- CommitteeRankingOverviewPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractItemPageModContentFactoryImpl <|-- CommitteePageVisitHistoryPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractItemPageModContentFactoryImpl <|-- CommitteeDocumentHistoryPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractItemPageModContentFactoryImpl <|-- CommitteeCurrentMembersHistoryPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractItemPageModContentFactoryImpl <|-- CommitteeBallotDecisionSummaryPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- CommitteeRankingAllCommitteesChartsPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractItemPageModContentFactoryImpl <|-- CommitteeDecisionFlowPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractItemPageModContentFactoryImpl <|-- CommitteeDocumentActivityPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractItemPageModContentFactoryImpl <|-- CommitteeDecisionTypeDailySummaryPageModContentFactoryImpl2
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- CommitteeRankingCommitteeByPartyChartsPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- CommitteeRankingCurrentCommitteePartiesChartsPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractItemPageModContentFactoryImpl <|-- CommitteeDecisionSummaryPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractItemPageModContentFactoryImpl <|-- CommitteeMemberHistoryPageModContentFactoryImpl
    }

    namespace com.hack23.cia.web.impl.ui.application.views.common.pagemode {
        abstract class AbstractBasicPageModContentFactoryImpl [[../../../common/pagemode/AbstractBasicPageModContentFactoryImpl.html]]
        abstract class AbstractItemPageModContentFactoryImpl<T> [[../../../common/pagemode/AbstractItemPageModContentFactoryImpl.html]] {
            {abstract} #getItem(String): T
        }
    }

    center footer UMLDoclet 2.0.3, PlantUML 1.2019.06
@enduml
