@startuml
    set namespaceSeparator none
    hide circle
    hide empty fields
    hide empty methods

    com.hack23.cia.model.external.riksdagen.voteringlista.impl --> com.hack23.cia.model.common.api
    com.hack23.cia.model.external.riksdagen.voteringlista.impl --> com.hack23.cia.testfoundation
    com.hack23.cia.model.external.riksdagen.voteringlista.impl --> org.jvnet.hyperjaxb3.ejb.test
    com.hack23.cia.model.external.riksdagen.voteringlista.impl --> org.jvnet.jaxb2_commons.xml.bind

    ' Package links
    class "com.hack23.cia.model.external.riksdagen.voteringlista.impl" [[com/hack23/cia/model/external/riksdagen/voteringlista/impl/package-summary.html]] {
    }

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
