@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>GovernmentBodyChartDataManager\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api.GovernmentBodyChartDataManager [[GovernmentBodyChartDataManager.html]] {
        {abstract} +createMinistryGovernmentBodyHeadcountSummaryChart(AbstractOrderedLayout, String): void
        {abstract} +createMinistryGovernmentBodyHeadcountSummaryChart(AbstractOrderedLayout): void
        {abstract} +createMinistryGovernmentBodyIncomeSummaryChart(AbstractOrderedLayout): void
        {abstract} +createMinistryGovernmentBodyExpenditureSummaryChart(AbstractOrderedLayout): void
        {abstract} +createGovernmentBodyHeadcountSummaryChart(VerticalLayout): void
        {abstract} +createGovernmentBodyHeadcountSummaryChart(VerticalLayout, String): void
        {abstract} +createGovernmentBodyIncomeSummaryChart(VerticalLayout): void
        {abstract} +createGovernmentBodyIncomeSummaryChart(VerticalLayout, String): void
        {abstract} +createGovernmentBodyExpenditureSummaryChart(VerticalLayout): void
        {abstract} +createGovernmentBodyExpenditureSummaryChart(VerticalLayout, String): void
        {abstract} +createMinistryGovernmentBodyIncomeSummaryChart(VerticalLayout, String): void
        {abstract} +createMinistryGovernmentBodyExpenditureSummaryChart(VerticalLayout, String): void
    }

    center footer UMLDoclet 2.0.3, PlantUML 1.2019.06
@enduml
