@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>PartyCoalationChartDataManager\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api.PartyCoalationChartDataManager [[PartyCoalationChartDataManager.html]] {
        {abstract} +createPartyChart(AbstractOrderedLayout, String): void
    }

    center footer UMLDoclet 2.0.3, PlantUML 1.2019.06
@enduml
