@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>PoliticianComplianceCheckImpl\n<size:10>com.hack23.cia.service.impl.rules" as com.hack23.cia.service.impl.rules.PoliticianComplianceCheckImpl [[PoliticianComplianceCheckImpl.html]] {
        +PoliticianComplianceCheckImpl(ViewRiksdagenPolitician, ViewRiksdagenVoteDataBallotPoliticianSummaryDaily, ViewRiksdagenVoteDataBallotPoliticianSummaryMonthly, ViewRiksdagenVoteDataBallotPoliticianSummaryAnnual, List<ViewRiksdagenCommitteeBallotDecisionPoliticianSummary>)
        +getPolitician(): ViewRiksdagenPolitician
        +getName(): String
        +getId(): String
        +supports(String, String, String): boolean
        +against(String, String, String): boolean
        +getDailySummary(): ViewRiksdagenVoteDataBallotPoliticianSummaryDaily
        +getMonthlySummary(): ViewRiksdagenVoteDataBallotPoliticianSummaryMonthly
        +getAnnualSummary(): ViewRiksdagenVoteDataBallotPoliticianSummaryAnnual
        +getYear(): int
        +getAge(): int
    }

    abstract class "<size:14>AbstractComplianceCheckImpl\n<size:10>com.hack23.cia.service.impl.rules" as com.hack23.cia.service.impl.rules.AbstractComplianceCheckImpl [[AbstractComplianceCheckImpl.html]]

    com.hack23.cia.service.impl.rules.AbstractComplianceCheckImpl <|-- com.hack23.cia.service.impl.rules.PoliticianComplianceCheckImpl

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
