@startuml
    namespace com.hack23.cia.web.impl.ui.application.views.common.rows {

        class RowUtil [[RowUtil.html]] {
            {static} +createGridLayout(AbstractOrderedLayout): ResponsiveRow
            {static} +createRowComponent(ResponsiveRow, Component, String): void
            {static} +createRowItem(ResponsiveRow, Button, String): void
        }

    }

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
