package com.hack23.cia.service.impl.rules.politician

import org.kie.api.runtime.KieRuntime

import com.hack23.cia.model.internal.application.data.politician.impl.ViewRiksdagenPolitician
import com.hack23.cia.model.internal.application.data.rules.impl.Status
import com.hack23.cia.service.impl.rules.PoliticianComplianceCheckImpl

rule "We have an politician with leading role in the party"
	dialect "java"
	salience 1000
    when
        $p : PoliticianComplianceCheckImpl( politician.active && politician.currentPartyAssignments > 0 )
    then
    	$p.addViolation( Status.MINOR, "PoliticianPartyLeader","Behavior", kcontext.getRule().getName(),"Influential");
end

rule "We have an politician part of government"
	dialect "java"
	salience 100
    when
        $p : PoliticianComplianceCheckImpl( politician.active &&  politician.currentMinistryAssignments > 0)
    then
    	$p.addViolation( Status.MAJOR, "PoliticianPartyLeader","Behavior", kcontext.getRule().getName(),"Influential");
end

rule "We have an politician party leader and part of government"
	dialect "java"
	salience 10
    when
        $p : PoliticianComplianceCheckImpl( politician.active && politician.currentPartyAssignments > 0 &&  politician.currentMinistryAssignments > 0)
    then
    	$p.addViolation( Status.CRITICAL, "PoliticianPartyLeader","Behavior", kcontext.getRule().getName(),"Influential");
end