package com.hack23.cia.service.impl.rules.politician

import org.kie.api.runtime.KieRuntime

import com.hack23.cia.model.internal.application.data.politician.impl.ViewRiksdagenPolitician
import com.hack23.cia.model.internal.application.data.rules.impl.Status
import com.hack23.cia.service.impl.rules.PoliticianComplianceCheckImpl

rule "Politician with low collaboration - below 20%"
	dialect "java"
	salience 10
    when
        $p : PoliticianComplianceCheckImpl(politician.active && politician.totalDocuments > 10 && politician.collaborationPercentage < 20 && politician.collaborationPercentage >= 10)
    then
    	$p.addViolation( Status.MINOR, "PoliticianIsolatedBehavior","Behavior", kcontext.getRule().getName(),"LowCollaboration");
end

rule "Politician with very low collaboration - below 10%"
	dialect "java"
	salience 50
    when
        $p : PoliticianComplianceCheckImpl(politician.active && politician.totalDocuments > 10 && politician.collaborationPercentage < 10 && politician.collaborationPercentage > 0)
    then
    	$p.addViolation( Status.MAJOR, "PoliticianIsolatedBehavior","Behavior", kcontext.getRule().getName(),"VeryLowCollaboration");
end

rule "Politician with no multi-party collaboration"
	dialect "java"
	salience 100
    when
        $p : PoliticianComplianceCheckImpl(politician.active && politician.totalDocuments > 20 && politician.multiPartyMotions == 0)
    then
    	$p.addViolation( Status.CRITICAL, "PoliticianIsolatedBehavior","Behavior", kcontext.getRule().getName(),"NoMultiPartyCollaboration");
end
