@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>DecisionDataFactoryImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.impl" as com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.impl.DecisionDataFactoryImpl [[DecisionDataFactoryImpl.html]] {
        +createCommitteeSummary(String): List<ProposalCommitteeeSummary>
    }

    interface "<size:14>DecisionDataFactory\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.api" as com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.api.DecisionDataFactory [[../api/DecisionDataFactory.html]] {
        {abstract} +createCommitteeSummary(String): List<ProposalCommitteeeSummary>
    }

    com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.api.DecisionDataFactory <|.. com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.impl.DecisionDataFactoryImpl

    center footer UMLDoclet 2.0.4, PlantUML 1.2019.06
@enduml
