@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>MinistryDataSeriesFactoryImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.impl" as com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.impl.MinistryDataSeriesFactoryImpl [[MinistryDataSeriesFactoryImpl.html]] {
        +createChartTimeSeriesTotalDaysServedGovernmentByParty(): DataSeries
        +createMinistryChartTimeSeriesAll(): DataSeries
        +createMinistryChartTimeSeriesCurrent(): DataSeries
    }

    interface "<size:14>MinistryDataSeriesFactory\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.api" as com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.api.MinistryDataSeriesFactory [[../api/MinistryDataSeriesFactory.html]] {
        {abstract} +createChartTimeSeriesTotalDaysServedGovernmentByParty(): DataSeries
        {abstract} +createMinistryChartTimeSeriesAll(): DataSeries
        {abstract} +createMinistryChartTimeSeriesCurrent(): DataSeries
    }

    com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.api.MinistryDataSeriesFactory <|.. com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.impl.MinistryDataSeriesFactoryImpl

    center footer UMLDoclet 2.0.12, PlantUML 1.2020.16
@enduml
