@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>LoginService\n<size:10>com.hack23.cia.service.impl.action.application" as com.hack23.cia.service.impl.action.application.LoginService [[LoginService.html]] {
        +processService(LoginRequest): LoginResponse
        #createApplicationEventForService(LoginRequest): CreateApplicationEventRequest
        #createErrorResponse(): LoginResponse
    }

    abstract class "<size:14>AbstractBusinessServiceImpl\n<size:10>com.hack23.cia.service.impl.action.common" as com.hack23.cia.service.impl.action.common.AbstractBusinessServiceImpl<LoginRequest, LoginResponse> [[../common/AbstractBusinessServiceImpl.html]] {
        {abstract} #createErrorResponse(): LoginResponse
        {abstract} #createApplicationEventForService(LoginRequest): CreateApplicationEventRequest
    }
    interface "<size:14>BusinessService\n<size:10>com.hack23.cia.service.impl.action.common" as com.hack23.cia.service.impl.action.common.BusinessService<LoginRequest, LoginResponse> [[../common/BusinessService.html]] {
        {abstract} +getSupportedService(): Class<? extends ServiceRequest>
        {abstract} +processService(LoginRequest): LoginResponse
    }

    com.hack23.cia.service.impl.action.common.AbstractBusinessServiceImpl <|-- com.hack23.cia.service.impl.action.application.LoginService
    com.hack23.cia.service.impl.action.common.BusinessService <|.. com.hack23.cia.service.impl.action.application.LoginService

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
