@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>CommitteeDataSeriesFactory\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.api" as com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.api.CommitteeDataSeriesFactory [[CommitteeDataSeriesFactory.html]] {
        {abstract} +createChartTimeSeriesTotalDaysServedCommitteeByParty(): DataSeries
        {abstract} +createCommitteeChartTimeSeriesAll(): DataSeries
        {abstract} +createCommitteeChartTimeSeriesCurrent(): DataSeries
    }

    center footer UMLDoclet 2.0.4, PlantUML 1.2019.06
@enduml
