@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>MinistryDataSeriesFactory\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.api" as com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.api.MinistryDataSeriesFactory [[MinistryDataSeriesFactory.html]] {
        {abstract} +createChartTimeSeriesTotalDaysServedGovernmentByParty(): DataSeries
        {abstract} +createMinistryChartTimeSeriesAll(): DataSeries
        {abstract} +createMinistryChartTimeSeriesCurrent(): DataSeries
    }

    center footer UMLDoclet 2.0.7, PlantUML 1.2019.12
@enduml
