@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ProposalCommitteeeSummary\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.api" as com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.api.ProposalCommitteeeSummary [[ProposalCommitteeeSummary.html]] {
        +ProposalCommitteeeSummary(String, String, String, String)
        +getOrg(): String
        +getDocType(): String
        +getDecision(): String
        +getHangarId(): String
    }

    center footer UMLDoclet 2.0.3, PlantUML 1.2019.06
@enduml
