//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.02.25 at 12:05:09 AM CET
//


package com.hack23.cia.model.internal.application.system.impl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConfigurationGroup.</p>
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>
 * &lt;simpleType name="ConfigurationGroup"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="AUTHENTICATION"/&gt;
 *     &lt;enumeration value="AUTHORIZATION"/&gt;
 *     &lt;enumeration value="AGENT"/&gt;
 *     &lt;enumeration value="EXTERNAL_SERVICES"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "ConfigurationGroup")
@XmlEnum
public enum ConfigurationGroup {

    AUTHENTICATION,
    AUTHORIZATION,
    AGENT,
    EXTERNAL_SERVICES;

    public String value() {
        return name();
    }

    public static ConfigurationGroup fromValue(final String v) {
        return valueOf(v);
    }

}
