@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>GovernmentBodyPageVisitHistoryPageModContentFactoryImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.user.govermentbody.pagemode" as com.hack23.cia.web.impl.ui.application.views.user.govermentbody.pagemode.GovernmentBodyPageVisitHistoryPageModContentFactoryImpl [[GovernmentBodyPageVisitHistoryPageModContentFactoryImpl.html]] {
        {static} +NAME: String
        +createContent(String, MenuBar, Panel): Layout
        +matches(String, String): boolean
    }

    abstract class "<size:14>AbstractItemPageModContentFactoryImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.pagemode" as com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractItemPageModContentFactoryImpl<List<GovernmentBodyAnnualSummary>> [[../../../common/pagemode/AbstractItemPageModContentFactoryImpl.html]] {
        {abstract} #getItem(String): List<GovernmentBodyAnnualSummary>
    }

    com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractItemPageModContentFactoryImpl <|-- com.hack23.cia.web.impl.ui.application.views.user.govermentbody.pagemode.GovernmentBodyPageVisitHistoryPageModContentFactoryImpl

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
