@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    enum "<size:14>ApplicationEventGroup\n<size:10>com.hack23.cia.model.internal.application.system.impl" as com.hack23.cia.model.internal.application.system.impl.ApplicationEventGroup [[ApplicationEventGroup.html]] {
        {static} +ADMIN
        {static} +USER
        {static} +APPLICATION
        {static} +ERROR
        +value(): String
        {static} +fromValue(String): ApplicationEventGroup
    }

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
