@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    enum "<size:14>ApplicationSessionType\n<size:10>com.hack23.cia.model.internal.application.system.impl" as com.hack23.cia.model.internal.application.system.impl.ApplicationSessionType [[ApplicationSessionType.html]] {
        {static} +ANONYMOUS
        {static} +REGISTERED_USER
        {static} +SYSTEM
        +value(): String
        {static} +fromValue(String): ApplicationSessionType
    }

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
