@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>AdminApplicationSessionPageModContentFactoryImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.admin.system.pagemode" as com.hack23.cia.web.impl.ui.application.views.admin.system.pagemode.AdminApplicationSessionPageModContentFactoryImpl [[AdminApplicationSessionPageModContentFactoryImpl.html]] {
        {static} +NAME: String
        +createContent(String, MenuBar, Panel): Layout
        +matches(String, String): boolean
    }

    abstract class "<size:14>AbstractAdminSystemPageModContentFactoryImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.admin.system.pagemode" as com.hack23.cia.web.impl.ui.application.views.admin.system.pagemode.AbstractAdminSystemPageModContentFactoryImpl [[AbstractAdminSystemPageModContentFactoryImpl.html]]

    com.hack23.cia.web.impl.ui.application.views.admin.system.pagemode.AbstractAdminSystemPageModContentFactoryImpl <|-- com.hack23.cia.web.impl.ui.application.views.admin.system.pagemode.AdminApplicationSessionPageModContentFactoryImpl

    center footer UMLDoclet 2.0.12, PlantUML 1.2020.16
@enduml
