@startuml
    namespace com.hack23.cia.service.component.agent.impl.val {

        class ValImportServiceAutoLoadAtStartup [[ValImportServiceAutoLoadAtStartup.html]] {
            +autoLoad(): void
        }

        interface ValImportService [[ValImportService.html]] {
            {abstract} +loadPoliticalParties(): void
        }

    }

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
