@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>AdminChartDataManager\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api.AdminChartDataManager [[AdminChartDataManager.html]] {
        {abstract} +createApplicationActionEventPageDailySummaryChart(AbstractOrderedLayout): void
        {abstract} +createApplicationActionEventPageElementDailySummaryChart(AbstractOrderedLayout, String, String): void
        {abstract} +createApplicationActionEventPageModeDailySummaryChart(AbstractOrderedLayout, String): void
        {abstract} +createApplicationSessionPageDailySummaryChart(VerticalLayout): void
    }

    center footer UMLDoclet 2.0.12, PlantUML 1.2020.16
@enduml
