@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>BallotChartDataManager\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api.BallotChartDataManager [[BallotChartDataManager.html]] {
        {abstract} +createChart(Tab, AbstractOrderedLayout, List<ViewRiksdagenVoteDataBallotPartySummary>): void
        {abstract} +createChart(Tab, AbstractOrderedLayout, ViewRiksdagenVoteDataBallotSummary): void
    }

    center footer UMLDoclet 2.0.6, PlantUML 1.2019.12
@enduml
