@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>DocumentChartDataManager\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api.DocumentChartDataManager [[DocumentChartDataManager.html]] {
        {abstract} +createDocumentTypeChart(AbstractOrderedLayout): void
    }

    center footer UMLDoclet 2.0.12, PlantUML 1.2020.16
@enduml
