@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>GenericChartDataManager\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api.GenericChartDataManager<T> [[GenericChartDataManager.html]] {
        {abstract} +findByValue(String): List<T>
    }

    center footer UMLDoclet 2.0.4, PlantUML 1.2019.06
@enduml
