@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>GovernmentOutcomeChartDataManager\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api.GovernmentOutcomeChartDataManager [[GovernmentOutcomeChartDataManager.html]] {
        {abstract} +createGovernmentOutcomeChart(AbstractOrderedLayout): void
    }

    center footer UMLDoclet 2.0.7, PlantUML 1.2019.12
@enduml
