@startuml
    namespace com.hack23.cia.web.impl.ui.application.views.user.parliament.pagemode {

        class ParliamentRiskPageModContentFactoryImpl [[ParliamentRiskPageModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class com.hack23.cia.web.impl.ui.application.views.user.parliament.pagemode.ParliamentRiskPageModContentFactoryImpl.ComplianceCheckImpl [[ParliamentRiskPageModContentFactoryImpl.ComplianceCheckImpl.html]] {
            +ComplianceCheckImpl(List<RuleViolation>)
            +getResourceType(): ResourceType
            +getRuleViolations(): List<RuleViolation>
            +getNumberRuleViolations(): int
            +getRuleSummary(): String
            +getId(): String
            +getName(): String
        }

        class ParliamentChartsDocumentActivityByTypePageModContentFactoryImpl [[ParliamentChartsDocumentActivityByTypePageModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class ParliamentPageVisitHistoryPageModContentFactoryImpl [[ParliamentPageVisitHistoryPageModContentFactoryImpl.html]] {
            {static} +NAME: String
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class ParliamentChartsPartyGenderPageModContentFactoryImpl [[ParliamentChartsPartyGenderPageModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class ParliamentOverviewPageModContentFactoryImpl [[ParliamentOverviewPageModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class ParliamentChartsPartyAgePageModContentFactoryImpl [[ParliamentChartsPartyAgePageModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class ParliamentDecisionFlowPageModContentFactoryImpl [[ParliamentDecisionFlowPageModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class ParliamentChartsDecisionActivityByTypePageModContentFactoryImpl [[ParliamentChartsDecisionActivityByTypePageModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class ParliamentRuleViolationsPageModContentFactoryImpl [[ParliamentRuleViolationsPageModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class ParliamentChartsPartyWinnerPageModContentFactoryImpl [[ParliamentChartsPartyWinnerPageModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- ParliamentRiskPageModContentFactoryImpl
        com.hack23.cia.service.api.action.kpi.ComplianceCheck <|.. com.hack23.cia.web.impl.ui.application.views.user.parliament.pagemode.ParliamentRiskPageModContentFactoryImpl.ComplianceCheckImpl
        ParliamentRiskPageModContentFactoryImpl +-- com.hack23.cia.web.impl.ui.application.views.user.parliament.pagemode.ParliamentRiskPageModContentFactoryImpl.ComplianceCheckImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- ParliamentChartsDocumentActivityByTypePageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- ParliamentPageVisitHistoryPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- ParliamentChartsPartyGenderPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- ParliamentOverviewPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- ParliamentChartsPartyAgePageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- ParliamentDecisionFlowPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- ParliamentChartsDecisionActivityByTypePageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- ParliamentRuleViolationsPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- ParliamentChartsPartyWinnerPageModContentFactoryImpl
    }

    namespace com.hack23.cia.web.impl.ui.application.views.common.pagemode {
        abstract class AbstractBasicPageModContentFactoryImpl [[../../../common/pagemode/AbstractBasicPageModContentFactoryImpl.html]]
    }

    namespace com.hack23.cia.service.api.action.kpi {
        interface ComplianceCheck {
            {abstract} +getResourceType(): ResourceType
            {abstract} +getRuleViolations(): List<RuleViolation>
            {abstract} +getId(): String
            {abstract} +getName(): String
        }
    }

    center footer UMLDoclet 2.0.12, PlantUML 1.2020.16
@enduml
