@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ApplicationLoginListener\n<size:10>com.hack23.cia.web.impl.ui.application.views.pageclicklistener" as com.hack23.cia.web.impl.ui.application.views.pageclicklistener.ApplicationLoginListener [[ApplicationLoginListener.html]] {
        +ApplicationLoginListener(LoginRequest)
        +buttonClick(ClickEvent): void
    }

    interface "<size:14>Button.ClickListener\n<size:10>com.vaadin.ui" as com.vaadin.ui.Button.ClickListener {
        {abstract} +buttonClick(ClickEvent): void
    }

    com.vaadin.ui.Button.ClickListener <|.. com.hack23.cia.web.impl.ui.application.views.pageclicklistener.ApplicationLoginListener

    center footer UMLDoclet 2.0.6, PlantUML 1.2019.12
@enduml
