@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>RemoveDataClickListener\n<size:10>com.hack23.cia.web.impl.ui.application.views.pageclicklistener" as com.hack23.cia.web.impl.ui.application.views.pageclicklistener.RemoveDataClickListener [[RemoveDataClickListener.html]] {
        +RemoveDataClickListener(RemoveDataRequest)
        +buttonClick(ClickEvent): void
    }

    interface "<size:14>Button.ClickListener\n<size:10>com.vaadin.ui" as com.vaadin.ui.Button.ClickListener {
        {abstract} +buttonClick(ClickEvent): void
    }

    com.vaadin.ui.Button.ClickListener <|.. com.hack23.cia.web.impl.ui.application.views.pageclicklistener.RemoveDataClickListener

    center footer UMLDoclet 2.0.7, PlantUML 1.2019.12
@enduml
