#! /bin/bash

if [ -x /etc/init.d/cia ]; then
  /etc/init.d/cia stop || true
fi

if [ -e /opt/cia/bin/cia.sh ]; then
  mv -f /opt/cia/bin/cia.sh /opt/cia/bin/jetty.sh
fi
rm -f /etc/init.d/cia
rm -f /opt/cia/cia-base/etc/cacerts

echo prerm
exit 0
