@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>RulesConfiguration\n<size:10>com.hack23.cia.service.impl.rules" as com.hack23.cia.service.impl.rules.RulesConfiguration [[RulesConfiguration.html]] {
        +kieContainer(): KieContainer
    }

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
