@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>RulesEngine\n<size:10>com.hack23.cia.service.impl.rules" as com.hack23.cia.service.impl.rules.RulesEngine [[RulesEngine.html]] {
        {abstract} +checkRulesCompliance(): List<ComplianceCheck>
    }

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
