@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SetGoogleAuthenticatorCredentialService\n<size:10>com.hack23.cia.service.impl.action.user" as com.hack23.cia.service.impl.action.user.SetGoogleAuthenticatorCredentialService [[SetGoogleAuthenticatorCredentialService.html]] {
        +processService(SetGoogleAuthenticatorCredentialRequest): SetGoogleAuthenticatorCredentialResponse
        #createApplicationEventForService(SetGoogleAuthenticatorCredentialRequest): CreateApplicationEventRequest
        #createErrorResponse(): SetGoogleAuthenticatorCredentialResponse
    }

    abstract class "<size:14>AbstractBusinessServiceImpl\n<size:10>com.hack23.cia.service.impl.action.common" as com.hack23.cia.service.impl.action.common.AbstractBusinessServiceImpl<SetGoogleAuthenticatorCredentialRequest, SetGoogleAuthenticatorCredentialResponse> [[../common/AbstractBusinessServiceImpl.html]] {
        {abstract} #createErrorResponse(): SetGoogleAuthenticatorCredentialResponse
        {abstract} #createApplicationEventForService(SetGoogleAuthenticatorCredentialRequest): CreateApplicationEventRequest
    }
    interface "<size:14>BusinessService\n<size:10>com.hack23.cia.service.impl.action.common" as com.hack23.cia.service.impl.action.common.BusinessService<SetGoogleAuthenticatorCredentialRequest, SetGoogleAuthenticatorCredentialResponse> [[../common/BusinessService.html]] {
        {abstract} +getSupportedService(): Class<? extends ServiceRequest>
        {abstract} +processService(SetGoogleAuthenticatorCredentialRequest): SetGoogleAuthenticatorCredentialResponse
    }

    com.hack23.cia.service.impl.action.common.AbstractBusinessServiceImpl <|-- com.hack23.cia.service.impl.action.user.SetGoogleAuthenticatorCredentialService
    com.hack23.cia.service.impl.action.common.BusinessService <|.. com.hack23.cia.service.impl.action.user.SetGoogleAuthenticatorCredentialService

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
