@startuml
    set namespaceSeparator none
    hide circle
    hide empty fields
    hide empty methods

    com.hack23.cia.model.common.impl --> com.hack23.cia.model.common.api
    com.hack23.cia.model.common.impl --> com.hack23.cia.testfoundation
    com.hack23.cia.model.common.impl.xml --> org.slf4j
    com.hack23.cia.model.common.impl.xml --> com.hack23.cia.testfoundation

    ' Package links
    class "com.hack23.cia.model.common.impl" [[com/hack23/cia/model/common/impl/package-summary.html]] {
    }
    class "com.hack23.cia.model.common.impl.xml" [[com/hack23/cia/model/common/impl/xml/package-summary.html]] {
    }

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
