REFRESH MATERIALIZED VIEW view_worldbank_indicator_data_country_summary;
REFRESH MATERIALIZED VIEW view_riksdagen_vote_data_ballot_summary;
REFRESH MATERIALIZED VIEW view_riksdagen_vote_data_ballot_party_summary;
REFRESH MATERIALIZED VIEW view_riksdagen_vote_data_ballot_politician_summary;
REFRESH MATERIALIZED VIEW view_riksdagen_vote_data_ballot_party_summary_daily;
REFRESH MATERIALIZED VIEW view_riksdagen_vote_data_ballot_party_summary_annual;
REFRESH MATERIALIZED VIEW view_riksdagen_vote_data_ballot_party_summary_monthly;
REFRESH MATERIALIZED VIEW view_riksdagen_vote_data_ballot_party_summary_weekly;

REFRESH MATERIALIZED VIEW view_riksdagen_vote_data_ballot_summary_daily;
REFRESH MATERIALIZED VIEW view_riksdagen_vote_data_ballot_summary_annual;
REFRESH MATERIALIZED VIEW view_riksdagen_vote_data_ballot_summary_monthly;
REFRESH MATERIALIZED VIEW view_riksdagen_vote_data_ballot_summary_weekly;

REFRESH MATERIALIZED VIEW view_riksdagen_vote_data_ballot_politician_summary_daily;
REFRESH MATERIALIZED VIEW view_riksdagen_vote_data_ballot_politician_summary_annual;
REFRESH MATERIALIZED VIEW view_riksdagen_vote_data_ballot_politician_summary_monthly;
REFRESH MATERIALIZED VIEW view_riksdagen_vote_data_ballot_politician_summary_weekly;
REFRESH MATERIALIZED VIEW view_riksdagen_committee_decisions;
REFRESH MATERIALIZED VIEW view_riksdagen_committee_ballot_decision_politician_summary;
REFRESH MATERIALIZED VIEW view_riksdagen_committee_ballot_decision_party_summary;

REFRESH MATERIALIZED VIEW view_riksdagen_committee_ballot_decision_summary;
REFRESH MATERIALIZED VIEW view_riksdagen_committee_decision_type_org_summary;
REFRESH MATERIALIZED VIEW view_riksdagen_committee_decision_type_summary;


REFRESH MATERIALIZED VIEW view_riksdagen_politician_document;
REFRESH MATERIALIZED VIEW view_riksdagen_org_document_daily_summary;
REFRESH MATERIALIZED VIEW view_riksdagen_party_document_daily_summary;
REFRESH MATERIALIZED VIEW view_riksdagen_politician_document_daily_summary;
REFRESH MATERIALIZED VIEW view_riksdagen_document_type_daily_summary;

REFRESH MATERIALIZED VIEW view_worldbank_indicator_data_country_summary;

REFRESH MATERIALIZED VIEW view_riksdagen_party_summary;