@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>GovernmenBodyView\n<size:10>com.hack23.cia.web.impl.ui.application.views.user.govermentbody" as com.hack23.cia.web.impl.ui.application.views.user.govermentbody.GovernmenBodyView [[GovernmenBodyView.html]] {
        {static} +NAME: String
        +GovernmenBodyView(ApplicationContext)
    }

    abstract class "<size:14>AbstractGroupView\n<size:10>com.hack23.cia.web.impl.ui.application.views.user.common" as com.hack23.cia.web.impl.ui.application.views.user.common.AbstractGroupView [[../common/AbstractGroupView.html]]

    com.hack23.cia.web.impl.ui.application.views.user.common.AbstractGroupView <|-- com.hack23.cia.web.impl.ui.application.views.user.govermentbody.GovernmenBodyView

    center footer UMLDoclet 2.0.6, PlantUML 1.2019.12
@enduml
