@startuml
    namespace com.hack23.cia.web.impl.ui.application.views.user.govermentbody {

        class GovernmentBodyRankingView [[GovernmentBodyRankingView.html]] {
            {static} +NAME: String
            +GovernmentBodyRankingView(ApplicationContext)
        }

        class GovernmenBodyView [[GovernmenBodyView.html]] {
            {static} +NAME: String
            +GovernmenBodyView(ApplicationContext)
        }

        com.hack23.cia.web.impl.ui.application.views.user.common.AbstractRankingView <|-- GovernmentBodyRankingView
        com.hack23.cia.web.impl.ui.application.views.user.common.AbstractGroupView <|-- GovernmenBodyView
    }

    namespace com.hack23.cia.web.impl.ui.application.views.user.common {
        abstract class AbstractRankingView [[../common/AbstractRankingView.html]] {
        }
        abstract class AbstractGroupView [[../common/AbstractGroupView.html]] {
        }
    }

    center footer UMLDoclet 2.0.6, PlantUML 1.2019.12
@enduml
