@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>PageActionEventHelper\n<size:10>com.hack23.cia.web.impl.ui.application.action" as com.hack23.cia.web.impl.ui.application.action.PageActionEventHelper [[PageActionEventHelper.html]] {
        {abstract} +createPageEvent(ViewAction, ApplicationEventGroup, String, String, String): void
    }

    center footer UMLDoclet 2.0.7, PlantUML 1.2019.12
@enduml
