@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>EncryptedValue\n<size:10>com.hack23.cia.model.internal.application.secure.impl" as com.hack23.cia.model.internal.application.secure.impl.EncryptedValue [[EncryptedValue.html]] {
        +getId(): Long
        +setId(Long): void
        +getStorage(): String
        +setStorage(String): void
        +getUserId(): String
        +setUserId(String): void
        +getVaultName(): String
        +setVaultName(String): void
    }

    abstract class "<size:14>AbstractModelObjectImpl\n<size:10>com.hack23.cia.model.common.impl" as com.hack23.cia.model.common.impl.AbstractModelObjectImpl

    com.hack23.cia.model.common.impl.AbstractModelObjectImpl <|-- com.hack23.cia.model.internal.application.secure.impl.EncryptedValue

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
