@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ContentSize\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.sizing" as com.hack23.cia.web.impl.ui.application.views.common.sizing.ContentSize [[ContentSize.html]] {
        {static} +FULL_SIZE: String
        {static} +HALF_SIZE: String
    }

    center footer UMLDoclet 2.0.6, PlantUML 1.2019.12
@enduml
