@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>MinistryRankingView\n<size:10>com.hack23.cia.web.impl.ui.application.views.user.goverment" as com.hack23.cia.web.impl.ui.application.views.user.goverment.MinistryRankingView [[MinistryRankingView.html]] {
        {static} +NAME: String
        +MinistryRankingView(ApplicationContext)
    }

    abstract class "<size:14>AbstractRankingView\n<size:10>com.hack23.cia.web.impl.ui.application.views.user.common" as com.hack23.cia.web.impl.ui.application.views.user.common.AbstractRankingView [[../common/AbstractRankingView.html]]

    com.hack23.cia.web.impl.ui.application.views.user.common.AbstractRankingView <|-- com.hack23.cia.web.impl.ui.application.views.user.goverment.MinistryRankingView

    center footer UMLDoclet 2.0.3, PlantUML 1.2019.06
@enduml
