@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>UpdateApplicationConfigurationService\n<size:10>com.hack23.cia.service.impl.action.admin" as com.hack23.cia.service.impl.action.admin.UpdateApplicationConfigurationService [[UpdateApplicationConfigurationService.html]] {
        +processService(UpdateApplicationConfigurationRequest): UpdateApplicationConfigurationResponse
        #createApplicationEventForService(UpdateApplicationConfigurationRequest): CreateApplicationEventRequest
        #createErrorResponse(): UpdateApplicationConfigurationResponse
    }

    abstract class "<size:14>AbstractBusinessServiceImpl\n<size:10>com.hack23.cia.service.impl.action.common" as com.hack23.cia.service.impl.action.common.AbstractBusinessServiceImpl<UpdateApplicationConfigurationRequest, UpdateApplicationConfigurationResponse> [[../common/AbstractBusinessServiceImpl.html]] {
        {abstract} #createErrorResponse(): UpdateApplicationConfigurationResponse
        {abstract} #createApplicationEventForService(UpdateApplicationConfigurationRequest): CreateApplicationEventRequest
    }
    interface "<size:14>BusinessService\n<size:10>com.hack23.cia.service.impl.action.common" as com.hack23.cia.service.impl.action.common.BusinessService<UpdateApplicationConfigurationRequest, UpdateApplicationConfigurationResponse> [[../common/BusinessService.html]] {
        {abstract} +getSupportedService(): Class<? extends ServiceRequest>
        {abstract} +processService(UpdateApplicationConfigurationRequest): UpdateApplicationConfigurationResponse
    }

    com.hack23.cia.service.impl.action.common.AbstractBusinessServiceImpl <|-- com.hack23.cia.service.impl.action.admin.UpdateApplicationConfigurationService
    com.hack23.cia.service.impl.action.common.BusinessService <|.. com.hack23.cia.service.impl.action.admin.UpdateApplicationConfigurationService

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
