module com.hack23.cia.web {
	exports com.hack23.cia.web.impl.ui.application;
	exports com.hack23.cia.web.impl.ui.application.action;
	exports com.hack23.cia.web.impl.ui.application.util;
	exports com.hack23.cia.web.impl.ui.application.web.listener;
	exports com.hack23.cia.web.impl.ui.application.views.admin.system.pagemode;
	exports com.hack23.cia.web.impl.ui.application.views.admin.system;
	exports com.hack23.cia.web.impl.ui.application.views.admin.datasummary.pagemode;
	exports com.hack23.cia.web.impl.ui.application.views.admin.datasummary;
	exports com.hack23.cia.web.impl.ui.application.views.admin.agentoperations.pagemode;
	exports com.hack23.cia.web.impl.ui.application.views.admin.agentoperations;
	exports com.hack23.cia.web.impl.ui.application.views.admin.common;
	exports com.hack23.cia.web.impl.ui.application.views.pageclicklistener;
	exports com.hack23.cia.web.impl.ui.application.views.user.parliament.pagemode;
	exports com.hack23.cia.web.impl.ui.application.views.user.parliament;
	exports com.hack23.cia.web.impl.ui.application.views.user.home.pagemode;
	exports com.hack23.cia.web.impl.ui.application.views.user.home;
	exports com.hack23.cia.web.impl.ui.application.views.user.party.pagemode;
	exports com.hack23.cia.web.impl.ui.application.views.user.party;
	exports com.hack23.cia.web.impl.ui.application.views.user.ballot.pagemode;
	exports com.hack23.cia.web.impl.ui.application.views.user.ballot;
	exports com.hack23.cia.web.impl.ui.application.views.user.country.pagemode;
	exports com.hack23.cia.web.impl.ui.application.views.user.country;
	exports com.hack23.cia.web.impl.ui.application.views.user.goverment.pagemode;
	exports com.hack23.cia.web.impl.ui.application.views.user.goverment;
	exports com.hack23.cia.web.impl.ui.application.views.user.document.pagemode;
	exports com.hack23.cia.web.impl.ui.application.views.user.document;
	exports com.hack23.cia.web.impl.ui.application.views.user.committee.pagemode;
	exports com.hack23.cia.web.impl.ui.application.views.user.committee;
	exports com.hack23.cia.web.impl.ui.application.views.user.politician.pagemode;
	exports com.hack23.cia.web.impl.ui.application.views.user.politician;
	exports com.hack23.cia.web.impl.ui.application.views.user.common;
	exports com.hack23.cia.web.impl.ui.application.views.user.govermentbody.pagemode;
	exports com.hack23.cia.web.impl.ui.application.views.user.govermentbody;
	exports com.hack23.cia.web.impl.ui.application.views.pageclicklisteners.handlers.impl;
	exports com.hack23.cia.web.impl.ui.application.views.pageclicklisteners.handlers.api;
	exports com.hack23.cia.web.impl.ui.application.views.common.labelfactory;
	exports com.hack23.cia.web.impl.ui.application.views.common.formfactory.impl;
	exports com.hack23.cia.web.impl.ui.application.views.common.formfactory.api;
	exports com.hack23.cia.web.impl.ui.application.views.common.pagemode;
	exports com.hack23.cia.web.impl.ui.application.views.common.sizing;
	exports com.hack23.cia.web.impl.ui.application.views.common.viewnames;
	exports com.hack23.cia.web.impl.ui.application.views.common.pagelinks.impl;
	exports com.hack23.cia.web.impl.ui.application.views.common.pagelinks.api;
	exports com.hack23.cia.web.impl.ui.application.views.common.converters;
	exports com.hack23.cia.web.impl.ui.application.views.common.rows;
	exports com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.impl;
	exports com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.api;
	exports com.hack23.cia.web.impl.ui.application.views.common.gridfactory.impl;
	exports com.hack23.cia.web.impl.ui.application.views.common.gridfactory.api;
	exports com.hack23.cia.web.impl.ui.application.views.common.paging;
	exports com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl;
	exports com.hack23.cia.web.impl.ui.application.views.common.menufactory.api;
	exports com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl;
	exports com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api;
	exports com.hack23.cia.web.impl.ui.application.views.common;
	
	opens com.hack23.cia.web.impl.ui.application to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;	
	opens com.hack23.cia.web.impl.ui.application.action to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.util to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.web.listener to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.admin.system.pagemode to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.admin.system to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.admin.datasummary.pagemode to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.admin.datasummary to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.admin.agentoperations.pagemode to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.admin.agentoperations to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.admin.common to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.pageclicklistener to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.user.parliament.pagemode to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.user.parliament to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.user.home.pagemode to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.user.home to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.user.party.pagemode to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.user.party to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.user.ballot.pagemode to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.user.ballot to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.user.country.pagemode to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.user.country to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.user.goverment.pagemode to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.user.goverment to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.user.document.pagemode to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.user.document to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.user.committee.pagemode to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.user.committee to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.user.politician.pagemode to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.user.politician to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.user.common to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.user.govermentbody.pagemode to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.user.govermentbody to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.pageclicklisteners.handlers.impl to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.pageclicklisteners.handlers.api to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.common.labelfactory to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.common.formfactory.impl to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.common.formfactory.api to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.common.pagemode to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.common.sizing to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.common.viewnames to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.common.pagelinks.impl to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.common.pagelinks.api to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.common.converters to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.common.rows to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.impl to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.common.dataseriesfactory.api to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.common.gridfactory.impl to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.common.gridfactory.api to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.common.paging to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.common.menufactory.api to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	opens com.hack23.cia.web.impl.ui.application.views.common to commons.beanutils, javassist, spring.security.core, spring.security.web,spring.aop, spring.core, spring.beans, spring.context, spring.context.support, vaadin.spring, vaadin.server, vaadin.shared, vaadin.compatibility.server, vaadin.compatibility.shared;
	
	requires vaadin.compatibility.shared;
	requires vaadin.compatibility.server;
	requires vaadin.shared;
	requires vaadin.server;
	requires responsive.layout;
	
	requires java.xml.bind;
	requires java.annotation;
	requires org.slf4j;
	requires spring.context;
	requires spring.beans;
	requires spring.tx;
	requires spring.messaging;
	requires spring.context.support;
	requires quartz;
	requires commons.lang;

	requires spring.security.core;
	requires spring.security.web;
	requires org.apache.commons.lang3;

	requires weka.dev;
	requires passay;
	requires wt.pdf.viewer;
	requires spring.aop;
	requires statistics.card;
	requires org.eclipse.jetty.servlet;
	requires vaadin.grid.util;
	requires yauaa;
	requires qrcode;

	requires java.desktop;
	requires org.apache.commons.text;
	requires gantt.addon;
//	requires joda.time;

//	requires jms;
//	requires java.bean;

	requires dcharts;
	requires commons.beanutils;
	requires org.jsoup;
	requires javax.servlet.api;
	requires vaadin.spring;
	requires spring.web;
	requires java.logging;
	requires java.management;
	
	requires transitive com.hack23.cia.web.widgets;
	requires transitive com.hack23.cia.service.api;
	requires transitive com.hack23.cia.service.impl;
	requires transitive com.hack23.cia.service.external.esv;

	requires transitive com.hack23.cia.service.component.agent.api;
	requires transitive com.hack23.cia.service.component.agent.impl;

	requires transitive com.hack23.cia.service.external.common;
    requires transitive com.hack23.cia.service.data.api;
	requires transitive com.hack23.cia.service.external.riksdagen;
	requires transitive com.hack23.cia.service.external.val;
	requires transitive com.hack23.cia.service.external.worldbank;

	requires transitive com.hack23.cia.model.external.val.riksdagsvalkrets.impl;
	requires transitive com.hack23.cia.model.external.riksdagen.voteringlista.impl;
	requires transitive com.hack23.cia.model.external.val.kommunvalkrets.impl;
	requires transitive com.hack23.cia.model.external.worldbank.topic.impl;
	requires transitive com.hack23.cia.model.external.worldbank.indicators.impl;
	requires transitive com.hack23.cia.model.external.riksdagen.documentcontent.impl;
	requires transitive com.hack23.cia.model.external.worldbank.data.impl;
	requires transitive com.hack23.cia.model.external.riksdagen.person.impl;
	requires transitive com.hack23.cia.model.external.riksdagen.dokumentstatus.impl;
	requires transitive com.hack23.cia.model.external.riksdagen.dokumentlista.impl;
	requires transitive com.hack23.cia.model.external.riksdagen.utskottsforslag.impl;
	requires transitive com.hack23.cia.model.external.val.partier.impl;
	requires transitive com.hack23.cia.model.external.riksdagen.personlista.impl;
	requires transitive com.hack23.cia.model.external.val.landstingvalkrets.impl;
	requires transitive com.hack23.cia.model.external.riksdagen.votering.impl;

}