@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>PartyCommitteeBallotDecisionSummaryPageModContentFactoryImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.user.party.pagemode" as com.hack23.cia.web.impl.ui.application.views.user.party.pagemode.PartyCommitteeBallotDecisionSummaryPageModContentFactoryImpl [[PartyCommitteeBallotDecisionSummaryPageModContentFactoryImpl.html]] {
        +createContent(String, MenuBar, Panel): Layout
        +matches(String, String): boolean
    }

    abstract class "<size:14>AbstractItemPageModContentFactoryImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.pagemode" as com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractItemPageModContentFactoryImpl<ViewRiksdagenParty> [[../../../common/pagemode/AbstractItemPageModContentFactoryImpl.html]] {
        {abstract} #getItem(String): ViewRiksdagenParty
    }

    com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractItemPageModContentFactoryImpl <|-- com.hack23.cia.web.impl.ui.application.views.user.party.pagemode.PartyCommitteeBallotDecisionSummaryPageModContentFactoryImpl

    center footer UMLDoclet 2.0.6, PlantUML 1.2019.12
@enduml
