@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    abstract class "<size:14>AbstractActorView\n<size:10>com.hack23.cia.web.impl.ui.application.views.user.common" as com.hack23.cia.web.impl.ui.application.views.user.common.AbstractActorView [[AbstractActorView.html]] {
        +AbstractActorView(Map<String, PageModeContentFactory>, String)
    }

    abstract class "<size:14>AbstractUserView\n<size:10>com.hack23.cia.web.impl.ui.application.views.user.common" as com.hack23.cia.web.impl.ui.application.views.user.common.AbstractUserView [[AbstractUserView.html]]

    com.hack23.cia.web.impl.ui.application.views.user.common.AbstractUserView <|-- com.hack23.cia.web.impl.ui.application.views.user.common.AbstractActorView

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
