@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>ComplianceCheck\n<size:10>com.hack23.cia.service.api.action.kpi" as com.hack23.cia.service.api.action.kpi.ComplianceCheck [[ComplianceCheck.html]] {
        {abstract} +getResourceType(): ResourceType
        {abstract} +getRuleViolations(): List<RuleViolation>
        {abstract} +getNumberRuleViolations(): int
        {abstract} +getRuleSummary(): String
        {abstract} +getId(): String
        {abstract} +getName(): String
    }

    interface "<size:14>Serializable\n<size:10>java.io" as java.io.Serializable

    java.io.Serializable <|.. com.hack23.cia.service.api.action.kpi.ComplianceCheck

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
