@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    enum "<size:14>ResourceType\n<size:10>com.hack23.cia.service.api.action.kpi" as com.hack23.cia.service.api.action.kpi.ResourceType [[ResourceType.html]] {
        {static} +POLITICIAN
        {static} +PARTY
        {static} +PARTY_LEADER
        {static} +COMMITTEE
        {static} +MINISTRY
        {static} +GOVERNMENT
        {static} +MINISTER
    }

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
