@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>FormFactory\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.formfactory.api" as com.hack23.cia.web.impl.ui.application.views.common.formfactory.api.FormFactory [[FormFactory.html]] {
        {abstract} +addFormPanelTextFields(AbstractOrderedLayout, T extends Serializable, Class<T extends Serializable>, List<String>): void
        {abstract} +addRequestInputFormFields(FormLayout, T extends Serializable, Class<T extends Serializable>, List<String>, String, ClickListener): void
    }

    center footer UMLDoclet 2.0.7, PlantUML 1.2019.12
@enduml
