@startuml
    namespace com.hack23.cia.web.impl.ui.application.views.common.pagelinks.api {

        interface PageLinkFactory [[PageLinkFactory.html]] {
            {abstract} +addCommitteePageLink(ViewRiksdagenCommittee): Link
            {abstract} +addMinistryPageLink(ViewRiksdagenMinistry): Link
            {abstract} +addPartyPageLink(ViewRiksdagenParty): Link
            {abstract} +createAdminPagingLink(String, String, String, String): Link
            {abstract} +createLoginPageLink(): Link
            {abstract} +createMainViewPageLink(): Link
            {abstract} +createPoliticianPageLink(PersonData): Link
            {abstract} +createRegisterPageLink(): Link
            {abstract} +createUserHomeViewPageLink(): Link
        }

        class PageModeMenuCommand [[PageModeMenuCommand.html]] {
            +PageModeMenuCommand(String, PageMode)
            +PageModeMenuCommand(String, PageMode, String)
            +PageModeMenuCommand(String, String)
            +PageModeMenuCommand(String, String, String)
            +buttonClick(ClickEvent): void
            +getPagePath(): String
            +menuSelected(MenuItem): void
        }

        com.vaadin.ui.MenuBar.Command <|.. PageModeMenuCommand
        com.vaadin.ui.Button.ClickListener <|.. PageModeMenuCommand
    }

    namespace com.vaadin.ui {
        interface com.vaadin.ui.MenuBar.Command {
            {abstract} +menuSelected(MenuItem): void
        }
        interface com.vaadin.ui.Button.ClickListener {
            {static} +BUTTON_CLICK_METHOD: Method
            {abstract} +buttonClick(ClickEvent): void
        }
    }

    center footer UMLDoclet 2.0.7, PlantUML 1.2019.12
@enduml
