@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>PageModeMenuCommand\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.pagelinks.api" as com.hack23.cia.web.impl.ui.application.views.common.pagelinks.api.PageModeMenuCommand [[PageModeMenuCommand.html]] {
        +PageModeMenuCommand(String, PageMode)
        +PageModeMenuCommand(String, PageMode, String)
        +PageModeMenuCommand(String, String)
        +PageModeMenuCommand(String, String, String)
        +buttonClick(ClickEvent): void
        +getPagePath(): String
        +menuSelected(MenuItem): void
    }

    interface "<size:14>MenuBar.Command\n<size:10>com.vaadin.ui" as com.vaadin.ui.MenuBar.Command {
        {abstract} +menuSelected(MenuItem): void
    }
    interface "<size:14>Button.ClickListener\n<size:10>com.vaadin.ui" as com.vaadin.ui.Button.ClickListener {
        {abstract} +buttonClick(ClickEvent): void
    }

    com.vaadin.ui.MenuBar.Command <|.. com.hack23.cia.web.impl.ui.application.views.common.pagelinks.api.PageModeMenuCommand
    com.vaadin.ui.Button.ClickListener <|.. com.hack23.cia.web.impl.ui.application.views.common.pagelinks.api.PageModeMenuCommand

    center footer UMLDoclet 2.0.12, PlantUML 1.2020.16
@enduml
