@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>AdminViews\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.viewnames" as com.hack23.cia.web.impl.ui.application.views.common.viewnames.AdminViews [[AdminViews.html]] {
        {static} +ADMIN_AGENCY_VIEW_NAME: String
        {static} +ADMIN_AGENT_OPERATIONVIEW_NAME: String
        {static} +ADMIN_APPLICATIONS_CONFIGURATION_VIEW_NAME: String
        {static} +ADMIN_APPLICATIONS_EVENTS_VIEW_NAME: String
        {static} +ADMIN_APPLICATIONS_SESSION_VIEW_NAME: String
        {static} +ADMIN_COUNTRY_VIEW_NAME: String
        {static} +ADMIN_DATA_SUMMARY_VIEW_NAME: String
        {static} +ADMIN_EMAIL_VIEW_NAME: String
        {static} +ADMIN_LANGUAGE_CONTENT_VIEW_NAME: String
        {static} +ADMIN_LANGUAGE_VIEW_NAME: String
        {static} +ADMIN_MONITORING_VIEW_NAME: String
        {static} +ADMIN_PORTAL_VIEW_NAME: String
        {static} +ADMIN_USERACCOUNT_VIEW_NAME: String
    }

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
