@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    enum "<size:14>ApplicationPageMode\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.viewnames" as com.hack23.cia.web.impl.ui.application.views.common.viewnames.ApplicationPageMode [[ApplicationPageMode.html]] {
        {static} +LOGIN
        {static} +LOGOUT
        {static} +REGISTER
    }

    center footer UMLDoclet 2.0.4, PlantUML 1.2019.06
@enduml
