@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    enum "<size:14>ChartIndicators\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.viewnames" as com.hack23.cia.web.impl.ui.application.views.common.viewnames.ChartIndicators [[ChartIndicators.html]] {
        {static} +PARTYWINNER
        {static} +PARTYGENDER
        {static} +PARTYAGE
        {static} +DOCUMENTACTIVITYBYTYPE
        {static} +DECISIONACTIVITYBYTYPE
        {static} +ALLMINISTRIESBYHEADCOUNT
        {static} +CURRENTMINISTRIESBYHEADCOUNT
        {static} +ALLMINISTRIESPARTYBYTOTALDAYS
        {static} +CURRENTPARTIESBYHEADCOUNT
        {static} +ALLCOMMITTEESBYHEADCOUNT
        {static} +COMMITTEESBYPARTY
        {static} +CURRENTCOMMITTEESBYHEADCOUNT
        {static} +CURRENTCOMMITTEESBYPARTYDAYSSERVED
        {static} +ALLPARTIES
        {static} +CURRENTCOMMITTEES
        {static} +CURRENTGOVERMENTPARTIES
        {static} +CURRENTPARTIES
        {static} +ALL_GOVERNMENT_ROLE_CHART
        {static} +DECISION_FLOW_CHART
    }

    center footer UMLDoclet 2.0.3, PlantUML 1.2019.06
@enduml
