@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>CommonsViews\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.viewnames" as com.hack23.cia.web.impl.ui.application.views.common.viewnames.CommonsViews [[CommonsViews.html]] {
        {static} +MAIN_VIEW_NAME: String
    }

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
