@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    enum "<size:14>GovernmentBodyPageMode\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.viewnames" as com.hack23.cia.web.impl.ui.application.views.common.viewnames.GovernmentBodyPageMode [[GovernmentBodyPageMode.html]] {
        {static} +EXPENDITURE
        {static} +HEADCOUNT
        {static} +INCOME
    }

    center footer UMLDoclet 2.0.6, PlantUML 1.2019.12
@enduml
