@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>PartyRankingMenuItemFactoryImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl" as com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl.PartyRankingMenuItemFactoryImpl [[PartyRankingMenuItemFactoryImpl.html]] {
        +createOverviewPage(VerticalLayout): void
        +createPartyRankingMenuBar(MenuBar): void
        +createPartyRankingTopics(MenuItem): void
    }

    abstract class "<size:14>AbstractMenuItemFactoryImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl" as com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl.AbstractMenuItemFactoryImpl [[AbstractMenuItemFactoryImpl.html]]
    interface "<size:14>PartyRankingMenuItemFactory\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.menufactory.api" as com.hack23.cia.web.impl.ui.application.views.common.menufactory.api.PartyRankingMenuItemFactory [[../api/PartyRankingMenuItemFactory.html]] {
        {abstract} +createOverviewPage(VerticalLayout): void
        {abstract} +createPartyRankingMenuBar(MenuBar): void
        {abstract} +createPartyRankingTopics(MenuItem): void
    }

    com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl.AbstractMenuItemFactoryImpl <|-- com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl.PartyRankingMenuItemFactoryImpl
    com.hack23.cia.web.impl.ui.application.views.common.menufactory.api.PartyRankingMenuItemFactory <|.. com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl.PartyRankingMenuItemFactoryImpl

    center footer UMLDoclet 2.0.4, PlantUML 1.2019.06
@enduml
