@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>PoliticianMenuItemFactoryImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl" as com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl.PoliticianMenuItemFactoryImpl [[PoliticianMenuItemFactoryImpl.html]] {
        +createPoliticianMenuBar(MenuBar, String): void
        +createOverviewPage(VerticalLayout, String): void
    }

    abstract class "<size:14>AbstractMenuItemFactoryImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl" as com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl.AbstractMenuItemFactoryImpl [[AbstractMenuItemFactoryImpl.html]]
    interface "<size:14>PoliticianMenuItemFactory\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.menufactory.api" as com.hack23.cia.web.impl.ui.application.views.common.menufactory.api.PoliticianMenuItemFactory [[../api/PoliticianMenuItemFactory.html]] {
        {abstract} +createPoliticianMenuBar(MenuBar, String): void
        {abstract} +createOverviewPage(VerticalLayout, String): void
    }

    com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl.AbstractMenuItemFactoryImpl <|-- com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl.PoliticianMenuItemFactoryImpl
    com.hack23.cia.web.impl.ui.application.views.common.menufactory.api.PoliticianMenuItemFactory <|.. com.hack23.cia.web.impl.ui.application.views.common.menufactory.impl.PoliticianMenuItemFactoryImpl

    center footer UMLDoclet 2.0.3, PlantUML 1.2019.06
@enduml
