@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SearchDocumentResponseHandlerImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.pageclicklisteners.handlers.impl" as com.hack23.cia.web.impl.ui.application.views.pageclicklisteners.handlers.impl.SearchDocumentResponseHandlerImpl [[SearchDocumentResponseHandlerImpl.html]] {
        +SearchDocumentResponseHandlerImpl(GridFactory, Panel, VerticalLayout)
        +handle(SearchDocumentResponse): void
    }

    interface "<size:14>SearchDocumentResponseHandler\n<size:10>com.hack23.cia.web.impl.ui.application.views.pageclicklisteners.handlers.api" as com.hack23.cia.web.impl.ui.application.views.pageclicklisteners.handlers.api.SearchDocumentResponseHandler [[../api/SearchDocumentResponseHandler.html]] {
        {abstract} +handle(SearchDocumentResponse): void
    }

    com.hack23.cia.web.impl.ui.application.views.pageclicklisteners.handlers.api.SearchDocumentResponseHandler <|.. com.hack23.cia.web.impl.ui.application.views.pageclicklisteners.handlers.impl.SearchDocumentResponseHandlerImpl

    center footer UMLDoclet 2.0.12, PlantUML 1.2020.16
@enduml
