@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>AgentOperationView\n<size:10>com.hack23.cia.web.impl.ui.application.views.admin.agentoperations" as com.hack23.cia.web.impl.ui.application.views.admin.agentoperations.AgentOperationView [[AgentOperationView.html]] {
        {static} +NAME: String
        +AgentOperationView(ApplicationContext)
    }

    abstract class "<size:14>AbstractAdminView\n<size:10>com.hack23.cia.web.impl.ui.application.views.admin.common" as com.hack23.cia.web.impl.ui.application.views.admin.common.AbstractAdminView [[../common/AbstractAdminView.html]]

    com.hack23.cia.web.impl.ui.application.views.admin.common.AbstractAdminView <|-- com.hack23.cia.web.impl.ui.application.views.admin.agentoperations.AgentOperationView

    center footer UMLDoclet 2.0.3, PlantUML 1.2019.06
@enduml
