@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>AuthorizationFailureEventListener\n<size:10>com.hack23.cia.web.impl.ui.application.web.listener" as com.hack23.cia.web.impl.ui.application.web.listener.AuthorizationFailureEventListener [[AuthorizationFailureEventListener.html]] {
        +onApplicationEvent(AuthorizationFailureEvent): void
    }

    interface "<size:14>ApplicationListener\n<size:10>org.springframework.context" as org.springframework.context.ApplicationListener<AuthorizationFailureEvent> {
        {abstract} +onApplicationEvent(AuthorizationFailureEvent): void
    }

    org.springframework.context.ApplicationListener <|.. com.hack23.cia.web.impl.ui.application.web.listener.AuthorizationFailureEventListener

    center footer UMLDoclet 2.0.4, PlantUML 1.2019.06
@enduml
