@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SecurityAuthenticationProvider\n<size:10>com.hack23.cia.service.impl" as com.hack23.cia.service.impl.SecurityAuthenticationProvider [[SecurityAuthenticationProvider.html]] {
        +authenticate(Authentication): Authentication
        +supports(Class<?>): boolean
    }

    interface "<size:14>AuthenticationProvider\n<size:10>org.springframework.security.authentication" as org.springframework.security.authentication.AuthenticationProvider {
        {abstract} +authenticate(Authentication): Authentication
        {abstract} +supports(Class<?>): boolean
    }

    org.springframework.security.authentication.AuthenticationProvider <|.. com.hack23.cia.service.impl.SecurityAuthenticationProvider

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
