# --------------------------------------- 
# Module: ee8-websocket-javax
# Enable the Jetty 12 EE8 websocket-javax module for deployed web applications.
# --------------------------------------- 
--module=ee8-websocket-javax


