@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>CountryMenuItemFactory\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.menufactory.api" as com.hack23.cia.web.impl.ui.application.views.common.menufactory.api.CountryMenuItemFactory [[CountryMenuItemFactory.html]] {
        {abstract} +createCountryTopicMenu(MenuBar): void
        {abstract} +createCountryTopicMenu(MenuItem): void
        {abstract} +createOverviewPage(VerticalLayout): void
    }

    center footer UMLDoclet 2.0.3, PlantUML 1.2019.06
@enduml
