@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>GovernmentBodyMenuItemFactory\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.menufactory.api" as com.hack23.cia.web.impl.ui.application.views.common.menufactory.api.GovernmentBodyMenuItemFactory [[GovernmentBodyMenuItemFactory.html]] {
        {abstract} +createGovernmentBodyMenuBar(MenuBar, String): void
        {abstract} +createOverviewPage(VerticalLayout, String): void
    }

    center footer UMLDoclet 2.0.12, PlantUML 1.2020.16
@enduml
