@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>ChangePasswordService\n<size:10>com.hack23.cia.service.impl.action.user" as com.hack23.cia.service.impl.action.user.ChangePasswordService [[ChangePasswordService.html]] {
        +processService(ChangePasswordRequest): ChangePasswordResponse
        #createApplicationEventForService(ChangePasswordRequest): CreateApplicationEventRequest
        #createErrorResponse(): ChangePasswordResponse
    }

    abstract class "<size:14>AbstractBusinessServiceImpl\n<size:10>com.hack23.cia.service.impl.action.common" as com.hack23.cia.service.impl.action.common.AbstractBusinessServiceImpl<ChangePasswordRequest, ChangePasswordResponse> [[../common/AbstractBusinessServiceImpl.html]] {
        {abstract} #createErrorResponse(): ChangePasswordResponse
        {abstract} #createApplicationEventForService(ChangePasswordRequest): CreateApplicationEventRequest
    }
    interface "<size:14>BusinessService\n<size:10>com.hack23.cia.service.impl.action.common" as com.hack23.cia.service.impl.action.common.BusinessService<ChangePasswordRequest, ChangePasswordResponse> [[../common/BusinessService.html]] {
        {abstract} +getSupportedService(): Class<? extends ServiceRequest>
        {abstract} +processService(ChangePasswordRequest): ChangePasswordResponse
    }

    com.hack23.cia.service.impl.action.common.AbstractBusinessServiceImpl <|-- com.hack23.cia.service.impl.action.user.ChangePasswordService
    com.hack23.cia.service.impl.action.common.BusinessService <|.. com.hack23.cia.service.impl.action.user.ChangePasswordService

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
