@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>DocumentWordCountService\n<size:10>com.hack23.cia.service.impl.action.user" as com.hack23.cia.service.impl.action.user.DocumentWordCountService [[DocumentWordCountService.html]] {
        +processService(DocumentWordCountRequest): DocumentWordCountResponse
        #createApplicationEventForService(DocumentWordCountRequest): CreateApplicationEventRequest
        #createErrorResponse(): DocumentWordCountResponse
    }

    abstract class "<size:14>AbstractBusinessServiceImpl\n<size:10>com.hack23.cia.service.impl.action.common" as com.hack23.cia.service.impl.action.common.AbstractBusinessServiceImpl<DocumentWordCountRequest, DocumentWordCountResponse> [[../common/AbstractBusinessServiceImpl.html]] {
        {abstract} #createErrorResponse(): DocumentWordCountResponse
        {abstract} #createApplicationEventForService(DocumentWordCountRequest): CreateApplicationEventRequest
    }
    interface "<size:14>BusinessService\n<size:10>com.hack23.cia.service.impl.action.common" as com.hack23.cia.service.impl.action.common.BusinessService<DocumentWordCountRequest, DocumentWordCountResponse> [[../common/BusinessService.html]] {
        {abstract} +getSupportedService(): Class<? extends ServiceRequest>
        {abstract} +processService(DocumentWordCountRequest): DocumentWordCountResponse
    }

    com.hack23.cia.service.impl.action.common.AbstractBusinessServiceImpl <|-- com.hack23.cia.service.impl.action.user.DocumentWordCountService
    com.hack23.cia.service.impl.action.common.BusinessService <|.. com.hack23.cia.service.impl.action.user.DocumentWordCountService

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
