@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>DocumentWordCountRequest\n<size:10>com.hack23.cia.service.api.action.user" as com.hack23.cia.service.api.action.user.DocumentWordCountRequest [[DocumentWordCountRequest.html]] {
        +getSessionId(): String
        +setSessionId(String): void
        +getMaxResults(): int
        +setMaxResults(int): void
        +getDocumentId(): String
        +setDocumentId(String): void
    }

    abstract class "<size:14>AbstractRequest\n<size:10>com.hack23.cia.service.api.action.common" as com.hack23.cia.service.api.action.common.AbstractRequest [[../common/AbstractRequest.html]]

    com.hack23.cia.service.api.action.common.AbstractRequest <|-- com.hack23.cia.service.api.action.user.DocumentWordCountRequest

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
