//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.25 at 12:05:09 AM CET 
//


package com.hack23.cia.model.internal.application.data.committee.impl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hack23.cia.model.internal.application.data.committee.impl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hack23.cia.model.internal.application.data.committee.impl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ViewRiksdagenCommittee }
     * 
     */
    public ViewRiksdagenCommittee createViewRiksdagenCommittee() {
        return new ViewRiksdagenCommittee();
    }

    /**
     * Create an instance of {@link ViewRiksdagenCommitteeRoleMember }
     * 
     */
    public ViewRiksdagenCommitteeRoleMember createViewRiksdagenCommitteeRoleMember() {
        return new ViewRiksdagenCommitteeRoleMember();
    }

    /**
     * Create an instance of {@link ViewRiksdagenVoteDataBallotSummary }
     * 
     */
    public ViewRiksdagenVoteDataBallotSummary createViewRiksdagenVoteDataBallotSummary() {
        return new ViewRiksdagenVoteDataBallotSummary();
    }

    /**
     * Create an instance of {@link RiksdagenVoteDataBallotEmbeddedId }
     * 
     */
    public RiksdagenVoteDataBallotEmbeddedId createRiksdagenVoteDataBallotEmbeddedId() {
        return new RiksdagenVoteDataBallotEmbeddedId();
    }

    /**
     * Create an instance of {@link ViewRiksdagenVoteDataBallotPartySummary }
     * 
     */
    public ViewRiksdagenVoteDataBallotPartySummary createViewRiksdagenVoteDataBallotPartySummary() {
        return new ViewRiksdagenVoteDataBallotPartySummary();
    }

    /**
     * Create an instance of {@link RiksdagenVoteDataBallotPartyEmbeddedId }
     * 
     */
    public RiksdagenVoteDataBallotPartyEmbeddedId createRiksdagenVoteDataBallotPartyEmbeddedId() {
        return new RiksdagenVoteDataBallotPartyEmbeddedId();
    }

    /**
     * Create an instance of {@link ViewRiksdagenVoteDataBallotPoliticianSummary }
     * 
     */
    public ViewRiksdagenVoteDataBallotPoliticianSummary createViewRiksdagenVoteDataBallotPoliticianSummary() {
        return new ViewRiksdagenVoteDataBallotPoliticianSummary();
    }

    /**
     * Create an instance of {@link RiksdagenVoteDataBallotPoliticianEmbeddedId }
     * 
     */
    public RiksdagenVoteDataBallotPoliticianEmbeddedId createRiksdagenVoteDataBallotPoliticianEmbeddedId() {
        return new RiksdagenVoteDataBallotPoliticianEmbeddedId();
    }

    /**
     * Create an instance of {@link ViewRiksdagenVoteDataBallotSummaryDaily }
     * 
     */
    public ViewRiksdagenVoteDataBallotSummaryDaily createViewRiksdagenVoteDataBallotSummaryDaily() {
        return new ViewRiksdagenVoteDataBallotSummaryDaily();
    }

    /**
     * Create an instance of {@link ViewRiksdagenVoteDataBallotSummaryWeekly }
     * 
     */
    public ViewRiksdagenVoteDataBallotSummaryWeekly createViewRiksdagenVoteDataBallotSummaryWeekly() {
        return new ViewRiksdagenVoteDataBallotSummaryWeekly();
    }

    /**
     * Create an instance of {@link ViewRiksdagenVoteDataBallotSummaryMonthly }
     * 
     */
    public ViewRiksdagenVoteDataBallotSummaryMonthly createViewRiksdagenVoteDataBallotSummaryMonthly() {
        return new ViewRiksdagenVoteDataBallotSummaryMonthly();
    }

    /**
     * Create an instance of {@link ViewRiksdagenVoteDataBallotSummaryAnnual }
     * 
     */
    public ViewRiksdagenVoteDataBallotSummaryAnnual createViewRiksdagenVoteDataBallotSummaryAnnual() {
        return new ViewRiksdagenVoteDataBallotSummaryAnnual();
    }

    /**
     * Create an instance of {@link RiksdagenVoteDataBallotPoliticianPeriodSummaryEmbeddedId }
     * 
     */
    public RiksdagenVoteDataBallotPoliticianPeriodSummaryEmbeddedId createRiksdagenVoteDataBallotPoliticianPeriodSummaryEmbeddedId() {
        return new RiksdagenVoteDataBallotPoliticianPeriodSummaryEmbeddedId();
    }

    /**
     * Create an instance of {@link RiksdagenVoteDataBallotPartyPeriodSummaryEmbeddedId }
     * 
     */
    public RiksdagenVoteDataBallotPartyPeriodSummaryEmbeddedId createRiksdagenVoteDataBallotPartyPeriodSummaryEmbeddedId() {
        return new RiksdagenVoteDataBallotPartyPeriodSummaryEmbeddedId();
    }

    /**
     * Create an instance of {@link ViewRiksdagenVoteDataBallotPartySummaryDaily }
     * 
     */
    public ViewRiksdagenVoteDataBallotPartySummaryDaily createViewRiksdagenVoteDataBallotPartySummaryDaily() {
        return new ViewRiksdagenVoteDataBallotPartySummaryDaily();
    }

    /**
     * Create an instance of {@link ViewRiksdagenVoteDataBallotPartySummaryWeekly }
     * 
     */
    public ViewRiksdagenVoteDataBallotPartySummaryWeekly createViewRiksdagenVoteDataBallotPartySummaryWeekly() {
        return new ViewRiksdagenVoteDataBallotPartySummaryWeekly();
    }

    /**
     * Create an instance of {@link ViewRiksdagenVoteDataBallotPartySummaryMonthly }
     * 
     */
    public ViewRiksdagenVoteDataBallotPartySummaryMonthly createViewRiksdagenVoteDataBallotPartySummaryMonthly() {
        return new ViewRiksdagenVoteDataBallotPartySummaryMonthly();
    }

    /**
     * Create an instance of {@link ViewRiksdagenVoteDataBallotPartySummaryAnnual }
     * 
     */
    public ViewRiksdagenVoteDataBallotPartySummaryAnnual createViewRiksdagenVoteDataBallotPartySummaryAnnual() {
        return new ViewRiksdagenVoteDataBallotPartySummaryAnnual();
    }

    /**
     * Create an instance of {@link ViewRiksdagenVoteDataBallotPoliticianSummaryDaily }
     * 
     */
    public ViewRiksdagenVoteDataBallotPoliticianSummaryDaily createViewRiksdagenVoteDataBallotPoliticianSummaryDaily() {
        return new ViewRiksdagenVoteDataBallotPoliticianSummaryDaily();
    }

    /**
     * Create an instance of {@link ViewRiksdagenVoteDataBallotPoliticianSummaryWeekly }
     * 
     */
    public ViewRiksdagenVoteDataBallotPoliticianSummaryWeekly createViewRiksdagenVoteDataBallotPoliticianSummaryWeekly() {
        return new ViewRiksdagenVoteDataBallotPoliticianSummaryWeekly();
    }

    /**
     * Create an instance of {@link ViewRiksdagenVoteDataBallotPoliticianSummaryMonthly }
     * 
     */
    public ViewRiksdagenVoteDataBallotPoliticianSummaryMonthly createViewRiksdagenVoteDataBallotPoliticianSummaryMonthly() {
        return new ViewRiksdagenVoteDataBallotPoliticianSummaryMonthly();
    }

    /**
     * Create an instance of {@link ViewRiksdagenVoteDataBallotPoliticianSummaryAnnual }
     * 
     */
    public ViewRiksdagenVoteDataBallotPoliticianSummaryAnnual createViewRiksdagenVoteDataBallotPoliticianSummaryAnnual() {
        return new ViewRiksdagenVoteDataBallotPoliticianSummaryAnnual();
    }

    /**
     * Create an instance of {@link RiksdagenCommitteeDecisionTypeSummaryEmbeddedId }
     * 
     */
    public RiksdagenCommitteeDecisionTypeSummaryEmbeddedId createRiksdagenCommitteeDecisionTypeSummaryEmbeddedId() {
        return new RiksdagenCommitteeDecisionTypeSummaryEmbeddedId();
    }

    /**
     * Create an instance of {@link ViewRiksdagenCommitteeDecisionTypeDailySummary }
     * 
     */
    public ViewRiksdagenCommitteeDecisionTypeDailySummary createViewRiksdagenCommitteeDecisionTypeDailySummary() {
        return new ViewRiksdagenCommitteeDecisionTypeDailySummary();
    }

    /**
     * Create an instance of {@link RiksdagenCommitteeDecisionTypeOrgSummaryEmbeddedId }
     * 
     */
    public RiksdagenCommitteeDecisionTypeOrgSummaryEmbeddedId createRiksdagenCommitteeDecisionTypeOrgSummaryEmbeddedId() {
        return new RiksdagenCommitteeDecisionTypeOrgSummaryEmbeddedId();
    }

    /**
     * Create an instance of {@link ViewRiksdagenCommitteeDecisionTypeOrgDailySummary }
     * 
     */
    public ViewRiksdagenCommitteeDecisionTypeOrgDailySummary createViewRiksdagenCommitteeDecisionTypeOrgDailySummary() {
        return new ViewRiksdagenCommitteeDecisionTypeOrgDailySummary();
    }

    /**
     * Create an instance of {@link ViewRiksdagenCommitteeDecisionsEmbeddedId }
     * 
     */
    public ViewRiksdagenCommitteeDecisionsEmbeddedId createViewRiksdagenCommitteeDecisionsEmbeddedId() {
        return new ViewRiksdagenCommitteeDecisionsEmbeddedId();
    }

    /**
     * Create an instance of {@link ViewRiksdagenCommitteeDecisions }
     * 
     */
    public ViewRiksdagenCommitteeDecisions createViewRiksdagenCommitteeDecisions() {
        return new ViewRiksdagenCommitteeDecisions();
    }

    /**
     * Create an instance of {@link ViewRiksdagenCommitteeBallotDecisionEmbeddedId }
     * 
     */
    public ViewRiksdagenCommitteeBallotDecisionEmbeddedId createViewRiksdagenCommitteeBallotDecisionEmbeddedId() {
        return new ViewRiksdagenCommitteeBallotDecisionEmbeddedId();
    }

    /**
     * Create an instance of {@link ViewRiksdagenCommitteeBallotDecisionPartyEmbeddedId }
     * 
     */
    public ViewRiksdagenCommitteeBallotDecisionPartyEmbeddedId createViewRiksdagenCommitteeBallotDecisionPartyEmbeddedId() {
        return new ViewRiksdagenCommitteeBallotDecisionPartyEmbeddedId();
    }

    /**
     * Create an instance of {@link ViewRiksdagenCommitteeBallotDecisionPoliticianEmbeddedId }
     * 
     */
    public ViewRiksdagenCommitteeBallotDecisionPoliticianEmbeddedId createViewRiksdagenCommitteeBallotDecisionPoliticianEmbeddedId() {
        return new ViewRiksdagenCommitteeBallotDecisionPoliticianEmbeddedId();
    }

    /**
     * Create an instance of {@link ViewRiksdagenCommitteeBallotDecisionSummary }
     * 
     */
    public ViewRiksdagenCommitteeBallotDecisionSummary createViewRiksdagenCommitteeBallotDecisionSummary() {
        return new ViewRiksdagenCommitteeBallotDecisionSummary();
    }

    /**
     * Create an instance of {@link ViewRiksdagenCommitteeBallotDecisionPartySummary }
     * 
     */
    public ViewRiksdagenCommitteeBallotDecisionPartySummary createViewRiksdagenCommitteeBallotDecisionPartySummary() {
        return new ViewRiksdagenCommitteeBallotDecisionPartySummary();
    }

    /**
     * Create an instance of {@link ViewRiksdagenCommitteeBallotDecisionPoliticianSummary }
     * 
     */
    public ViewRiksdagenCommitteeBallotDecisionPoliticianSummary createViewRiksdagenCommitteeBallotDecisionPoliticianSummary() {
        return new ViewRiksdagenCommitteeBallotDecisionPoliticianSummary();
    }

    /**
     * Create an instance of {@link RiksdagenCommitteeEmbeddedId }
     * 
     */
    public RiksdagenCommitteeEmbeddedId createRiksdagenCommitteeEmbeddedId() {
        return new RiksdagenCommitteeEmbeddedId();
    }

}
