//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.25 at 12:05:09 AM CET 
//


package com.hack23.cia.model.internal.application.data.committee.impl;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import com.hack23.cia.model.common.api.ModelObject;
import com.hack23.cia.model.common.impl.xml.XmlDateTypeAdapter;


/**
 * <p>Java class for ViewRiksdagenCommitteeDecisions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ViewRiksdagenCommitteeDecisions"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="embeddedId" type="{http://committee.data.application.internal.model.cia.hack23.com/impl}ViewRiksdagenCommitteeDecisionsEmbeddedId"/&gt;
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="header" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="committee_report" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="rm" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="end_number" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="org" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="created_date" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="public_date" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="committee_proposal_url_xml" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="decision_type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ballot_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="against_proposal_parties" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="against_proposal_number" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="winner" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ViewRiksdagenCommitteeDecisions", propOrder = {
    "embeddedId",
    "title",
    "header",
    "committeeReport",
    "rm",
    "endNumber",
    "org",
    "createdDate",
    "publicDate",
    "committeeProposalUrlXml",
    "decisionType",
    "ballotId",
    "againstProposalParties",
    "againstProposalNumber",
    "winner"
})
@Entity(name = "ViewRiksdagenCommitteeDecisions")
@Table(name = "View_Riksdagen_Committee_Decisions")
@Inheritance(strategy = InheritanceType.JOINED)
public class ViewRiksdagenCommitteeDecisions
    implements ModelObject, Equals
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@XmlElement(required = true)
    protected ViewRiksdagenCommitteeDecisionsEmbeddedId embeddedId;
    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String header;
    @XmlElement(name = "committee_report", required = true)
    protected String committeeReport;
    @XmlElement(required = true)
    protected String rm;
    @XmlElement(name = "end_number", required = true)
    protected BigDecimal endNumber;
    @XmlElement(required = true)
    protected String org;
    @XmlElement(name = "created_date", required = true, type = String.class)
    @XmlJavaTypeAdapter(XmlDateTypeAdapter.class)
    @XmlSchemaType(name = "date")
    protected Date createdDate;
    @XmlElement(name = "public_date", required = true, type = String.class)
    @XmlJavaTypeAdapter(XmlDateTypeAdapter.class)
    @XmlSchemaType(name = "date")
    protected Date publicDate;
    @XmlElement(name = "committee_proposal_url_xml", required = true)
    protected String committeeProposalUrlXml;
    @XmlElement(name = "decision_type", required = true)
    protected String decisionType;
    @XmlElement(name = "ballot_id", required = true)
    protected String ballotId;
    @XmlElement(name = "against_proposal_parties", required = true)
    protected String againstProposalParties;
    @XmlElement(name = "against_proposal_number", required = true)
    protected BigDecimal againstProposalNumber;
    @XmlElement(required = true)
    protected String winner;

    /**
     * Gets the value of the embeddedId property.
     * 
     * @return
     *     possible object is
     *     {@link ViewRiksdagenCommitteeDecisionsEmbeddedId }
     *     
     */
    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "id", column = @Column(name = "EMBEDDED_ID_ID")),
        @AttributeOverride(name = "hangarId", column = @Column(name = "EMBEDDED_ID_HANGAR_ID", precision = 20, scale = 10)),
        @AttributeOverride(name = "issueNummer", column = @Column(name = "EMBEDDED_ID_ISSUE_NUMMER", precision = 20, scale = 10))
    })
    public ViewRiksdagenCommitteeDecisionsEmbeddedId getEmbeddedId() {
        return embeddedId;
    }

    /**
     * Sets the value of the embeddedId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ViewRiksdagenCommitteeDecisionsEmbeddedId }
     *     
     */
    public void setEmbeddedId(final ViewRiksdagenCommitteeDecisionsEmbeddedId value) {
        this.embeddedId = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "TITLE")
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(final String value) {
        this.title = value;
    }

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "HEADER")
    public String getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeader(final String value) {
        this.header = value;
    }

    /**
     * Gets the value of the committeeReport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "COMMITTEE_REPORT")
    public String getCommitteeReport() {
        return committeeReport;
    }

    /**
     * Sets the value of the committeeReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommitteeReport(final String value) {
        this.committeeReport = value;
    }

    /**
     * Gets the value of the rm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "RM")
    public String getRm() {
        return rm;
    }

    /**
     * Sets the value of the rm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRm(final String value) {
        this.rm = value;
    }

    /**
     * Gets the value of the endNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    @Basic
    @Column(name = "END_NUMBER", precision = 20, scale = 10)
    public BigDecimal getEndNumber() {
        return endNumber;
    }

    /**
     * Sets the value of the endNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEndNumber(final BigDecimal value) {
        this.endNumber = value;
    }

    /**
     * Gets the value of the org property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "ORG")
    public String getOrg() {
        return org;
    }

    /**
     * Sets the value of the org property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrg(final String value) {
        this.org = value;
    }

    /**
     * Gets the value of the createdDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "CREATED_DATE")
    @Temporal(TemporalType.DATE)
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the value of the createdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedDate(final Date value) {
        this.createdDate = value;
    }

    /**
     * Gets the value of the publicDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "PUBLIC_DATE")
    @Temporal(TemporalType.DATE)
    public Date getPublicDate() {
        return publicDate;
    }

    /**
     * Sets the value of the publicDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicDate(final Date value) {
        this.publicDate = value;
    }

    /**
     * Gets the value of the committeeProposalUrlXml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "COMMITTEE_PROPOSAL_URL_XML")
    public String getCommitteeProposalUrlXml() {
        return committeeProposalUrlXml;
    }

    /**
     * Sets the value of the committeeProposalUrlXml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommitteeProposalUrlXml(final String value) {
        this.committeeProposalUrlXml = value;
    }

    /**
     * Gets the value of the decisionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "DECISION_TYPE")
    public String getDecisionType() {
        return decisionType;
    }

    /**
     * Sets the value of the decisionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecisionType(final String value) {
        this.decisionType = value;
    }

    /**
     * Gets the value of the ballotId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "BALLOT_ID")
    public String getBallotId() {
        return ballotId;
    }

    /**
     * Sets the value of the ballotId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBallotId(final String value) {
        this.ballotId = value;
    }

    /**
     * Gets the value of the againstProposalParties property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "AGAINST_PROPOSAL_PARTIES")
    public String getAgainstProposalParties() {
        return againstProposalParties;
    }

    /**
     * Sets the value of the againstProposalParties property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgainstProposalParties(final String value) {
        this.againstProposalParties = value;
    }

    /**
     * Gets the value of the againstProposalNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    @Basic
    @Column(name = "AGAINST_PROPOSAL_NUMBER", precision = 20, scale = 10)
    public BigDecimal getAgainstProposalNumber() {
        return againstProposalNumber;
    }

    /**
     * Sets the value of the againstProposalNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAgainstProposalNumber(final BigDecimal value) {
        this.againstProposalNumber = value;
    }

    /**
     * Gets the value of the winner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "WINNER")
    public String getWinner() {
        return winner;
    }

    /**
     * Sets the value of the winner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWinner(final String value) {
        this.winner = value;
    }

    public ViewRiksdagenCommitteeDecisions withEmbeddedId(final ViewRiksdagenCommitteeDecisionsEmbeddedId value) {
        setEmbeddedId(value);
        return this;
    }

    public ViewRiksdagenCommitteeDecisions withTitle(final String value) {
        setTitle(value);
        return this;
    }

    public ViewRiksdagenCommitteeDecisions withHeader(final String value) {
        setHeader(value);
        return this;
    }

    public ViewRiksdagenCommitteeDecisions withCommitteeReport(final String value) {
        setCommitteeReport(value);
        return this;
    }

    public ViewRiksdagenCommitteeDecisions withRm(final String value) {
        setRm(value);
        return this;
    }

    public ViewRiksdagenCommitteeDecisions withEndNumber(final BigDecimal value) {
        setEndNumber(value);
        return this;
    }

    public ViewRiksdagenCommitteeDecisions withOrg(final String value) {
        setOrg(value);
        return this;
    }

    public ViewRiksdagenCommitteeDecisions withCreatedDate(final Date value) {
        setCreatedDate(value);
        return this;
    }

    public ViewRiksdagenCommitteeDecisions withPublicDate(final Date value) {
        setPublicDate(value);
        return this;
    }

    public ViewRiksdagenCommitteeDecisions withCommitteeProposalUrlXml(final String value) {
        setCommitteeProposalUrlXml(value);
        return this;
    }

    public ViewRiksdagenCommitteeDecisions withDecisionType(final String value) {
        setDecisionType(value);
        return this;
    }

    public ViewRiksdagenCommitteeDecisions withBallotId(final String value) {
        setBallotId(value);
        return this;
    }

    public ViewRiksdagenCommitteeDecisions withAgainstProposalParties(final String value) {
        setAgainstProposalParties(value);
        return this;
    }

    public ViewRiksdagenCommitteeDecisions withAgainstProposalNumber(final BigDecimal value) {
        setAgainstProposalNumber(value);
        return this;
    }

    public ViewRiksdagenCommitteeDecisions withWinner(final String value) {
        setWinner(value);
        return this;
    }

	@Override
	public final String toString() {
		return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
	}


    public boolean equals(final ObjectLocator thisLocator, final ObjectLocator thatLocator, final Object object, final EqualsStrategy strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final ViewRiksdagenCommitteeDecisions that = ((ViewRiksdagenCommitteeDecisions) object);
        {
            ViewRiksdagenCommitteeDecisionsEmbeddedId lhsEmbeddedId;
            lhsEmbeddedId = this.getEmbeddedId();
            ViewRiksdagenCommitteeDecisionsEmbeddedId rhsEmbeddedId;
            rhsEmbeddedId = that.getEmbeddedId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "embeddedId", lhsEmbeddedId), LocatorUtils.property(thatLocator, "embeddedId", rhsEmbeddedId), lhsEmbeddedId, rhsEmbeddedId)) {
                return false;
            }
        }
        {
            String lhsTitle;
            lhsTitle = this.getTitle();
            String rhsTitle;
            rhsTitle = that.getTitle();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "title", lhsTitle), LocatorUtils.property(thatLocator, "title", rhsTitle), lhsTitle, rhsTitle)) {
                return false;
            }
        }
        {
            String lhsHeader;
            lhsHeader = this.getHeader();
            String rhsHeader;
            rhsHeader = that.getHeader();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "header", lhsHeader), LocatorUtils.property(thatLocator, "header", rhsHeader), lhsHeader, rhsHeader)) {
                return false;
            }
        }
        {
            String lhsCommitteeReport;
            lhsCommitteeReport = this.getCommitteeReport();
            String rhsCommitteeReport;
            rhsCommitteeReport = that.getCommitteeReport();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "committeeReport", lhsCommitteeReport), LocatorUtils.property(thatLocator, "committeeReport", rhsCommitteeReport), lhsCommitteeReport, rhsCommitteeReport)) {
                return false;
            }
        }
        {
            String lhsRm;
            lhsRm = this.getRm();
            String rhsRm;
            rhsRm = that.getRm();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "rm", lhsRm), LocatorUtils.property(thatLocator, "rm", rhsRm), lhsRm, rhsRm)) {
                return false;
            }
        }
        {
            BigDecimal lhsEndNumber;
            lhsEndNumber = this.getEndNumber();
            BigDecimal rhsEndNumber;
            rhsEndNumber = that.getEndNumber();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "endNumber", lhsEndNumber), LocatorUtils.property(thatLocator, "endNumber", rhsEndNumber), lhsEndNumber, rhsEndNumber)) {
                return false;
            }
        }
        {
            String lhsOrg;
            lhsOrg = this.getOrg();
            String rhsOrg;
            rhsOrg = that.getOrg();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "org", lhsOrg), LocatorUtils.property(thatLocator, "org", rhsOrg), lhsOrg, rhsOrg)) {
                return false;
            }
        }
        {
            Date lhsCreatedDate;
            lhsCreatedDate = this.getCreatedDate();
            Date rhsCreatedDate;
            rhsCreatedDate = that.getCreatedDate();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "createdDate", lhsCreatedDate), LocatorUtils.property(thatLocator, "createdDate", rhsCreatedDate), lhsCreatedDate, rhsCreatedDate)) {
                return false;
            }
        }
        {
            Date lhsPublicDate;
            lhsPublicDate = this.getPublicDate();
            Date rhsPublicDate;
            rhsPublicDate = that.getPublicDate();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "publicDate", lhsPublicDate), LocatorUtils.property(thatLocator, "publicDate", rhsPublicDate), lhsPublicDate, rhsPublicDate)) {
                return false;
            }
        }
        {
            String lhsCommitteeProposalUrlXml;
            lhsCommitteeProposalUrlXml = this.getCommitteeProposalUrlXml();
            String rhsCommitteeProposalUrlXml;
            rhsCommitteeProposalUrlXml = that.getCommitteeProposalUrlXml();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "committeeProposalUrlXml", lhsCommitteeProposalUrlXml), LocatorUtils.property(thatLocator, "committeeProposalUrlXml", rhsCommitteeProposalUrlXml), lhsCommitteeProposalUrlXml, rhsCommitteeProposalUrlXml)) {
                return false;
            }
        }
        {
            String lhsDecisionType;
            lhsDecisionType = this.getDecisionType();
            String rhsDecisionType;
            rhsDecisionType = that.getDecisionType();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "decisionType", lhsDecisionType), LocatorUtils.property(thatLocator, "decisionType", rhsDecisionType), lhsDecisionType, rhsDecisionType)) {
                return false;
            }
        }
        {
            String lhsBallotId;
            lhsBallotId = this.getBallotId();
            String rhsBallotId;
            rhsBallotId = that.getBallotId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "ballotId", lhsBallotId), LocatorUtils.property(thatLocator, "ballotId", rhsBallotId), lhsBallotId, rhsBallotId)) {
                return false;
            }
        }
        {
            String lhsAgainstProposalParties;
            lhsAgainstProposalParties = this.getAgainstProposalParties();
            String rhsAgainstProposalParties;
            rhsAgainstProposalParties = that.getAgainstProposalParties();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "againstProposalParties", lhsAgainstProposalParties), LocatorUtils.property(thatLocator, "againstProposalParties", rhsAgainstProposalParties), lhsAgainstProposalParties, rhsAgainstProposalParties)) {
                return false;
            }
        }
        {
            BigDecimal lhsAgainstProposalNumber;
            lhsAgainstProposalNumber = this.getAgainstProposalNumber();
            BigDecimal rhsAgainstProposalNumber;
            rhsAgainstProposalNumber = that.getAgainstProposalNumber();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "againstProposalNumber", lhsAgainstProposalNumber), LocatorUtils.property(thatLocator, "againstProposalNumber", rhsAgainstProposalNumber), lhsAgainstProposalNumber, rhsAgainstProposalNumber)) {
                return false;
            }
        }
        {
            String lhsWinner;
            lhsWinner = this.getWinner();
            String rhsWinner;
            rhsWinner = that.getWinner();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "winner", lhsWinner), LocatorUtils.property(thatLocator, "winner", rhsWinner), lhsWinner, rhsWinner)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(final Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

	@Override
	public final int hashCode() {
		return HashCodeBuilder.reflectionHashCode(this);
	}

}
