@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    abstract class "<size:14>AbstractRequest\n<size:10>com.hack23.cia.service.api.action.common" as com.hack23.cia.service.api.action.common.AbstractRequest [[AbstractRequest.html]] {
    }

    abstract class "<size:14>AbstractMessage\n<size:10>com.hack23.cia.service.api.action.common" as com.hack23.cia.service.api.action.common.AbstractMessage [[AbstractMessage.html]]
    interface "<size:14>ServiceRequest\n<size:10>com.hack23.cia.service.api.action.common" as com.hack23.cia.service.api.action.common.ServiceRequest [[ServiceRequest.html]]

    com.hack23.cia.service.api.action.common.AbstractMessage <|-- com.hack23.cia.service.api.action.common.AbstractRequest
    com.hack23.cia.service.api.action.common.ServiceRequest <|.. com.hack23.cia.service.api.action.common.AbstractRequest

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
