@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>ServiceMessage\n<size:10>com.hack23.cia.service.api.action.common" as com.hack23.cia.service.api.action.common.ServiceMessage [[ServiceMessage.html]]

    interface "<size:14>Serializable\n<size:10>java.io" as java.io.Serializable

    java.io.Serializable <|.. com.hack23.cia.service.api.action.common.ServiceMessage

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
