@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>ServiceRequest\n<size:10>com.hack23.cia.service.api.action.common" as com.hack23.cia.service.api.action.common.ServiceRequest [[ServiceRequest.html]]

    interface "<size:14>ServiceMessage\n<size:10>com.hack23.cia.service.api.action.common" as com.hack23.cia.service.api.action.common.ServiceMessage [[ServiceMessage.html]]

    com.hack23.cia.service.api.action.common.ServiceMessage <|.. com.hack23.cia.service.api.action.common.ServiceRequest

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
