@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>ServiceResponse\n<size:10>com.hack23.cia.service.api.action.common" as com.hack23.cia.service.api.action.common.ServiceResponse [[ServiceResponse.html]] {
        {abstract} +getResult(): ServiceResult
        {abstract} +getErrorMessage(): String
    }

    interface "<size:14>ServiceMessage\n<size:10>com.hack23.cia.service.api.action.common" as com.hack23.cia.service.api.action.common.ServiceMessage [[ServiceMessage.html]]
    enum "<size:14>ServiceResponse.ServiceResult\n<size:10>com.hack23.cia.service.api.action.common" as com.hack23.cia.service.api.action.common.ServiceResponse.ServiceResult [[ServiceResponse.ServiceResult.html]]

    com.hack23.cia.service.api.action.common.ServiceMessage <|.. com.hack23.cia.service.api.action.common.ServiceResponse
    com.hack23.cia.service.api.action.common.ServiceResponse +-- com.hack23.cia.service.api.action.common.ServiceResponse.ServiceResult

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
