@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    enum "<size:14>ApplicationOperationType\n<size:10>com.hack23.cia.model.internal.application.system.impl" as com.hack23.cia.model.internal.application.system.impl.ApplicationOperationType [[ApplicationOperationType.html]] {
        {static} +CREATE
        {static} +READ
        {static} +UPDATE
        {static} +DELETE
        {static} +AUTHENTICATION
        {static} +AUTHORIZATION
        +value(): String
        {static} +fromValue(String): ApplicationOperationType
    }

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
