@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    abstract class "<size:14>AbstractGhantChartManagerImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.AbstractGhantChartManagerImpl<T> [[AbstractGhantChartManagerImpl.html]] {
        +createRoleGhant(AbstractOrderedLayout, Collection<T>): void
        {abstract} #getComparator(): Comparator<T>
        {abstract} #getRoleMapping(): Function<T, String>
        {abstract} #getStepMapping(): StepMapping<T>
    }
    interface "<size:14>AbstractGhantChartManagerImpl.StepMapping\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.AbstractGhantChartManagerImpl.StepMapping<T> [[AbstractGhantChartManagerImpl.StepMapping.html]]

    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.AbstractGhantChartManagerImpl +-- com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.AbstractGhantChartManagerImpl.StepMapping

    center footer UMLDoclet 2.0.7, PlantUML 1.2019.12
@enduml
