@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>BallotChartDataManagerImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.BallotChartDataManagerImpl [[BallotChartDataManagerImpl.html]] {
        +createChart(Tab, AbstractOrderedLayout, List<ViewRiksdagenVoteDataBallotPartySummary>): void
        +createChart(Tab, AbstractOrderedLayout, ViewRiksdagenVoteDataBallotSummary): void
    }

    abstract class "<size:14>AbstractChartDataManagerImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.AbstractChartDataManagerImpl [[AbstractChartDataManagerImpl.html]]
    interface "<size:14>BallotChartDataManager\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api.BallotChartDataManager [[../api/BallotChartDataManager.html]] {
        {abstract} +createChart(Tab, AbstractOrderedLayout, List<ViewRiksdagenVoteDataBallotPartySummary>): void
        {abstract} +createChart(Tab, AbstractOrderedLayout, ViewRiksdagenVoteDataBallotSummary): void
    }

    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.AbstractChartDataManagerImpl <|-- com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.BallotChartDataManagerImpl
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api.BallotChartDataManager <|.. com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.BallotChartDataManagerImpl

    center footer UMLDoclet 2.0.4, PlantUML 1.2019.06
@enduml
