@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>GovernmentOutcomeChartDataManagerImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.GovernmentOutcomeChartDataManagerImpl [[GovernmentOutcomeChartDataManagerImpl.html]] {
        +createGovernmentOutcomeChart(AbstractOrderedLayout): void
    }

    abstract class "<size:14>AbstractChartDataManagerImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.AbstractChartDataManagerImpl [[AbstractChartDataManagerImpl.html]]
    interface "<size:14>GovernmentOutcomeChartDataManager\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api.GovernmentOutcomeChartDataManager [[../api/GovernmentOutcomeChartDataManager.html]] {
        {abstract} +createGovernmentOutcomeChart(AbstractOrderedLayout): void
    }

    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.AbstractChartDataManagerImpl <|-- com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.GovernmentOutcomeChartDataManagerImpl
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api.GovernmentOutcomeChartDataManager <|.. com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.GovernmentOutcomeChartDataManagerImpl

    center footer UMLDoclet 2.0.12, PlantUML 1.2020.16
@enduml
