@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>PartyGhantChartManagerImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.PartyGhantChartManagerImpl [[PartyGhantChartManagerImpl.html]] {
        #getComparator(): Comparator<ViewRiksdagenPartyRoleMember>
        #getRoleMapping(): Function<ViewRiksdagenPartyRoleMember, String>
        #getStepMapping(): StepMapping<ViewRiksdagenPartyRoleMember>
    }

    abstract class "<size:14>AbstractGhantChartManagerImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.AbstractGhantChartManagerImpl<ViewRiksdagenPartyRoleMember> [[AbstractGhantChartManagerImpl.html]] {
        {abstract} #getComparator(): Comparator<T>
        {abstract} #getRoleMapping(): Function<T, String>
        {abstract} #getStepMapping(): StepMapping<T>
    }
    interface "<size:14>PartyGhantChartManager\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api.PartyGhantChartManager [[../api/PartyGhantChartManager.html]] {
        {abstract} +createRoleGhant(AbstractOrderedLayout, Collection<ViewRiksdagenPartyRoleMember>): void
    }

    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.AbstractGhantChartManagerImpl <|-- com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.PartyGhantChartManagerImpl
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api.PartyGhantChartManager <|.. com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.PartyGhantChartManagerImpl

    center footer UMLDoclet 2.0.6, PlantUML 1.2019.12
@enduml
