@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>WorldIndicatorChartDataManagerImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.WorldIndicatorChartDataManagerImpl [[WorldIndicatorChartDataManagerImpl.html]] {
        +createIndicatorChart(AbstractOrderedLayout, List<WorldBankData>, ViewWorldbankIndicatorDataCountrySummary): void
    }

    abstract class "<size:14>AbstractChartDataManagerImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.AbstractChartDataManagerImpl [[AbstractChartDataManagerImpl.html]]
    interface "<size:14>WorldIndicatorChartDataManager\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api" as com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api.WorldIndicatorChartDataManager [[../api/WorldIndicatorChartDataManager.html]] {
        {abstract} +createIndicatorChart(AbstractOrderedLayout, List<WorldBankData>, ViewWorldbankIndicatorDataCountrySummary): void
    }

    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.AbstractChartDataManagerImpl <|-- com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.WorldIndicatorChartDataManagerImpl
    com.hack23.cia.web.impl.ui.application.views.common.chartfactory.api.WorldIndicatorChartDataManager <|.. com.hack23.cia.web.impl.ui.application.views.common.chartfactory.impl.WorldIndicatorChartDataManagerImpl

    center footer UMLDoclet 2.0.7, PlantUML 1.2019.12
@enduml
