@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SetGoogleAuthenticatorCredentialClickListener\n<size:10>com.hack23.cia.web.impl.ui.application.views.pageclicklistener" as com.hack23.cia.web.impl.ui.application.views.pageclicklistener.SetGoogleAuthenticatorCredentialClickListener [[SetGoogleAuthenticatorCredentialClickListener.html]] {
        +SetGoogleAuthenticatorCredentialClickListener(SetGoogleAuthenticatorCredentialRequest)
        +buttonClick(ClickEvent): void
    }

    interface "<size:14>Button.ClickListener\n<size:10>com.vaadin.ui" as com.vaadin.ui.Button.ClickListener {
        {abstract} +buttonClick(ClickEvent): void
    }

    com.vaadin.ui.Button.ClickListener <|.. com.hack23.cia.web.impl.ui.application.views.pageclicklistener.SetGoogleAuthenticatorCredentialClickListener

    center footer UMLDoclet 2.0.12, PlantUML 1.2020.16
@enduml
