@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>RemoveDataRequest\n<size:10>com.hack23.cia.service.api.action.admin" as com.hack23.cia.service.api.action.admin.RemoveDataRequest [[RemoveDataRequest.html]] {
        +getDataType(): DataType
        +setDataType(DataType): void
        +getSessionId(): String
        +setSessionId(String): void
    }

    abstract class "<size:14>AbstractRequest\n<size:10>com.hack23.cia.service.api.action.common" as com.hack23.cia.service.api.action.common.AbstractRequest [[../common/AbstractRequest.html]]
    enum "<size:14>RemoveDataRequest.DataType\n<size:10>com.hack23.cia.service.api.action.admin" as com.hack23.cia.service.api.action.admin.RemoveDataRequest.DataType [[RemoveDataRequest.DataType.html]]

    com.hack23.cia.service.api.action.common.AbstractRequest <|-- com.hack23.cia.service.api.action.admin.RemoveDataRequest
    com.hack23.cia.service.api.action.admin.RemoveDataRequest +-- com.hack23.cia.service.api.action.admin.RemoveDataRequest.DataType

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
