@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>MinistryRankingAllPartiesChartsPageModContentFactoryImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.user.goverment.pagemode" as com.hack23.cia.web.impl.ui.application.views.user.goverment.pagemode.MinistryRankingAllPartiesChartsPageModContentFactoryImpl [[MinistryRankingAllPartiesChartsPageModContentFactoryImpl.html]] {
        +createContent(String, MenuBar, Panel): Layout
        +matches(String, String): boolean
    }

    abstract class "<size:14>AbstractBasicPageModContentFactoryImpl\n<size:10>com.hack23.cia.web.impl.ui.application.views.common.pagemode" as com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl [[../../../common/pagemode/AbstractBasicPageModContentFactoryImpl.html]]

    com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- com.hack23.cia.web.impl.ui.application.views.user.goverment.pagemode.MinistryRankingAllPartiesChartsPageModContentFactoryImpl

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
