@startuml
    namespace com.hack23.cia.web.impl.ui.application.views.user.goverment.pagemode {

        class MinistryOverviewPageModContentFactoryImpl [[MinistryOverviewPageModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class MinistryRankingAllRolesChartsPageModContentFactoryImpl [[MinistryRankingAllRolesChartsPageModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class MinistryRankingPageVisitHistoryPageModContentFactoryImpl [[MinistryRankingPageVisitHistoryPageModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class MinistryCurrentMembersPageModContentFactoryImpl [[MinistryCurrentMembersPageModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class MinistryRankingGovernmentBodyExpenditurePageModContentFactoryImpl [[MinistryRankingGovernmentBodyExpenditurePageModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class MinistryRankingOverviewPageModContentFactoryImpl [[MinistryRankingOverviewPageModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class MinistryRoleGhantPageModContentFactoryImpl [[MinistryRoleGhantPageModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class MinistryGovernmentBodiesExpenditureModContentFactoryImpl [[MinistryGovernmentBodiesExpenditureModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class MinistryRankingAllMinistriesChartsPageModContentFactoryImpl [[MinistryRankingAllMinistriesChartsPageModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class MinistryGovernmentBodiesHeadcountModContentFactoryImpl [[MinistryGovernmentBodiesHeadcountModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class MinistryRankingAllPartiesChartsPageModContentFactoryImpl [[MinistryRankingAllPartiesChartsPageModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class MinistryRankingGovernmentBodyIncomePageModContentFactoryImpl [[MinistryRankingGovernmentBodyIncomePageModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class MinistryRankingGovernmentOutcomePageModContentFactoryImpl [[MinistryRankingGovernmentOutcomePageModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class MinistryPageVisitHistoryPageModContentFactoryImpl [[MinistryPageVisitHistoryPageModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class MinistryMemberHistoryPageModContentFactoryImpl [[MinistryMemberHistoryPageModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class MinistryDocumentActivityPageModContentFactoryImpl [[MinistryDocumentActivityPageModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class MinistryRankingDataGridPageModContentFactoryImpl [[MinistryRankingDataGridPageModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class MinistryRankingCurrentPartiesChartsPageModContentFactoryImpl [[MinistryRankingCurrentPartiesChartsPageModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class MinistryGovernmentBodiesIncomeModContentFactoryImpl [[MinistryGovernmentBodiesIncomeModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class MinistryRankingCurrentMinistriesChartsPageModContentFactoryImpl [[MinistryRankingCurrentMinistriesChartsPageModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class MinistryRankingGovernmentBodiesPageModContentFactoryImpl [[MinistryRankingGovernmentBodiesPageModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        class MinistryDocumentHistoryPageModContentFactoryImpl [[MinistryDocumentHistoryPageModContentFactoryImpl.html]] {
            +createContent(String, MenuBar, Panel): Layout
            +matches(String, String): boolean
        }

        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractItemPageModContentFactoryImpl <|-- MinistryOverviewPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- MinistryRankingAllRolesChartsPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- MinistryRankingPageVisitHistoryPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractItemPageModContentFactoryImpl <|-- MinistryCurrentMembersPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- MinistryRankingGovernmentBodyExpenditurePageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- MinistryRankingOverviewPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractItemPageModContentFactoryImpl <|-- MinistryRoleGhantPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractItemPageModContentFactoryImpl <|-- MinistryGovernmentBodiesExpenditureModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- MinistryRankingAllMinistriesChartsPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractItemPageModContentFactoryImpl <|-- MinistryGovernmentBodiesHeadcountModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- MinistryRankingAllPartiesChartsPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- MinistryRankingGovernmentBodyIncomePageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- MinistryRankingGovernmentOutcomePageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractItemPageModContentFactoryImpl <|-- MinistryPageVisitHistoryPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractItemPageModContentFactoryImpl <|-- MinistryMemberHistoryPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractItemPageModContentFactoryImpl <|-- MinistryDocumentActivityPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- MinistryRankingDataGridPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- MinistryRankingCurrentPartiesChartsPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractItemPageModContentFactoryImpl <|-- MinistryGovernmentBodiesIncomeModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- MinistryRankingCurrentMinistriesChartsPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractBasicPageModContentFactoryImpl <|-- MinistryRankingGovernmentBodiesPageModContentFactoryImpl
        com.hack23.cia.web.impl.ui.application.views.common.pagemode.AbstractItemPageModContentFactoryImpl <|-- MinistryDocumentHistoryPageModContentFactoryImpl
    }

    namespace com.hack23.cia.web.impl.ui.application.views.common.pagemode {
        abstract class AbstractItemPageModContentFactoryImpl<T> [[../../../common/pagemode/AbstractItemPageModContentFactoryImpl.html]] {
            {abstract} #getItem(String): T
        }
        abstract class AbstractBasicPageModContentFactoryImpl [[../../../common/pagemode/AbstractBasicPageModContentFactoryImpl.html]]
    }

    center footer UMLDoclet 2.0.12, PlantUML 1.2020.16
@enduml
