@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>ApplicationManager\n<size:10>com.hack23.cia.service.api" as com.hack23.cia.service.api.ApplicationManager [[ApplicationManager.html]] {
        {abstract} +getAgentContainer(): AgentContainer
        {abstract} +getDataContainer(Class<T extends Serializable>): DataContainer<T extends Serializable, V extends Serializable>
        {abstract} +service(ServiceRequest): ServiceResponse
        {abstract} +asyncService(ServiceRequest): Future<ServiceResponse>
    }

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
