@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>DocumentsView\n<size:10>com.hack23.cia.web.impl.ui.application.views.user.document" as com.hack23.cia.web.impl.ui.application.views.user.document.DocumentsView [[DocumentsView.html]] {
        {static} +NAME: String
        +DocumentsView(ApplicationContext)
    }

    abstract class "<size:14>AbstractUserView\n<size:10>com.hack23.cia.web.impl.ui.application.views.user.common" as com.hack23.cia.web.impl.ui.application.views.user.common.AbstractUserView [[../common/AbstractUserView.html]]

    com.hack23.cia.web.impl.ui.application.views.user.common.AbstractUserView <|-- com.hack23.cia.web.impl.ui.application.views.user.document.DocumentsView

    center footer UMLDoclet 2.0.3, PlantUML 1.2019.06
@enduml
