@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SearchDocumentView\n<size:10>com.hack23.cia.web.impl.ui.application.views.user.document" as com.hack23.cia.web.impl.ui.application.views.user.document.SearchDocumentView [[SearchDocumentView.html]] {
        {static} +NAME: String
        +SearchDocumentView(ApplicationContext)
    }

    abstract class "<size:14>AbstractUserView\n<size:10>com.hack23.cia.web.impl.ui.application.views.user.common" as com.hack23.cia.web.impl.ui.application.views.user.common.AbstractUserView [[../common/AbstractUserView.html]]

    com.hack23.cia.web.impl.ui.application.views.user.common.AbstractUserView <|-- com.hack23.cia.web.impl.ui.application.views.user.document.SearchDocumentView

    center footer UMLDoclet 2.0.7, PlantUML 1.2019.12
@enduml
